# coding: utf-8

"""
    Netpicker API (Celery 5.5.3)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.4.23.3109
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Events(str, Enum):
    """
    Events
    """

    """
    allowed enum values
    """
    FINISH_COLON_EXECUTE_MINUS_RULES = 'finish:execute-rules'
    FINISH_COLON_BACKUP_MINUS_CONFIG = 'finish:backup-config'
    FINISH_COLON_EXEC_MINUS_JOB = 'finish:exec-job'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Events from a JSON string"""
        return cls(json.loads(json_str))


