# Generated by Django 3.0.5 on 2020-04-29 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_rds_iam_auth', '0015_auto_20200425_1825'),
    ]

    operations = [
        # migrations.RunSQL("""
        #        CREATE POLICY scans_policy ON api_scan
        #             USING (ibrag_user_has_tenant(tenant_id) AND
        #                     (owner_id = cast(current_user as varchar) OR
        #                      ibrag_user_has_role('tenant_admin') OR
        #                      ibrag_user_has_role('tenant_manager')))
        #             WITH CHECK (ibrag_user_has_tenant(tenant_id) AND
        #                     (owner_id = cast(current_user as varchar) OR
        #                      ibrag_user_has_role('tenant_damin')));
        #     """, reverse_sql="drop policy scans_policy on table api_scan;"),
    ]
