"""Global variables."""

COLNAMES = {
    "participants": [
        "record_id",
        "date_created",
        "date_updated",
        "source",
        "name",
        "age_created_months",
        "age_created_days",
        "sex",
        "twin",
        "isdropout",
        "parent1_name",
        "parent1_surname",
        "email1",
        "phone1",
        "parent2_name",
        "parent2_surname",
        "email2",
        "phone2",
        "address",
        "city",
        "postcode",
        "birth_type",
        "gest_weeks",
        "birth_weight",
        "head_circumference",
        "apgar1",
        "apgar2",
        "apgar3",
        "hearing",
        "diagnoses",
        "comments",
        "age_now_months",
        "age_now_days",
    ],
    "appointments": [
        "record_id",
        "appointment_id",
        "study",
        "status",
        "date",
        "date_created",
        "date_updated",
        "taxi_address",
        "taxi_isbooked",
    ],
    "questionnaires": [
        "record_id",
        "redcap_repeat_instance",
        "date_created",
        "date_updated",
        "isestimated",
        "lang1",
        "lang1_exp",
        "lang2",
        "lang2_exp",
        "lang3",
        "lang3_exp",
        "lang4",
        "lang4_exp",
        "comments",
        "complete",
    ],
}
