{
 "title": "StackGen Health",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Pending scans",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(namespace) (pending_workflow_count)",
     "legendFormat": "pending workflows"
    }
   ]
  },
  {
   "title": "Analyzer Scan Duration",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(language) (analyzer_duration_bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 7 },
   "targets": [
    {
     "expr": "avg by(http_method, http_route) (irate(http_server_duration_milliseconds_sum{http_route!=\"/api/v1/health\"}[$__interval]))",
     "legendFormat": "{{http_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "StackGen Error Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by(code, err) (errors_total)"
    }
   ]
  }
 ]
}