# coding: utf-8

"""
    Platform API Documentation

    Combined API documentation for all platform services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from do_sdk_platform.models.hardware_object import HardwareObject

class TestHardwareObject(unittest.TestCase):
    """HardwareObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HardwareObject:
        """Test HardwareObject
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HardwareObject`
        """
        model = HardwareObject()
        if include_optional:
            return HardwareObject(
                cpu = do_sdk_platform.models.cpu_object.CPUObject(
                    architecture = do_sdk_platform.models.cpu_architecture_object.CpuArchitectureObject(
                        main = '', 
                        micro = do_sdk_platform.models.micro.micro(), ), 
                    quantity_vcpu = 1.337, 
                    memory_gb = 1.337, ),
                gpu = do_sdk_platform.models.gpu_object.GPUObject(
                    architecture = do_sdk_platform.models.gpu_architecture_object.GpuArchitectureObject(
                        vendor = '', 
                        microarchitecture = '', 
                        model = '', ), 
                    quantity_gpu = 1.337, 
                    memory_gb = 1.337, ),
                asic_id = '',
                storage_gb = 1.337,
                bandwidth_gb_sec = 1.337
            )
        else:
            return HardwareObject(
                cpu = do_sdk_platform.models.cpu_object.CPUObject(
                    architecture = do_sdk_platform.models.cpu_architecture_object.CpuArchitectureObject(
                        main = '', 
                        micro = do_sdk_platform.models.micro.micro(), ), 
                    quantity_vcpu = 1.337, 
                    memory_gb = 1.337, ),
                gpu = do_sdk_platform.models.gpu_object.GPUObject(
                    architecture = do_sdk_platform.models.gpu_architecture_object.GpuArchitectureObject(
                        vendor = '', 
                        microarchitecture = '', 
                        model = '', ), 
                    quantity_gpu = 1.337, 
                    memory_gb = 1.337, ),
                asic_id = '',
                storage_gb = 1.337,
                bandwidth_gb_sec = 1.337,
        )
        """

    def testHardwareObject(self):
        """Test HardwareObject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
