# coding: utf-8

"""
    Platform API Documentation

    Combined API documentation for all platform services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from do_sdk_platform.models.api_contact_us200_response import ApiContactUs200Response

class TestApiContactUs200Response(unittest.TestCase):
    """ApiContactUs200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiContactUs200Response:
        """Test ApiContactUs200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiContactUs200Response`
        """
        model = ApiContactUs200Response()
        if include_optional:
            return ApiContactUs200Response(
                links = do_sdk_platform.models.http_links_dto.HttpLinksDto(
                    self = '', 
                    next = '', 
                    prev = '', 
                    first = '', ),
                data = [
                    do_sdk_platform.models.api_update_billing_address_200_response_data.apiUpdateBillingAddress_200_response_data(
                        id = '', 
                        type = '', 
                        attributes = do_sdk_platform.models.success_dto.SuccessDto(
                            is_success = True, ), )
                    ]
            )
        else:
            return ApiContactUs200Response(
                links = do_sdk_platform.models.http_links_dto.HttpLinksDto(
                    self = '', 
                    next = '', 
                    prev = '', 
                    first = '', ),
                data = [
                    do_sdk_platform.models.api_update_billing_address_200_response_data.apiUpdateBillingAddress_200_response_data(
                        id = '', 
                        type = '', 
                        attributes = do_sdk_platform.models.success_dto.SuccessDto(
                            is_success = True, ), )
                    ],
        )
        """

    def testApiContactUs200Response(self):
        """Test ApiContactUs200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
