# coding: utf-8

"""
    Platform API Documentation

    Combined API documentation for all platform services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from do_sdk_platform.models.nucleus_api_list_chat_thread_messages200_response_data_messages_inner_content_inner_any_of2 import NucleusApiListChatThreadMessages200ResponseDataMessagesInnerContentInnerAnyOf2

class TestNucleusApiListChatThreadMessages200ResponseDataMessagesInnerContentInnerAnyOf2(unittest.TestCase):
    """NucleusApiListChatThreadMessages200ResponseDataMessagesInnerContentInnerAnyOf2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NucleusApiListChatThreadMessages200ResponseDataMessagesInnerContentInnerAnyOf2:
        """Test NucleusApiListChatThreadMessages200ResponseDataMessagesInnerContentInnerAnyOf2
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NucleusApiListChatThreadMessages200ResponseDataMessagesInnerContentInnerAnyOf2`
        """
        model = NucleusApiListChatThreadMessages200ResponseDataMessagesInnerContentInnerAnyOf2()
        if include_optional:
            return NucleusApiListChatThreadMessages200ResponseDataMessagesInnerContentInnerAnyOf2(
                type = 'image_url',
                image_url = do_sdk_platform.models.nucleus_api_list_chat_thread_messages_200_response_data_messages_inner_content_inner_any_of_2_image_url.nucleus_apiListChatThreadMessages_200_response_data_messages_inner_content_inner_anyOf_2_image_url(
                    url = '', )
            )
        else:
            return NucleusApiListChatThreadMessages200ResponseDataMessagesInnerContentInnerAnyOf2(
                type = 'image_url',
                image_url = do_sdk_platform.models.nucleus_api_list_chat_thread_messages_200_response_data_messages_inner_content_inner_any_of_2_image_url.nucleus_apiListChatThreadMessages_200_response_data_messages_inner_content_inner_anyOf_2_image_url(
                    url = '', ),
        )
        """

    def testNucleusApiListChatThreadMessages200ResponseDataMessagesInnerContentInnerAnyOf2(self):
        """Test NucleusApiListChatThreadMessages200ResponseDataMessagesInnerContentInnerAnyOf2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
