# coding: utf-8

"""
    Platform API Documentation

    Combined API documentation for all platform services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from do_sdk_platform.models.nucleus_api_delete_database200_response import NucleusApiDeleteDatabase200Response

class TestNucleusApiDeleteDatabase200Response(unittest.TestCase):
    """NucleusApiDeleteDatabase200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NucleusApiDeleteDatabase200Response:
        """Test NucleusApiDeleteDatabase200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NucleusApiDeleteDatabase200Response`
        """
        model = NucleusApiDeleteDatabase200Response()
        if include_optional:
            return NucleusApiDeleteDatabase200Response(
                data = do_sdk_platform.models.attributes.attributes()
            )
        else:
            return NucleusApiDeleteDatabase200Response(
                data = do_sdk_platform.models.attributes.attributes(),
        )
        """

    def testNucleusApiDeleteDatabase200Response(self):
        """Test NucleusApiDeleteDatabase200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
