# coding: utf-8

"""
    Platform API Documentation

    Combined API documentation for all platform services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from do_sdk_platform.models.api_get_recent_activity200_response import ApiGetRecentActivity200Response

class TestApiGetRecentActivity200Response(unittest.TestCase):
    """ApiGetRecentActivity200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiGetRecentActivity200Response:
        """Test ApiGetRecentActivity200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiGetRecentActivity200Response`
        """
        model = ApiGetRecentActivity200Response()
        if include_optional:
            return ApiGetRecentActivity200Response(
                links = do_sdk_platform.models.http_links_dto.HttpLinksDto(
                    self = '', 
                    next = '', 
                    prev = '', 
                    first = '', ),
                data = [
                    do_sdk_platform.models.api_get_recent_activity_200_response_data_inner.apiGetRecentActivity_200_response_data_inner(
                        id = '', 
                        type = '', 
                        attributes = do_sdk_platform.models.recent_activity_item_schema_dto.RecentActivityItemSchemaDto(
                            date = '', 
                            name = '0', 
                            total = 0, 
                            free_actions = 0, 
                            paid_amount = 0, ), )
                    ]
            )
        else:
            return ApiGetRecentActivity200Response(
                links = do_sdk_platform.models.http_links_dto.HttpLinksDto(
                    self = '', 
                    next = '', 
                    prev = '', 
                    first = '', ),
                data = [
                    do_sdk_platform.models.api_get_recent_activity_200_response_data_inner.apiGetRecentActivity_200_response_data_inner(
                        id = '', 
                        type = '', 
                        attributes = do_sdk_platform.models.recent_activity_item_schema_dto.RecentActivityItemSchemaDto(
                            date = '', 
                            name = '0', 
                            total = 0, 
                            free_actions = 0, 
                            paid_amount = 0, ), )
                    ],
        )
        """

    def testApiGetRecentActivity200Response(self):
        """Test ApiGetRecentActivity200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
