# coding: utf-8

"""
    Platform API Documentation

    Combined API documentation for all platform services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from do_sdk_platform.models.nucleus_api_add_database_column200_response import NucleusApiAddDatabaseColumn200Response

class TestNucleusApiAddDatabaseColumn200Response(unittest.TestCase):
    """NucleusApiAddDatabaseColumn200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NucleusApiAddDatabaseColumn200Response:
        """Test NucleusApiAddDatabaseColumn200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NucleusApiAddDatabaseColumn200Response`
        """
        model = NucleusApiAddDatabaseColumn200Response()
        if include_optional:
            return NucleusApiAddDatabaseColumn200Response(
                data = do_sdk_platform.models.nucleus_api_add_database_column_200_response_data.nucleus_apiAddDatabaseColumn_200_response_data(
                    column = null, 
                    database = do_sdk_platform.models.database.Database(
                        id = '', 
                        type = 'database', 
                        hid = '', 
                        name = '', 
                        date_created = '', 
                        date_updated = '', 
                        created_by_user_drn = '', 
                        edited_by_user_drn = '', 
                        parent_id = '', 
                        parent_hid = '', 
                        creation_parent_id = '', 
                        creation_block_id = '', 
                        hid_prefix = '', 
                        cols = [
                            null
                            ], 
                        row_json_schema = do_sdk_platform.models.row_json_schema.rowJsonSchema(), 
                        editor = null, 
                        is_inline_database = True, 
                        is_locked = True, ), )
            )
        else:
            return NucleusApiAddDatabaseColumn200Response(
                data = do_sdk_platform.models.nucleus_api_add_database_column_200_response_data.nucleus_apiAddDatabaseColumn_200_response_data(
                    column = null, 
                    database = do_sdk_platform.models.database.Database(
                        id = '', 
                        type = 'database', 
                        hid = '', 
                        name = '', 
                        date_created = '', 
                        date_updated = '', 
                        created_by_user_drn = '', 
                        edited_by_user_drn = '', 
                        parent_id = '', 
                        parent_hid = '', 
                        creation_parent_id = '', 
                        creation_block_id = '', 
                        hid_prefix = '', 
                        cols = [
                            null
                            ], 
                        row_json_schema = do_sdk_platform.models.row_json_schema.rowJsonSchema(), 
                        editor = null, 
                        is_inline_database = True, 
                        is_locked = True, ), ),
        )
        """

    def testNucleusApiAddDatabaseColumn200Response(self):
        """Test NucleusApiAddDatabaseColumn200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
