# coding: utf-8

"""
    Platform API Documentation

    Combined API documentation for all platform services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from do_sdk_platform.models.nucleus_api_list_files200_response_data_inner_assignments_inner import NucleusApiListFiles200ResponseDataInnerAssignmentsInner

class TestNucleusApiListFiles200ResponseDataInnerAssignmentsInner(unittest.TestCase):
    """NucleusApiListFiles200ResponseDataInnerAssignmentsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NucleusApiListFiles200ResponseDataInnerAssignmentsInner:
        """Test NucleusApiListFiles200ResponseDataInnerAssignmentsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NucleusApiListFiles200ResponseDataInnerAssignmentsInner`
        """
        model = NucleusApiListFiles200ResponseDataInnerAssignmentsInner()
        if include_optional:
            return NucleusApiListFiles200ResponseDataInnerAssignmentsInner(
                row_id = ''
            )
        else:
            return NucleusApiListFiles200ResponseDataInnerAssignmentsInner(
                row_id = '',
        )
        """

    def testNucleusApiListFiles200ResponseDataInnerAssignmentsInner(self):
        """Test NucleusApiListFiles200ResponseDataInnerAssignmentsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
