# coding: utf-8

"""
    Platform API Documentation

    Combined API documentation for all platform services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from do_sdk_platform.models.nucleus_api_send_chat_message_request_messages_inner import NucleusApiSendChatMessageRequestMessagesInner

class TestNucleusApiSendChatMessageRequestMessagesInner(unittest.TestCase):
    """NucleusApiSendChatMessageRequestMessagesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NucleusApiSendChatMessageRequestMessagesInner:
        """Test NucleusApiSendChatMessageRequestMessagesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NucleusApiSendChatMessageRequestMessagesInner`
        """
        model = NucleusApiSendChatMessageRequestMessagesInner()
        if include_optional:
            return NucleusApiSendChatMessageRequestMessagesInner(
                content = '0',
                role = 'user'
            )
        else:
            return NucleusApiSendChatMessageRequestMessagesInner(
                content = '0',
                role = 'user',
        )
        """

    def testNucleusApiSendChatMessageRequestMessagesInner(self):
        """Test NucleusApiSendChatMessageRequestMessagesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
