# coding: utf-8

"""
    Platform API Documentation

    Combined API documentation for all platform services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from do_sdk_platform.models.credit_history_dto import CreditHistoryDto

class TestCreditHistoryDto(unittest.TestCase):
    """CreditHistoryDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreditHistoryDto:
        """Test CreditHistoryDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreditHistoryDto`
        """
        model = CreditHistoryDto()
        if include_optional:
            return CreditHistoryDto(
                item = 'Monthly Service Fee',
                var_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                credits = 15,
                discount_credits = 2,
                total_credits = 17,
                id = 'hist_001'
            )
        else:
            return CreditHistoryDto(
                item = 'Monthly Service Fee',
                var_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                credits = 15,
                discount_credits = 2,
                total_credits = 17,
                id = 'hist_001',
        )
        """

    def testCreditHistoryDto(self):
        """Test CreditHistoryDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
