# coding: utf-8

"""
    Platform API Documentation

    Combined API documentation for all platform services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from do_sdk_platform.models.api_list_notifications200_response import ApiListNotifications200Response

class TestApiListNotifications200Response(unittest.TestCase):
    """ApiListNotifications200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiListNotifications200Response:
        """Test ApiListNotifications200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiListNotifications200Response`
        """
        model = ApiListNotifications200Response()
        if include_optional:
            return ApiListNotifications200Response(
                links = do_sdk_platform.models.http_links_dto.HttpLinksDto(
                    self = '', 
                    next = '', 
                    prev = '', 
                    first = '', ),
                data = [
                    do_sdk_platform.models.api_list_notifications_200_response_data_inner.apiListNotifications_200_response_data_inner(
                        id = '', 
                        type = '', 
                        attributes = do_sdk_platform.models.billing_notification_schema_dto.BillingNotificationSchemaDto(
                            id = '0', 
                            org_friendly_id = '0', 
                            title = '012', 
                            description = '01234', 
                            buttons = 'ok', 
                            severity = 'success', 
                            type = 'toast', 
                            is_read = True, 
                            created_at = null, ), )
                    ]
            )
        else:
            return ApiListNotifications200Response(
                links = do_sdk_platform.models.http_links_dto.HttpLinksDto(
                    self = '', 
                    next = '', 
                    prev = '', 
                    first = '', ),
                data = [
                    do_sdk_platform.models.api_list_notifications_200_response_data_inner.apiListNotifications_200_response_data_inner(
                        id = '', 
                        type = '', 
                        attributes = do_sdk_platform.models.billing_notification_schema_dto.BillingNotificationSchemaDto(
                            id = '0', 
                            org_friendly_id = '0', 
                            title = '012', 
                            description = '01234', 
                            buttons = 'ok', 
                            severity = 'success', 
                            type = 'toast', 
                            is_read = True, 
                            created_at = null, ), )
                    ],
        )
        """

    def testApiListNotifications200Response(self):
        """Test ApiListNotifications200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
