# coding: utf-8

"""
    Platform API Documentation

    Combined API documentation for all platform services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from do_sdk_platform.models.tool_manifest_schema_dto_executors_inner_resource_requirements import ToolManifestSchemaDtoExecutorsInnerResourceRequirements

class TestToolManifestSchemaDtoExecutorsInnerResourceRequirements(unittest.TestCase):
    """ToolManifestSchemaDtoExecutorsInnerResourceRequirements unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ToolManifestSchemaDtoExecutorsInnerResourceRequirements:
        """Test ToolManifestSchemaDtoExecutorsInnerResourceRequirements
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ToolManifestSchemaDtoExecutorsInnerResourceRequirements`
        """
        model = ToolManifestSchemaDtoExecutorsInnerResourceRequirements()
        if include_optional:
            return ToolManifestSchemaDtoExecutorsInnerResourceRequirements(
                processor_affinity = True,
                cpu = 1.337,
                memory = 1.337,
                gpu = 1.337,
                preemptible = True,
                zones = [
                    ''
                    ]
            )
        else:
            return ToolManifestSchemaDtoExecutorsInnerResourceRequirements(
                cpu = 1.337,
                memory = 1.337,
        )
        """

    def testToolManifestSchemaDtoExecutorsInnerResourceRequirements(self):
        """Test ToolManifestSchemaDtoExecutorsInnerResourceRequirements"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
