from redis import Redis


class RedisKeysManager:
    redis_client: Redis
    def __init__(self, redis_client: Redis) -> None: ...
    def get_city_keys(self, city: str) -> list[str]: ...
    def delete_city_keys(self, city: str) -> None: ...
