# coding: utf-8

"""
    Skyledge API

    Sky Ledge is an operational insights platform that gives you the visibility and control you need to minimise inefficiencies, oversight, theft, and ultimately, unnecessary costs associated with your operations.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skyledge_sdk.api.list_places_controller_api import ListPlacesControllerApi


class TestListPlacesControllerApi(unittest.TestCase):
    """ListPlacesControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ListPlacesControllerApi()

    def tearDown(self) -> None:
        pass

    def test_list_places_for_control_room(self) -> None:
        """Test case for list_places_for_control_room

        """
        pass


if __name__ == '__main__':
    unittest.main()
