# coding: utf-8

"""
    Skyledge API

    Sky Ledge is an operational insights platform that gives you the visibility and control you need to minimise inefficiencies, oversight, theft, and ultimately, unnecessary costs associated with your operations.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skyledge_sdk.api.update_asset_type_table_view_controller_api import UpdateAssetTypeTableViewControllerApi


class TestUpdateAssetTypeTableViewControllerApi(unittest.TestCase):
    """UpdateAssetTypeTableViewControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UpdateAssetTypeTableViewControllerApi()

    def tearDown(self) -> None:
        pass

    def test_update_asset_table_view(self) -> None:
        """Test case for update_asset_table_view

        """
        pass


if __name__ == '__main__':
    unittest.main()
