# coding: utf-8

"""
    Platform API Documentation

    Combined API documentation for all platform services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Optional
from do_sdk_platform.models.nucleus_api_list_rows_request_filters_inner_any_of import NucleusApiListRowsRequestFiltersInnerAnyOf
from do_sdk_platform.models.nucleus_api_list_rows_request_filters_inner_any_of1 import NucleusApiListRowsRequestFiltersInnerAnyOf1
from do_sdk_platform.models.nucleus_api_list_rows_request_filters_inner_any_of2 import NucleusApiListRowsRequestFiltersInnerAnyOf2
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

NUCLEUSAPILISTROWSREQUESTFILTERSINNER_ANY_OF_SCHEMAS = ["NucleusApiListRowsRequestFiltersInnerAnyOf", "NucleusApiListRowsRequestFiltersInnerAnyOf1", "NucleusApiListRowsRequestFiltersInnerAnyOf2"]

class NucleusApiListRowsRequestFiltersInner(BaseModel):
    """
    NucleusApiListRowsRequestFiltersInner
    """

    # data type: NucleusApiListRowsRequestFiltersInnerAnyOf
    anyof_schema_1_validator: Optional[NucleusApiListRowsRequestFiltersInnerAnyOf] = None
    # data type: NucleusApiListRowsRequestFiltersInnerAnyOf1
    anyof_schema_2_validator: Optional[NucleusApiListRowsRequestFiltersInnerAnyOf1] = None
    # data type: NucleusApiListRowsRequestFiltersInnerAnyOf2
    anyof_schema_3_validator: Optional[NucleusApiListRowsRequestFiltersInnerAnyOf2] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[NucleusApiListRowsRequestFiltersInnerAnyOf, NucleusApiListRowsRequestFiltersInnerAnyOf1, NucleusApiListRowsRequestFiltersInnerAnyOf2]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "NucleusApiListRowsRequestFiltersInnerAnyOf", "NucleusApiListRowsRequestFiltersInnerAnyOf1", "NucleusApiListRowsRequestFiltersInnerAnyOf2" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = NucleusApiListRowsRequestFiltersInner.model_construct()
        error_messages = []
        # validate data type: NucleusApiListRowsRequestFiltersInnerAnyOf
        if not isinstance(v, NucleusApiListRowsRequestFiltersInnerAnyOf):
            error_messages.append(f"Error! Input type `{type(v)}` is not `NucleusApiListRowsRequestFiltersInnerAnyOf`")
        else:
            return v

        # validate data type: NucleusApiListRowsRequestFiltersInnerAnyOf1
        if not isinstance(v, NucleusApiListRowsRequestFiltersInnerAnyOf1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `NucleusApiListRowsRequestFiltersInnerAnyOf1`")
        else:
            return v

        # validate data type: NucleusApiListRowsRequestFiltersInnerAnyOf2
        if not isinstance(v, NucleusApiListRowsRequestFiltersInnerAnyOf2):
            error_messages.append(f"Error! Input type `{type(v)}` is not `NucleusApiListRowsRequestFiltersInnerAnyOf2`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in NucleusApiListRowsRequestFiltersInner with anyOf schemas: NucleusApiListRowsRequestFiltersInnerAnyOf, NucleusApiListRowsRequestFiltersInnerAnyOf1, NucleusApiListRowsRequestFiltersInnerAnyOf2. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[NucleusApiListRowsRequestFiltersInnerAnyOf] = None
        try:
            instance.actual_instance = NucleusApiListRowsRequestFiltersInnerAnyOf.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[NucleusApiListRowsRequestFiltersInnerAnyOf1] = None
        try:
            instance.actual_instance = NucleusApiListRowsRequestFiltersInnerAnyOf1.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_3_validator: Optional[NucleusApiListRowsRequestFiltersInnerAnyOf2] = None
        try:
            instance.actual_instance = NucleusApiListRowsRequestFiltersInnerAnyOf2.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into NucleusApiListRowsRequestFiltersInner with anyOf schemas: NucleusApiListRowsRequestFiltersInnerAnyOf, NucleusApiListRowsRequestFiltersInnerAnyOf1, NucleusApiListRowsRequestFiltersInnerAnyOf2. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], NucleusApiListRowsRequestFiltersInnerAnyOf, NucleusApiListRowsRequestFiltersInnerAnyOf1, NucleusApiListRowsRequestFiltersInnerAnyOf2]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


