# coding: utf-8

# flake8: noqa

"""
    Data Space Search Service

    The Search Service is a service of the Data Space Node, designed to process search queries and aggregate results from decentralized catalogs.

    The version of the OpenAPI document: 0.2.2
    Contact: all-hiro@hiro-microdatacenters.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from ds_search_service.api.decentralized_search_api import DecentralizedSearchApi
from ds_search_service.api.local_search_api import LocalSearchApi
from ds_search_service.api.default_api import DefaultApi

# import ApiClient
from ds_search_service.api_response import ApiResponse
from ds_search_service.api_client import ApiClient
from ds_search_service.configuration import Configuration
from ds_search_service.exceptions import OpenApiException
from ds_search_service.exceptions import ApiTypeError
from ds_search_service.exceptions import ApiValueError
from ds_search_service.exceptions import ApiKeyError
from ds_search_service.exceptions import ApiAttributeError
from ds_search_service.exceptions import ApiException

# import models into sdk package
from ds_search_service.models.http_validation_error import HTTPValidationError
from ds_search_service.models.health_check import HealthCheck
from ds_search_service.models.validation_error import ValidationError
from ds_search_service.models.validation_error_loc_inner import ValidationErrorLocInner
