# coding: utf-8

"""
    Platform API Documentation

    Combined API documentation for all platform services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from do_sdk_platform.models.function_definition_schema_dto_executor_environment_inner import FunctionDefinitionSchemaDtoExecutorEnvironmentInner
from do_sdk_platform.models.function_definition_schema_dto_executor_port_inner import FunctionDefinitionSchemaDtoExecutorPortInner
from do_sdk_platform.models.function_definition_schema_dto_executor_resource_requirements import FunctionDefinitionSchemaDtoExecutorResourceRequirements
from typing import Optional, Set
from typing_extensions import Self

class FunctionDefinitionSchemaDtoExecutor(BaseModel):
    """
    FunctionDefinitionSchemaDtoExecutor
    """ # noqa: E501
    container_concurrency: Union[StrictFloat, StrictInt] = Field(alias="containerConcurrency")
    environment: Optional[List[FunctionDefinitionSchemaDtoExecutorEnvironmentInner]] = None
    image: StrictStr
    method: StrictStr
    min_scale: Union[StrictFloat, StrictInt] = Field(alias="minScale")
    name: StrictStr
    path: StrictStr
    port: Optional[List[FunctionDefinitionSchemaDtoExecutorPortInner]] = None
    resource_requirements: FunctionDefinitionSchemaDtoExecutorResourceRequirements = Field(alias="resourceRequirements")
    response_start_timeout_seconds: Union[StrictFloat, StrictInt] = Field(alias="responseStartTimeoutSeconds")
    scale_down_delay_seconds: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="scaleDownDelaySeconds")
    timeout_seconds: Union[StrictFloat, StrictInt] = Field(alias="timeoutSeconds")
    url: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["containerConcurrency", "environment", "image", "method", "minScale", "name", "path", "port", "resourceRequirements", "responseStartTimeoutSeconds", "scaleDownDelaySeconds", "timeoutSeconds", "url"]

    @field_validator('method')
    def method_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['POST']):
            raise ValueError("must be one of enum values ('POST')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FunctionDefinitionSchemaDtoExecutor from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in environment (list)
        _items = []
        if self.environment:
            for _item_environment in self.environment:
                if _item_environment:
                    _items.append(_item_environment.to_dict())
            _dict['environment'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in port (list)
        _items = []
        if self.port:
            for _item_port in self.port:
                if _item_port:
                    _items.append(_item_port.to_dict())
            _dict['port'] = _items
        # override the default output from pydantic by calling `to_dict()` of resource_requirements
        if self.resource_requirements:
            _dict['resourceRequirements'] = self.resource_requirements.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FunctionDefinitionSchemaDtoExecutor from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "containerConcurrency": obj.get("containerConcurrency"),
            "environment": [FunctionDefinitionSchemaDtoExecutorEnvironmentInner.from_dict(_item) for _item in obj["environment"]] if obj.get("environment") is not None else None,
            "image": obj.get("image"),
            "method": obj.get("method"),
            "minScale": obj.get("minScale"),
            "name": obj.get("name"),
            "path": obj.get("path"),
            "port": [FunctionDefinitionSchemaDtoExecutorPortInner.from_dict(_item) for _item in obj["port"]] if obj.get("port") is not None else None,
            "resourceRequirements": FunctionDefinitionSchemaDtoExecutorResourceRequirements.from_dict(obj["resourceRequirements"]) if obj.get("resourceRequirements") is not None else None,
            "responseStartTimeoutSeconds": obj.get("responseStartTimeoutSeconds"),
            "scaleDownDelaySeconds": obj.get("scaleDownDelaySeconds"),
            "timeoutSeconds": obj.get("timeoutSeconds"),
            "url": obj.get("url")
        })
        return _obj


