# coding: utf-8

"""
    DJ Set Downloader API

    A REST API for downloading and processing DJ sets, splitting them into individual tracks.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dj_set_downloader.api.process_api import ProcessApi


class TestProcessApi(unittest.TestCase):
    """ProcessApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProcessApi()

    def tearDown(self) -> None:
        pass

    def test_api_process_post(self) -> None:
        """Test case for api_process_post

        Process a DJ set URL with tracklist
        """
        pass


if __name__ == '__main__':
    unittest.main()
