# coding: utf-8

"""
    Skyledge API

    Sky Ledge is an operational insights platform that gives you the visibility and control you need to minimise inefficiencies, oversight, theft, and ultimately, unnecessary costs associated with your operations.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skyledge_sdk.api.get_asset_active_events_controller_api import GetAssetActiveEventsControllerApi


class TestGetAssetActiveEventsControllerApi(unittest.TestCase):
    """GetAssetActiveEventsControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GetAssetActiveEventsControllerApi()

    def tearDown(self) -> None:
        pass

    def test_retrieve_latest100_active_events(self) -> None:
        """Test case for retrieve_latest100_active_events

        """
        pass


if __name__ == '__main__':
    unittest.main()
