// This file is autogenerated. DO NOT EDIT

#pragma once
#include <semiwrap.h>

// wrapped header

#include <rev/config/SmartMotionConfig.h>

#include <trampolines/rev__BaseConfig.hpp>

namespace rev::spark {

template <typename CfgBase = swgen::EmptyTrampolineCfg>
struct PyTrampolineCfg_SmartMotionConfig :
  rev::PyTrampolineCfg_BaseConfig<
  CfgBase
  >
{
  using Base = rev::spark::SmartMotionConfig;
};

template <typename PyTrampolineBase, typename PyTrampolineCfg>
using PyTrampolineBase_SmartMotionConfig =
  rev::PyTrampoline_BaseConfig<
    PyTrampolineBase
    , PyTrampolineCfg>
;

template <typename PyTrampolineBase, typename PyTrampolineCfg>
struct PyTrampoline_SmartMotionConfig : PyTrampolineBase_SmartMotionConfig<PyTrampolineBase, PyTrampolineCfg> {
  using PyTrampolineBase_SmartMotionConfig<PyTrampolineBase, PyTrampolineCfg>::PyTrampolineBase_SmartMotionConfig;
};

}; // namespace rev::spark
