
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-07-22T17:27:56+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "80d4d2cbdabca40211dabb95dba0eb25fb38a4c6",
 "version": "0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
