# This file contains the python script that has been created for every workbook sheet
# that has been provided for each module. This file is used by the DoConfig.py script
# and ideally should never change. An entry should be added everytime when a new script
# is developed for a config workbook sheet

# **IMPORTANT** - Do not change the existing IDs below as it is used in other scripts for
# identifying the correct sheet and script

# Note: For a single worksheet, if there are multiple scripts, enter them in the required
# order separated by a semicolon

from ConfigAutomation.Baseline.src.ConfigFileNames import *

Script2Run = {
    # General Ledger
    LEGAL_ENTITY_SHEET: "/src/ERP/GL/ManageLegalAddress.py;/src/ERP/GL/ManageLegalEntity.py",
    LEGAL_ENTITY_REG: "/src/ERP/GL/ManageLegalEntityRegistrations.py",
    LEGAL_REPORTING_UNIT: "/src/ERP/GL/ManageLegalReportingUnit.py",
    CURRENCY: "/src/ERP/GL/ManageCurrencies.py",
    ACC_CALENDAR: "/src/ERP/GL/ManageAccountingCalendars.py",
    CHART_OF_ACCOUNT: "/src/ERP/GL/CreateCOAValueSets.py;/src/ERP/GL/CreateCOAStructure.py;/src/ERP/GL/CreateCOASegmentLabels.py;/src/ERP/GL/AssignCOASegmentLabels.py;/src/ERP/GL/CreateCOAStructureInstance.py",
    FUND: "/src/ERP/GL/LoadValuesForFund.py",
    COST_CENTER: "/src/ERP/GL/LoadValuesForCostCenter.py",
    ACCOUNT: "/src/ERP/GL/LoadValuesForAccount.py",
    ACTIVITY: "/src/ERP/GL/LoadValuesForActivity.py",
    INTERFUND: "/src/ERP/GL/LoadValuesForInterfund.py",
    FUTURE1: "/src/ERP/GL/LoadValuesForFuture1.py",
    FUTURE2: "/src/ERP/GL/LoadValuesForFuture2.py;/src/ERP/GL/DeployFlexFields.py",
    MANAGE_ACCOUNTING_METHOD: "/src/ERP/GL/ManageAccountingMethod.py",
    MANAGE_CONV_RATES_TYPES: "/src/ERP/GL/ManageConversionRateTypes.py",
    JRNL_SOURCES: "/src/ERP/GL/ManageJournalSources.py",
    JRNL_CATEGORIES: "/src/ERP/GL/ManageJournalCategories.py",
    MANAGE_JRNL_REVERSALSETS: "/src/ERP/GL/ManageJournalReversalCrieteriaSets.py",
    LEDGER: "/src/ERP/GL/ManagePrimaryLedgers.py;/src/ERP/GL/SpecifyLedgerOptions.py",
    LEDGERSETS: "/src/ERP/GL/ManageLedgerSets.py",
    ASSIGN_LEGAL_ENTITY: "/src/ERP/GL/AssignLegalEntity.py",
    ASSIGN_BAL_SGMT_VALUE_LE: "/src/ERP/GL/AssignBalancingsegmentValuestoLegalEntity.py",
    MANAGE_SECONDARY_LEDGERS: "/src/ERP/GL/ManageSecondaryLedgers.py;/src/ERP/GL/ManagePrimarytoSecondaryLedgerMapping.py",
    BU: "/src/ERP/GL/ManageBusinessUnit.py;/src/ERP/GL/AssignBusinessUnitBusinessFunctions.py",
    DATA_ACCESS_SET: "/src/ERP/GL/ManageDataAccessSets.py",
    MANAGE_AUTO_POST_SETS: "/src/ERP/GL/ManageAutoPostCriteriaSets.py",
    MANAGE_GL_DESCRIPTIVE_FLEXFIELDS: "/src/ERP/GL/ManageGeneralLedgerDescriptiveFlexfields.py",
    GL_DFF_VALUES: "/src/ERP/GL/ManageDFFValues_GL.py",

    # IC_SUPPLIER_ASSOCIATION: "/src/ERP/GL/ManageIntercompanyCustomerSupplierAssociation.py",
    # MANAGE_ADD_INTERCOMPANY_CLEARING: "/src/ERP/GL/.py",
    # MANAGE_IC_TRANSACTIONTYPES: "/src/ERP/GL/.py",
    # MANAGE_IC_ORGANIZATIONS: "/src/ERP/GL/.py",

    # AP
    INVOICE_TOLERANCES: "/src/ERP/AP/ManageInvoiceTolerances.py",
    PAYMENT_TERMS: "/src/ERP/AP/ManagePaymentTerms.py",
    INVOICE_HOLDS_RELEASES: "/src/ERP/AP/ManageInvoiceHoldsandReleases.py",
    PAYABLES_CALENDAR: "/src/ERP/AP/ManagePayablesCalendars.py",
    PAY_GROUP: "/src/ERP/AP/ManagePayablesLookups.py",
    COMMON_OPTIONS: "/src/ERP/AP/ManageCommonOptionsforPayablesandProcurement.py",
    INVOICE_OPTIONS: "/src/ERP/AP/ManageInvoiceOptions.py",
    PAYMENT_OPTIONS: "/src/ERP/AP/ManagePaymentOptions.py",
    DFF_VALUES: "/src/ERP/AP/Manage DFF Values.py",
    PAYABLES_DESCRIPTIVE_FLEXFIELD: "/src/ERP/AP/ManagePayablesDescriptiveFlexfields.py",
    PAYABLES_DOC_SEQUENCE: "/src/ERP/AP/ManagePayablesDocumentSequences.py",
    PAYMENT_METHODS: "/src/ERP/AP/ManagePaymentMethods.py",
    PAYMENT_METHOD_DEFAULTING_RULE: "/src/ERP/AP/ManagePaymentMethodDefaultingRules.py",
    TRANSMISSION_CONFIG: "/src/ERP/AP/ManageTransmissionConfigurations.py",
    FORMATS: "/src/ERP/AP/ManageFormats.py",
    PAYMENT_SYSTEM: "/src/ERP/AP/ManagePaymentSystems.py",
    PAYMENT_PROCESS_PROFILES: "/src/ERP/AP/PaymentProcess Profiles.py",
    DISBURSEMENT_SYSTEM_OPTIONS: "/src/ERP/AP/ManageDisbursementSystemOptions.py",
    DISTRIBUTION_SETS: "/src/ERP/AP/ManageDistributionSets.py",
    SPECIFY_SUPPLIER_NUMBERING: "/src/ERP/AP/SpecifySupplierNumbering.py",
    AGING_PERIODS: "/src/ERP/AP/ManageAgingPeriods.py",

    # AR

    RECEIVABLES_SYS_OPT: "/src/ERP/AR/ManageReceivablesSystemOption.py",
    RECEIVABLES_ACTIVITY: "/src/ERP/AR/ManageReceivablesActivities.py",
    TRANS_TYPES: "/src/ERP/AR/ManageTransactionTypes.py",
    TRANS_SOURCE: "/src/ERP/AR/ManageTransactionSource.py",
    STAN_MEMO_LINES: "/src/ERP/AR/ManageStandardMemoLines.py",
    AUTO_ACC_RULE: "/src/ERP/AR/ManageAutoAccountingRules.py",
    PYMNT_TERMS: "/src/ERP/AR/ManageReceivablesPaymentTerms.py",
    REMIT_TO_ADDRESSES: "/src/ERP/AR/ManageRemittoAddresses.py",
    APPROVAL_LIMITS: "/src/ERP/AR/ManageApprovalLimits.py",
    STATEMENT_CYCLE: "/src/ERP/AR/ManageStatementCycles.py",
    RECEIVABLES_DSTRBTN: "/src/ERP/AR/ManageReceivablesDistributionSet.py",
    AR_DFF_VALUES: "/src/ERP/AR/ManageDescriptiveFlexfieldValues.py",
    RECEIVABLE_DFF: "/src/ERP/AR/ManageReceivablesDescriptiveFlexfield.py",
    RECEIPT_CLASSES_AND_METHODS: "/src/ERP/AR/ManageReceiptClassesandMethods.py",
    RECEIPT_SOURCE: "/src/ERP/AR/ManageReceiptSources.py",
    AUTOCASH_RULE_SET: "/src/ERP/AR/ManageAutoCashRuleSets .py",
    AUTOMATCH_RULE_SET: "/src/ERP/AR/ManageAutoMatchRuleSet.py",
    APP_EXCEPTION_RULES: "/src/ERP/AR/ManageApplicationExceptionRules.py",
    REVENUE_SCHDLNG_RULES: "/src/ERP/AR/ManageRevenueSchedulingRules.py",
    REVENUE_CONTINGENCIES: "/src/ERP/AR/ManageRevenueContingencies.py",
    RECEIVABLE_CUSTOMER_PROF: "/src/ERP/AR/ManageReceivablesCustomerProfileClasses.py",
    TRADING_COMMUNITY_SOURCE: "/src/ERP/AR/Managetradingcommunitysource.py",
    RECEIVABLES_DOC_SEQ: "/src/ERP/AR/ManageReceivablesDocumentSequences.py",
    AR_AGING_METHODS: "/src/ERP/AR/ManageAgingMethods.py",

    # Expenses
    EXP_FIELDS_BY_CATEGORY: "/src/ERP/Expenses/ManageExpenseFieldsByCategory.py",
    TAX_FIELDS: "/src/ERP/Expenses/ManageTaxFields.py",
    EXP_SYS_OPTIONS: "/src/ERP/Expenses/ManageExpensesSystemOptions.py",
    ACCM_EXP_POLICY: "/src/ERP/Expenses/ManageAccommodationsPolicy.py",
    ENTERTAINMENT_POLICY: "/src/ERP/Expenses/ManageEntertainmentPolicy.py",
    MEALS_EXP_POLICY: "/src/ERP/Expenses/ManageMealsPolicy.py",
    MILEAGE_POLICY: "/src/ERP/Expenses/ManageMileagePolicy.py",
    MISC_EXP_POLICY: "/src/ERP/Expenses/ManageMiscellaneousPolicy.py",
    CASH_ADVN_POLICY: "/src/ERP/Expenses/ManageCashAdvancePolicies.py",
    RECEIPT_NOTIFI_RULE: "/src/ERP/Expenses/ManageExpenseReportReceiptAndNotificationRules.py",
    CONV_RATES_POLICY: "/src/ERP/Expenses/ManageConversionRatesAndPolicies.py",
    EXP_PROFILE_VALUES: "/src/ERP/Expenses/ManageExpenseProfileValue.py",
    EXP_PAYMENT_METHOD_DEFAULTING_RULE: "/src/ERP/Expenses/ManagePaymentMethodDefaultingRules.py",
    AUDIT_SELC_RULE: "/src/ERP/Expenses/ManageExpenseReportAuditSelectionRules.py",
    EXP_DFF_VALUES: "/src/ERP/Expenses/ManageExpenseDFFValues.py",
    EXP_DFF: "/src/ERP/Expenses/ManageExpnsDescriptiveFlexfields.py",
    EXP_TEMP: "/src/ERP/Expenses/ManageExpenseReportTemplates.py",
    AUDIT_RULES_BY_EXP_TYPE: "/src/ERP/Expenses/ManageExpenseReportAuditRulesByExpenseTemplatesAndTypes.py",
    AUDIT_RECEIPT_RULE: "/src/ERP/Expenses/ManageExpenseAuditandReceiptRuleAssignments.py",

    # CM
    BANKS: "/src/ERP/CM/ManageBanks.py",
    BANK_BRANCHES: "/src/ERP/CM/ManageBankBranches.py",
    BANK_ACCOUNT: "/src/ERP/CM/ManageCMBankAccounts.py",
    BANK_STMT_TRNSCTN_CODE: "/src/ERP/CM/ManageBankStatementTransactionCodes.py",
    PARSE_RULE_SETS: "/src/ERP/CM/ManageParseRuleSets.py",
    CASH_TRANS_TYPE_MAPPING: "/src/ERP/CM/CashTransactionTypeMapping .py",
    BANK_STATEMENT_REC_TOLERANCE_RULE: "/src/ERP/CM/ManageReconciliationToleranceRules.py",
    BANK_STATEMENT_REC_MATCHING_RULE: "/src/ERP/CM/ManageBankStatementReconciliationMatchingRules.py",
    REC_RULE_SETS: "/src/ERP/CM/BankStatementReconciliationRuleSets.py",

    # FA
    MANAGE_FA_KEYFF_VALUESETS: "/src/ERP/FA/ManageFixedAssetsFlexfieldvaluesets.py",
    MANAGE_ASSET_KEYS: "/src/ERP/FA/ManageAssetKeys.py",
    MANAGE_ASSET_LOCATION: "/src/ERP/FA/ManageAssetLocations.py",
    MANGE_FISCAL_YEAR: "/src/ERP/FA/ManageFiscalYear.py",
    MANAGE_ASSET_CALENDARS: "/src/ERP/FA/ManageAssetCalendars.py",
    MANGE_PRORATE_CONV: "/src/ERP/FA/ManageProrateConventions.py",
    MANAGE_ASSET_BOOK: "/src/ERP/FA/ManageAssetBooks.py",
    MANAGE_ASSET_CATEGORIES: "/src/ERP/FA/ManageAssetCategories.py",
    MANAGE_DFF_VALUES: "/src/ERP/FA/ManageAssetDFFValues.py",
    MANAGE_DFF: "/src/ERP/FA/ManageAssetDescriptiveFlexfield.py",
    MANAGE_CATEGORY_ALIASES: "/src/ERP/FA/ManageAssetCategoryAliases.py",
    MANAGE_ASSETKEY_ALIASES: "/src/ERP/FA/ManageAssetKeyAliases.py",
    MANAGE_LOCATION_ALIASES: "/src/ERP/FA/ManageAssetLocationAliases.py",
    MANAGE_BONUS_RULE: "/src/ERP/FA/ManageBonusRules.py",
    MANAGE_DEPRECIATION_CEILING: "/src/ERP/FA/ManageCeilings.py",

    # PPM - Projects Organization
    PRJ_UNIT_ORG: "/src/ERP/PPM/ORG_ManageProjectUnitOrganizations.py",
    PRJ_UNIT_OPTS: "/src/ERP/PPM/ORG_ManageProjectUnitOptions.py",
    PRJ_UNIT_SETS_ASSIGNMTS: "/src/ERP/PPM/ORG_ManageProjectUnitSetAssignments.py",
    PRJ_ORG_CLASSIFICATIONS: "/src/ERP/PPM/ORG_ManageProjectOrganizationClassifications.py",
    PRJ_ACC_BU_FN: "/src/ERP/PPM/ORG_ ProjectAccountingBusinessfunction.py",

    # PPM - Foundation and Costing
    REV_CAT: "/src/ERP/PPM/CreateRevenueCategory.py",
    EXP_CAT: "/src/ERP/PPM/CreateExpenditureCategories.py",
    EXP_TYP: "/src/ERP/PPM/CreateExpenditureTypes.py",
    SER_TYP: "/src/ERP/PPM/CreateServiceTypes.py",
    PRJ_STS: "/src/ERP/PPM/CreateProjectStatuses.py",
    PRJ_TYPS: "/src/ERP/PPM/CreateProjectTypes.py",
    BRDN_CST_BS_TYP: "/src/ERP/PPM/CreateBurdenCostBaseTypes.py",
    BRDN_CST_BSS: "/src/ERP/PPM/CreateBurdenCostBases.py",
    BRDN_CST_CDS: "/src/ERP/PPM/CreateBurdenCostCodes.py",
    PRJCT_TRANS_SOURCES: "/src/ERP/PPM/ManageProjectTransactionSources.py",
    BRDN_SCHDL: "/src/ERP/PPM/ManageBurdenSchedule.py",
    # PRJCT_TRANS_SOURCES: "/src/ERP/PPM/ManageProjectTransactionSources.py",
    # BRDN_SCHDL: "/src/ERP/PPM/ManageBurdenSchedule.py",
    # PRJCT_TRANS_SOURCES: "/src/ERP/PPM/ManageProjectTransactionSources.py",
    # BRDN_SCHDL: "/src/ERP/PPM/ManageBurdenSchedule.py",



    # PPM - Grants
    RESOURCES: "/src/ERP/PPM/Grants_ManageResources.py",
    VALUE_SETS: "/src/ERP/PPM/Grants_ValueSets.py",
    GRANTS_DFF: "/src/ERP/PPM/Grants_CreateGrantsDescriptiveFlexfield.py",
    AUDIT_TYPES: "/src/ERP/PPM/Grants_ManageAuditTypes.py",
    AWARD_PURPOSE_CODES: "/src/ERP/PPM/Grants_ManageAwardPurposeCodes.py",
    AWARD_TYPES: "/src/ERP/PPM/Grants_ManageAwardTypes.py",
    INS_CONTACT_OFFICIAL: "/src/ERP/PPM/Grants_ManageInstitutionContactOfficialTypes.py",
    KEYWORDS: "/src/ERP/PPM/Grants_ManageKeywords.py",
    GRANTS_REF_TYPES: "/src/ERP/PPM/Grants_ManageGrantsReferenceTypes.py",
    ASSIST_LISTING_NUMBER: "/src/ERP/PPM/Grants_ManageAssistanceListingNumbers.py",
    GRANTS_PERSONNEL: "/src/ERP/PPM/Grants_ManageGrantsPersonnel.py",
    SPONSORS: "/src/ERP/PPM/Grants_CreateSponsors.py",
    FUND_SOURCES: "/src/ERP/PPM/Grants_ManageFundingSources.py",
    INSTITUTIONS: "/src/ERP/PPM/Grants_ManageInstitutions.py",
    AWARD_TEMPLATES: "/src/ERP/PPM/Grants_CreateAwardTemplate.py",

    # PPM - Billing
    CONTRACT_TYPES: "/src/ERP/PPM/Billing_ManageContractTypes.py",
    SPCFY_CSTMR_CNTRCT_MNGMNT_BSNSS_FNCTN_PRPRTS: "/src/ERP/PPM/Billing_SpecifyCustomerContractManagementBusinessFunctionProperties.py",
    EVENT_TYPES: "/src/ERP/PPM/Billing_ManageEventTypes.py",
    INV_FORMATS: "/src/ERP/PPM/Billing_ManageInvoiceFormats.py",

    # Global HR
    ENTERPRISE: "/src/HCM/GHR/EnterpriseHCMInformation.py",
    LDG: "/src/HCM/GHR/ManageLegislativeDataGroup.py",
    BUSINESS_UNIT: "/src/HCM/GHR/CreateBusinessUnit.py",
    REFERENCE_DATA_SET: "/src/HCM/GHR/ManageReferenceDataSets.py",
    MANAGE_EFF: "/src/HCM/GHR/ManageEFF.py",
    MANAGE_ADDRESS_FORMATS: "/src/HCM/GHR/ManageAddressFormats.py",
    ASSGN_LOOKUPS_SHEET: "/src/HCM/GHR/.py",
    MANAGE_ASSGN_STATUS: "/src/HCM/GHR/ManageAssignmentStatus.py",
    BARGAINING_UNIT: "/src/HCM/GHR/ManageBargainingUnit.py",
    SALARY_BASIS: "/src/HCM/GHR/DefineSalaryBasis.py",
    MANAGE_DOCUMENT_TYPE: "/src/HCM/GHR/ManageDocumentTypes.py",
    SENIORITY_DATE_RULES: "/src/HCM/GHR/ManageSeniorityDateRules.py",
    LEGAL_ENTITY_HCM_INFORMATION: "/src/HCM/GHR/LegalEntityHCMInformation.py",
    MANAGE_COMMON_LOOKUP: "/src/HCM/GHR/DefineCommonLookups.py",
    MANAGE_VALUE_SETS: "/src/HCM/GHR/DefineValueSetsandValues.py",
    HR_LEGAL_REPORTING_UNIT: "/src/HCM/GHR/Create Legal Reporting Unit.py",
    MANAGE_PRSN_FORMATS: "/src/HCM/GHR/ManagePersonNameFormats.py",
    MANAGE_PRSN_NM_STYL: "/src/HCM/GHR/ManagePersonNameStyles.py",
    MANAGE_HR_DFF: "/src/HCM/GHR/ManageDFF.py",
    MANAGE_JOURNY_CONFIG: "/src/HCM/GHR/ManageJourneyConfiguration.py",
    MANAGE_KFF: "/src/HCM/GHR/ManageKFF.py",
    LEGAL_ADDRESS: "/src/HCM/GHR/CreateLegalAddress.py",

    # Benefits
    BENEFIT_RELATIONSHIP: "/src/HCM/Benefits/Configure Default Benefit Relationship.py",
    PROGRAM_PLANYEARS: "/src/HCM/Benefits/Year Periods and Billing Calendars.py",
    PLAN_TYPES: "/src/HCM/Benefits/Plan Types.py",
    BENEFIT_OPTIONS: "/src/HCM/Benefits/Benefit Options.py",
    CONFIG_PLANTYPE_GROUPING_DISPLAY: "/src/HCM/Benefits/Configure Plan Type Grouping Display.py",
    BASIC_PLAN_DETAILS: "/src/HCM/Benefits/Benefit Plan - Basic Details.py",
    BASIC_PROGRAM_DETAILS: "/src/HCM/Benefits/Benefit Program - Basic Details.py",
    BENEFIT_PROGRAM_ENROLLMENT: "/src/HCM/Benefits/Benefit Program - Enrollment.py",
    BENEFIT_PRGM_CERT_UPLOAD: "/src/HCM/Benefits/BenefitPlan_Certifications.py",
    BENEFIT_PROGRAM_DESIGNATION: "/src/HCM/Benefits/Benefit Program - Designations.py",
    LIFEEVENTS_DATACHANGES: "/src/HCM/Benefits/BenefitLifeEvents_DataChanges.py",
    USR_DEF_CRITERIA: "/src/HCM/Benefits/UserDefinedCriteria.py",
    LIFEEVENTS: "/src/HCM/Benefits/BenefitLifeEvents_LifeEvents.py",
    VARIABLE_COVERAGE: "/src/HCM/Benefits/BenefitCoverage_VariableCoverages.py",
    BENEFIT_COVERAGE: "/src/HCM/Benefits/BenefitCoverage_Coverages.py",
    VARIABLE_RATE: "/src/HCM/Benefits/BenefitRates_VariableRates.py",
    BENEFIT_RATES: "/src/HCM/Benefits/BenefitRates_StandardRates.py",
    BENEFIT_GROUP: "/src/HCM/Benefits/Benefit_Groups.py",
    BENEFIT_BALANCES: "/src/HCM/Benefits/CreateBenefitBalances.py",
    DERIVEDFACTORS_AGE: "/src/HCM/Benefits/DerivedFactors_Age.py",
    DERIVEDFACTORS_LOS: "/src/HCM/Benefits/DerivedFactors_LengthOfService.py",
    DERIVEDFACTORS_AGEANDSERVICE: "/src/HCM/Benefits/DerivedFactors_Age&Service.py",
    DERIVEDFACTORS_COMPENSATION: "/src/HCM/Benefits/DerivedFactors_Compensation.py",
    DERIVEDFACTORS_HOURSWORKED: "/src/HCM/Benefits/DerivedFactor_HoursWorked.py",
    DERIVEDFACTORS_FTE: "/src/HCM/Benefits/DerivedFactors_FullTimeEquivalent.py",
    BENEFIT_PRGM_DOC_UPLOAD: "/src/HCM/Benefits/BenefitProgram_DocumentUpload.py",
    SELF_SER_CONFIG: "/src/HCM/Benefits/SelfServiceConfiguration.py",
    ENROLL_AUTH: "/src/HCM/Benefits/EnrollmentAuthorization.py",

    # Payroll
    STANDARD_EARNINGS: "/src/HCM/Payroll/CreateStandardEarningElements.py",
    TIME_LABOUR: "/src/HCM/Payroll/CreateTimeandLabourElements.py",
    ABSENCE_ELEMENTS: "/src/HCM/Payroll/CreateAbsenceElements.py",
    IMPUTED_EARNINGS: "/src/HCM/Payroll/CreateImputedEarningElements.py",
    SUPPLEMENTAL_EARNINGS: "/src/HCM/Payroll/CreateSupplementalEarningElements.py",
    VOLUNTRY_DEDUCTIONS: "/src/HCM/Payroll/CreateVoluntaryDeductions.py",
    PRETAX_DEDUCTIONS: "/src/HCM/Payroll/CreatePretaxElements.py",
    PRETAX_401K_DEDUCTIONS: "/src/HCM/Payroll/CreatePretaxDeferred401KElements.py",
    PRETAX_403B_457_DEDUCTIONS: "/src/HCM/Payroll/CreatePretaxDeffered403b_457_Elements.py",
    MANAGE_LEGAL_ENTITY_REGISTRATION: "/src/HCM/Payroll/Legal Entity Registrations.py",
    LEGAL_ENTITY_CALCULATION_FEDERA: "/src/HCM/Payroll/Legal Entity Calculation Cards - Federal.py",
    LEGAL_ENTITY_CALCULATION_REGION: "/src/HCM/Payroll/Legal Entity Calculations Card Setup - Regional.py",
    LEGAL_REPORTING_REGISTRATION: "/src/HCM/Payroll/CreateLegalReportingUnitRegistrations.py",
    LEGAL_RPT_CALCULATION_FEDERAL: "/src/HCM/Payroll/LRU Calculations Card Setup - Federal.py",
    LEGAL_RPT_CALCULATION_REGION: "/src/HCM/Payroll/LRU Calculations Card Setup - Regional.py",
    MANAGE_BANK: "/src/HCM/Payroll/Define Organization Bank.py",
    MANAGE_BANK_BRANCHES: "/src/HCM/Payroll/Define Organization Bank Branch.py",
    MANAGE_BANK_ACCOUNTS: "/src/HCM/Payroll/Define Organization Bank Account.py",
    ORGANIZATION_PAYMENT_METHODS: "/src/HCM/Payroll/Organizational Payment Methods.py",
    CREATE_PAYMENT_SOURCE: "/src/HCM/Payroll/Create Payment Source.py",
    PAYROLL_DEFINITIONS: "/src/HCM/Payroll/PayrollDefinitions.py",
    THIRD_PARTY_ORG: "/src/HCM/Payroll/Third Party Org.py",
    EMPLOYER_LIABILITY: "/src/HCM/Payroll/CreateEmployerLiabilityConfigurations.py",
    NONPAYROLL_ELEMENTS: "/src/HCM/Payroll/CreateNonPaymentElementConfigurations.py",
    DST_OBJ_GRP_DED: "/src/HCM/Payroll/Create_Object_group_Deduction.py",
    DST_OBJ_GRP_ELE: "/src/HCM/Payroll/Create_Object_groups_elements.py",
    DST_OBJ_GRP_PAY_R: "/src/HCM/Payroll/Create_Object_groups_payroll_relationship.py",
    DST_OBJ_GRP_PRO_I: "/src/HCM/Payroll/Create_object_groups_process_information.py",
    DST_OBJ_GRP_WRK_REL: "/src/HCM/Payroll/Create_Object_group_Work_Relationship.py",
    MANAGE_STRUCTURE: "/src/HCM/Payroll/CostAllocationFlexFields_ManageStructure.py",
    MANAGE_STRUCTURE_INST: "/src/HCM/Payroll/CostAllocationFlexFields_ManageStructureInstances.py",
    # DFRD_BLNCE : "/src/HCM/Payroll/DS TEMPLATE - DEFERRED BALANCE",
    DFRD_CSTM_BLNCE: "/src/HCM/Payroll/CreateCustomDeferredBalance.py",
    CSTM_DMSN: "/src/HCM/Payroll/CreateCustomDimension.py",
    CSTM_BLNC_FDS: "/src/HCM/Payroll/CreateDeferredBalanceFeeds.py",
    MAN_ACC_RULES: "/src/HCM/Payroll/SLA_Manage_Account_Rules.py",
    MAN_SBLDGR_JRNL_ENT: "/src/HCM/Payroll/SLA_Subledger_Journal_Entry_Rule_Sets.py",
    MAN_ACC_MTHDS: "/src/HCM/Payroll/SLA_Manage_Accounting_Methods.py",

    # Absence
    ABSENCE_REASONS: "/src/HCM/Absence/CreateAbsenceReasons.py",
    ABSENCE_CATEGORIES: "/src/HCM/Absence/CreateAbsence_Categories.py",
    ABSENCE_TYPES: "/src/HCM/Absence/CreateAbsence_Types.py",
    ABSENCE_PLANS_ACCRUAL: "/src/HCM/Absence/AbsencePlans-Accrual.py",
    RATE_DEFINITION: "/src/HCM/Absence/CreateRateDefinition.py",
    ABSENCE_CERTIFICATIONS: "/src/HCM/Absence/CreateAbsenceCertifications.py",
    ABSENCE_PLAN_QUALIFICATION: "/src/HCM/Absence/CreateAbsencePlanQualification.py",
    ABSENCE_PLANS_NO_ENTITLEMENT: "/src/HCM/Absence/AbsencePlans-NoEntitlement.py",

    # Time and Labor
    REPEATING_TIME_PERIOD: "/src/HCM/TimeandLabor/Create_Repeating_Time_Periods.py",
    TIME_CONSUMER_SETS: "/src/HCM/TimeandLabor/Create_Time_Consumer_Sets.py",
    TIME_CATEGORIES: "/src/HCM/TimeandLabor/Create_Time_Categories.py",
    SINGLE_ATTRIBUTE_COMPONENTS: "/src/HCM/TimeandLabor/ManageTimeEntryLayoutComp_SingleAttributeComponent.py",
    MULTIPLE_ATTRIBUTE_COMPONENT: "/src/HCM/TimeandLabor/Create_MultipleAttributeComponent.py",
    TIME_REPOSITORY_TEMP_TIME_ENT: "/src/HCM/TimeandLabor/ManageTimeRepositoryRuleTemplates_TimeEntryRule.py",
    MESSAGES: "/src/HCM/TimeandLabor/ManageMessages.py",
    HCM_GROUPS: "/src/HCM/TimeandLabor/HCMGroups.py",
    TIME_RULE_SETS: "/src/HCM/TimeandLabor/Manage Time Repository Rule Sets.py",


    # Talent- Career Development
    CAREER_DEV : "/src/HCM/Talent-Management/Create_CareerDevelopment.py",

    # Talent - Learnings
    LEARNING_CONTENT : "/src/HCM/Talent-Learnings/Create_LearningContent.py",
    CLASSROOM : "/src/HCM/Talent-Learnings/Create_Classrooms.py",
    LA_COURSE : "/src/HCM/Talent-Learnings/CreateandConfigureCourses.py",
    INST_LED_ACTIVITY : "/src/HCM/Talent-Learnings/Create_InstructorLedActivity.py",
    SELF_PACED_ACT : "/src/HCM/Talent-Learnings/Create_SelfPacedActivity.py",
    LEARNING_OFFERINGS : "Baseline/src/HCM/Talent-Learnings/Create_ConfigureOfferings.py",
    LA_QUESTIONS : "/src/HCM/Talent-Learnings/Create_Questions_LA.py",
    LA_QUESTIONNARIE_TEMP : "/src/HCM/Talent-Learnings/CreateQuestionnarieTemplate_LA.py",
    LA_QUESTIONNARIE : "/src/HCM/Talent-Learnings/CreateQuestionnarie_LA.py",
    LE_QUESTIONS : "/src/HCM/Talent-Learnings/Create_LearningEvaluationQuestions.py",
    LE_QUES_TEMPLATE : "/src/HCM/Talent-Learnings/Create_LearningEvaluationQT.py",
    LE_QUESTIONNARIE : "/src/HCM/Talent-Learnings/Create_LearningEvaluationQuestionnarie.py",
    OLC_QUESTIONS : "/src/HCM/Talent-Learnings/Create_OnlineCourseQuestions_LE.py",
    OLC_QUES_TEMPLATE : "/src/HCM/Talent-Learnings/Create_OnlineCourseQuestionnarieTemplate_LE.py",
    OLC_QUESTIONNARIE : "/src/HCM/Talent-Learnings/Create_OnlineCourseQuestionnarie_LE.py",


    #Talent - Goals
    GOAL_LIBRARY : "/src/HCM/Talent-Goal/Goal Library.py",
    GOAL_PLAN : "/src/HCM/Talent-Goal/Goal_Plan.py",

    # Talent - Performance
    RATING_MODEL_SHEET_NAME : "/src/HCM/Talent/HCM_Talent_Rating_Model.py",
    QUESTIONS : "/src/HCM/Talent-Performance/Create_Questions.py",
    REVIEW_PERIOD : "/src/HCM/Talent-Performance/Create_ReviewPeriods.py",
    PERFORMANCE_DOCUMENT_TYPE : "/src/HCM/Talent-Performance/Create_PerformanceDocumentType.py",
    CHECK_IN_TEMPLATE : "/src/HCM/Talent-Performance/Create_CheckInTemplate.py",
    FEEDBACK_TEMPLATE : "/src/HCM/Talent-Performance/Create_FeedbackTemplate.py",
    PERFORMANCE_ROLE : "/src/HCM/Talent-Performance/Create_Performance Roles.py",
    QUES_TEMPLATES : "/src/HCM/Talent-Performance/Create_QuestionarieTemplate.py",
    QUESTIONNARIE : "/src/HCM/Talent-Performance/Create_Questionnarie.py",
    PERFORMANCE_PROCESS_FLOW : "/src/HCM/Talent-Performance/Create_Performance Process Flow.py",
    PERFORMANCE_TEMPLATE_SECTION : "/src/HCM/Talent-Performance/Create_PerformanceTemplateSection.py",
    PERFORMANCE_TEMPLATE : "/src/HCM/Talent-Performance/Create_PerformanceTemplate.py",

    # Talent - ORC
    RECRUITING_MANAGEMENT : "/src/HCM/Talent-Recruiting/Recruiting_Management.py",
    SOURCES : "/src/HCM/Talent-Recruiting/Create_Sources.py",
    QUESTION_LIBRARY : "/src/HCM/Talent-Recruiting/Question_Library.py",
    QUESTIONNAIRE_TEMPLATE : "/src/HCM/Talent-Recruiting/Questionnaire Template.py",
    QUESTIONNAIRE_REC : "/src/HCM/Talent-Recruiting/Questionnaire.py",

    # Talent - OnBoarding
    CHECKLIST_STEP : "/src/HCM/Talent-Onboarding/Create_ChecklistStep.py",
    CHECKLIST_PROCESS : "/src/HCM/Talent-Onboarding/Create_ChecklistProcess.py",
    CHECKLIST_TASK : "/src/HCM/Talent-Onboarding/Create_ChecklistTask.py",



    # Health and Safety
    HandS_DFF :"/src/HCM/HealthAndSafety/ManageHealthandSafety-DescriptiveFlexfield.py",
    #OFFERINGS  :" ",
    QUESTIONS_HNS  :"/src/HCM/HealthAndSafety/HNS_Question_Library.py ",
    QUESTIONNAIRES_TEMPLATES:"/src/HCM/HealthAndSafety/HNS_QUESTIONNAIRES_TEMPLATES.py ",
    QUESTIONNAIRES_HNS :"/src/HCM/HealthAndSafety/HNS_QUESTIONNAIRES.py ",
    TARGET_DATE :"/src/HCM/HealthAndSafety/Create_TargetDates.py ",
    ENABLE_DELIVERED_ALERTS  :"/src/HCM/HealthAndSafety/Create_EnableDeliveredAlerts.py ",
    INCIDENT_EVENTS_LOOKUPS:"/src/HCM/HealthAndSafety/Create_IncidentEventsLookups.py ",

    # Security
    SEG_ROLE_OBJ_GRP : "/src/Security/Segment Roles.py",


    }
