ADMIN_COMMANDS_SETTINGS_NAME = "ADMIN_COMMANDS"
"""Expected setting name for enabling/disabling commands in the admin panel"""
ADMIN_COMMANDS_SETTINGS_HINT = "The setting should be a dict with keys as strings with the app names and the mapped values should be either the string literal '__all__' to show all commands for the app or an iterable of strings with the command names to show."
"""Hint for expected setting values"""
APP_NAME = "django_admin_commander"
"""Default app name"""
PERMISSION_NAME = "run_management_command"
"""Default permission name for running commands"""
