# coding: utf-8

"""
    aind-sharepoint-service

     ## aind-sharepoint-service  Service to pull data from Sharepoint.  

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class LASWhereToObtainSubstanceRo(str, Enum):
    """
    Enum class for LASWhereToObtainSubstanceRo
    """

    """
    allowed enum values
    """
    LAS_BLUE_BIN_IN_VIVARIUM = 'LAS blue bin in Vivarium -80 freezer(1st shelf)'
    OTHER_TYPE_IN = 'Other (Type in)'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of LASWhereToObtainSubstanceRo from a JSON string"""
        return cls(json.loads(json_str))


