import sys
from ctypes import *
from spire.xls.common import *
from spire.xls.common import dlllib
from spire.xls.common import dlllibXls

from spire.xls.common.Common import IntPtrArray
from spire.xls.common.Common import IntPtrWithTypeName
from spire.xls.common.Common import GetObjVectorFromArray
from spire.xls.common.Common import GetStrVectorFromArray
from spire.xls.common.Common import GetVectorFromArray
from spire.xls.common.Common import GetIntPtrArray
from spire.xls.common.Common import GetByteArray
from spire.xls.common.Common import GetIntValue
from spire.xls.common.Common import GetObjIntPtr
from spire.xls.common.Common import PtrToStr

from spire.xls.common.SpireObject import SpireObject
from spire.xls.common.CultureInfo import CultureInfo
from spire.xls.common.Boolean import Boolean
from spire.xls.common.Byte import Byte
from spire.xls.common.Char import Char
from spire.xls.common.Int16 import Int16
from spire.xls.common.Int32 import Int32
from spire.xls.common.Int64 import Int64
from spire.xls.common.PixelFormat import PixelFormat
from spire.xls.common.Size import Size
from spire.xls.common.SizeF import SizeF
from spire.xls.common.Point import Point
from spire.xls.common.PointF import PointF
from spire.xls.common.Rectangle import Rectangle
from spire.xls.common.RectangleF import RectangleF
from spire.xls.common.Single import Single
from spire.xls.common.TimeSpan import TimeSpan
from spire.xls.common.UInt16 import UInt16
from spire.xls.common.UInt32 import UInt32
from spire.xls.common.UInt64 import UInt64
from spire.xls.common.Stream import Stream
from spire.xls.common.License import License
from spire.xls.common.Color import Color
from spire.xls.common.DateTime import DateTime
from spire.xls.common.Double import Double
from spire.xls.common.EmfType import EmfType
from spire.xls.common.Encoding import Encoding
from spire.xls.common.FontStyle import FontStyle
from spire.xls.common.GraphicsUnit import GraphicsUnit
from spire.xls.common.ICollection import ICollection
from spire.xls.common.IDictionary import IDictionary
from spire.xls.common.IEnumerable import IEnumerable
from spire.xls.common.IEnumerator import IEnumerator
from spire.xls.common.IList import IList
from spire.xls.common.String import String



from spire.xls.enums.AlertStyleType import AlertStyleType
from spire.xls.enums.AutoFormatOptions import AutoFormatOptions
from spire.xls.enums.AutoFormatType import AutoFormatType
from spire.xls.enums.AverageType import AverageType
from spire.xls.enums.AxisLineIdentifierType import AxisLineIdentifierType
from spire.xls.enums.AxisTextDirectionType import AxisTextDirectionType
from spire.xls.enums.AxisType import AxisType
from spire.xls.enums.AxisTypes import AxisTypes
from spire.xls.enums.BaseFormatType import BaseFormatType
from spire.xls.enums.BordersLineType import BordersLineType
from spire.xls.enums.BubbleSizeType import BubbleSizeType
from spire.xls.enums.BuiltInPropertyType import BuiltInPropertyType
from spire.xls.enums.BuiltInStyles import BuiltInStyles
from spire.xls.enums.CategoryType import CategoryType
from spire.xls.enums.CellDataType import CellDataType
from spire.xls.enums.CellFormatType import CellFormatType
from spire.xls.charts.ChartBackgroundMode import ChartBackgroundMode
from spire.xls.enums.ChartBaseUnitType import ChartBaseUnitType
from spire.xls.enums.ChartDisplayUnitType import ChartDisplayUnitType
from spire.xls.enums.ChartLinePatternType import ChartLinePatternType
from spire.xls.enums.ChartLineWeightType import ChartLineWeightType
from spire.xls.enums.ChartMarkerType import ChartMarkerType
from spire.xls.enums.ChartParagraphType import ChartParagraphType
from spire.xls.enums.ChartPieType import ChartPieType
from spire.xls.enums.ChartPlotEmptyType import ChartPlotEmptyType
from spire.xls.enums.CheckState import CheckState
from spire.xls.enums.ColorType import ColorType
from spire.xls.enums.CommentHAlignType import CommentHAlignType
from spire.xls.enums.CommentVAlignType import CommentVAlignType
from spire.xls.enums.ComparisonOperatorType import ComparisonOperatorType
from spire.xls.enums.CompoundLineType import CompoundLineType
from spire.xls.conditional_formatting.ConditionalFormatScope import ConditionalFormatScope
from spire.xls.enums.ConditionalFormatType import ConditionalFormatType
from spire.xls.enums.ConditionalTopNType import ConditionalTopNType
from spire.xls.conditional_formatting.ConditionValuePosition import ConditionValuePosition
from spire.xls.enums.ConditionValueType import ConditionValueType
from spire.xls.enums.ConnectionDataSourceType import ConnectionDataSourceType
from spire.xls.enums.CopyRangeOptions import CopyRangeOptions
from spire.xls.enums.DataBarAxisPosition import DataBarAxisPosition
from spire.xls.enums.DataBarBorderType import DataBarBorderType
from spire.xls.enums.DataBarFillType import DataBarFillType
from spire.xls.enums.DataBarNegativeColorType import DataBarNegativeColorType
from spire.xls.enums.DataLabelPositionType import DataLabelPositionType
from spire.xls.enums.DataMarkerDirection import DataMarkerDirection
from spire.xls.enums.DataSourceType import DataSourceType
from spire.xls.enums.DateTimeGroupingType import DateTimeGroupingType
from spire.xls.enums.DeleteOption import DeleteOption
from spire.xls.enums.DropLineStyleType import DropLineStyleType
from spire.xls.DVAspect import DVAspect
from spire.xls.enums.DynamicFilterType import DynamicFilterType
from spire.xls.enums.ErrorBarIncludeType import ErrorBarIncludeType
from spire.xls.enums.ErrorBarType import ErrorBarType
from spire.xls.Excel2016Charttype import Excel2016Charttype
from spire.xls.enums.ExcelCalculationMode import ExcelCalculationMode
from spire.xls.enums.ExcelChartType import ExcelChartType
from spire.xls.enums.ExcelClearOptions import ExcelClearOptions
from spire.xls.enums.ExcelColors import ExcelColors
from spire.xls.enums.ExcelComboType import ExcelComboType
from spire.xls.enums.ExcelFindOptions import ExcelFindOptions
from spire.xls.enums.ExcelHorizontalAlignment import ExcelHorizontalAlignment
from spire.xls.enums.ExcelPatternType import ExcelPatternType
from spire.xls.enums.ExcelQuartileCalculation import ExcelQuartileCalculation
from spire.xls.enums.ExcelSaveType import ExcelSaveType
from spire.xls.enums.ExcelShapeType import ExcelShapeType
from spire.xls.enums.ExcelSheetType import ExcelSheetType
from spire.xls.enums.ExcelTotalsCalculation import ExcelTotalsCalculation
from spire.xls.enums.ExcelTreeMapLabelOption import ExcelTreeMapLabelOption
from spire.xls.enums.ExcelVersion import ExcelVersion
from spire.xls.enums.ExcelVerticalAlignment import ExcelVerticalAlignment
from spire.xls.enums.ExpandCollapseFlags import ExpandCollapseFlags
from spire.xls.FileFormat import FileFormat
from spire.xls.enums.FillPictureType import FillPictureType
from spire.xls.enums.FilterConditionType import FilterConditionType
from spire.xls.enums.FilterDataType import FilterDataType
from spire.xls.enums.FilterOperatorType import FilterOperatorType
from spire.xls.enums.FilterType import FilterType
from spire.xls.enums.FindType import FindType
from spire.xls.Font import Font
from spire.xls.enums.FontUnderlineType import FontUnderlineType
from spire.xls.enums.FontVertialAlignmentType import FontVertialAlignmentType
from spire.xls.enums.GeomertyAdjustValueFormulaType import GeomertyAdjustValueFormulaType
from spire.xls.GetText import GetText
from spire.xls.enums.GradientColorType import GradientColorType
from spire.xls.enums.GradientPatternType import GradientPatternType
from spire.xls.enums.GradientPresetType import GradientPresetType
from spire.xls.enums.GradientStyleType import GradientStyleType
from spire.xls.enums.GradientTextureType import GradientTextureType
from spire.xls.GradientType import GradientType
from spire.xls.enums.GradientVariantsType import GradientVariantsType
from spire.xls.enums.GroupByType import GroupByType

from spire.xls.GoalSeekResult import GoalSeekResult
from spire.xls.GoalSeek import GoalSeek
from spire.xls.enums.HorizontalAlignType import HorizontalAlignType
from spire.xls.enums.HttpContentType import HttpContentType
from spire.xls.enums.HyperLinkType import HyperLinkType
from spire.xls.enums.IconSetType import IconSetType
from spire.xls.enums.IgnoreErrorType import IgnoreErrorType
from spire.xls.enums.ImageFormatType import ImageFormatType
from spire.xls.interfaces.ImageLocationTypes import ImageLocationTypes
from spire.xls.enums.ImageType import ImageType
from spire.xls.interfaces.InsertMoveOption import InsertMoveOption
from spire.xls.enums.InsertOptionsType import InsertOptionsType
from spire.xls.enums.LegendPositionType import LegendPositionType
from spire.xls.enums.LegendSpacingType import LegendSpacingType
from spire.xls.enums.LineShapeType import LineShapeType
from spire.xls.enums.LineStyleType import LineStyleType
from spire.xls.enums.MeasureUnits import MeasureUnits
from spire.xls.enums.MsoPathType import MsoPathType
from spire.xls.enums.OdsPageBackgroundImagePositionType import OdsPageBackgroundImagePositionType
from spire.xls.enums.OdsPageBackgroundImageType import OdsPageBackgroundImageType
from spire.xls.enums.OdsPageBackgroundType import OdsPageBackgroundType
from spire.xls.enums.OLEDBCommandType import OLEDBCommandType
from spire.xls.enums.OleLinkType import OleLinkType
from spire.xls.enums.OleObjectType import OleObjectType
from spire.xls.enums.OrderBy import OrderBy
from spire.xls.enums.OrderType import OrderType
from spire.xls.enums.PageBreakExtentType import PageBreakExtentType
from spire.xls.enums.PageBreakType import PageBreakType
from spire.xls.enums.PageOrientationType import PageOrientationType
from spire.xls.enums.PagesOrderType import PagesOrderType
from spire.xls.enums.PaperSizeType import PaperSizeType
from spire.xls.enums.PathFillMode import PathFillMode
from spire.xls.enums.PivotAutoFomatTypes import PivotAutoFomatTypes
from spire.xls.enums.PivotBuiltInStyles import PivotBuiltInStyles
from spire.xls.enums.PivotDataType import PivotDataType
from spire.xls.enums.PivotFieldFormatType import PivotFieldFormatType
from spire.xls.enums.PivotFieldSortType import PivotFieldSortType
from spire.xls.enums.PivotItemType import PivotItemType
from spire.xls.enums.PivotPageAreaFieldsOrderType import PivotPageAreaFieldsOrderType
from spire.xls.enums.PivotTableElement import PivotTableElement
from spire.xls.enums.PivotTableLayoutType import PivotTableLayoutType
from spire.xls.enums.PresetTextEffect import PresetTextEffect
from spire.xls.enums.PrintCommentType import PrintCommentType
from spire.xls.enums.PrintErrorsType import PrintErrorsType
from spire.xls.enums.PrintingPageType import PrintingPageType
from spire.xls.enums.PropertyType import PropertyType
from spire.xls.enums.PrstGeomShapeType import PrstGeomShapeType
from spire.xls.enums.PivotValueFilterType import PivotValueFilterType
from spire.xls.enums.PivotLabelFilterType import PivotLabelFilterType
from spire.xls.enums.PivotGroupByTypes import PivotGroupByTypes
from spire.xls.enums.ReadingOrderType import ReadingOrderType
from spire.xls.enums.RectangleShapeType import RectangleShapeType
from spire.xls.enums.RectangleStyleType import RectangleStyleType
from spire.xls.enums.RelationShip import RelationShip
from spire.xls.enums.RenameStrategy import RenameStrategy
from spire.xls.enums.ResizeBehaveType import ResizeBehaveType
from spire.xls.enums.RtfTags import RtfTags
from spire.xls.enums.SelectionType import SelectionType
from spire.xls.enums.ShapeArrowLengthType import ShapeArrowLengthType
from spire.xls.enums.ShapeArrowStyleType import ShapeArrowStyleType
from spire.xls.enums.ShapeArrowWidthType import ShapeArrowWidthType
from spire.xls.enums.ShapeDashLineStyleType import ShapeDashLineStyleType
from spire.xls.enums.ShapeFillType import ShapeFillType
from spire.xls.enums.ShapeLayerChangeType import ShapeLayerChangeType
from spire.xls.enums.ShapeLineStyleType import ShapeLineStyleType
from spire.xls.enums.SheetProtectionType import SheetProtectionType
from spire.xls.enums.SortComparsionType import SortComparsionType
from spire.xls.enums.SortedWayType import SortedWayType
from spire.xls.enums.SortOrientationType import SortOrientationType
from spire.xls.enums.SparklineEmptyCells import SparklineEmptyCells
from spire.xls.enums.SparklineType import SparklineType
from spire.xls.enums.SpartlineVerticalAxisType import SpartlineVerticalAxisType
from spire.xls.enums.SplitType import SplitType
from spire.xls.enums.StrikeThroughStyle import StrikeThroughStyle
from spire.xls.enums.StyleDefineType import StyleDefineType
from spire.xls.enums.SubtotalTypes import SubtotalTypes
from spire.xls.enums.TableBuiltInStyles import TableBuiltInStyles
from spire.xls.enums.TextDirection import TextDirection
from spire.xls.enums.TextDirectionType import TextDirectionType
from spire.xls.enums.TextRotationType import TextRotationType
from spire.xls.enums.ThemeColorType import ThemeColorType
from spire.xls.enums.TickLabelPositionType import TickLabelPositionType
from spire.xls.enums.TickMarkType import TickMarkType
from spire.xls.enums.TimePeriodType import TimePeriodType
from spire.xls.enums.TopBottomType import TopBottomType
from spire.xls.enums.TopFormatType import TopFormatType
from spire.xls.enums.TRangeValueType import TRangeValueType
from spire.xls.enums.TrendLineType import TrendLineType
from spire.xls.enums.UnderlineStyle import UnderlineStyle
from spire.xls.enums.UnknownVariableAction import UnknownVariableAction
from spire.xls.enums.ValidationComparisonOperator import ValidationComparisonOperator
from spire.xls.enums.VariableTypeAction import VariableTypeAction
from spire.xls.enums.VerticalAlignType import VerticalAlignType
from spire.xls.HTMLOptions import HTMLOptions
from spire.xls.enums.ViewMode import ViewMode
from spire.xls.enums.WorksheetCopyType import WorksheetCopyType
from spire.xls.autofilter.AutoFitterOptions import AutoFitterOptions
from spire.xls.enums.WorksheetVisibility import WorksheetVisibility
from spire.xls.enums.XLSXBorderJoinType import XLSXBorderJoinType
from spire.xls.enums.XLSXChartBevelType import XLSXChartBevelType
from spire.xls.enums.XLSXChartLightingType import XLSXChartLightingType
from spire.xls.enums.XLSXChartMaterialType import XLSXChartMaterialType
from spire.xls.enums.XLSXChartPrespectiveType import XLSXChartPrespectiveType
from spire.xls.enums.XLSXChartShadowInnerType import XLSXChartShadowInnerType
from spire.xls.enums.XLSXChartShadowOuterType import XLSXChartShadowOuterType
from spire.xls.enums.XLSXPivotItemType import XLSXPivotItemType
from spire.xls.enums.XmlOpenType import XmlOpenType
from spire.xls.enums.PdfConformanceLevel import PdfConformanceLevel
from spire.xls.collection.CollectionBase import CollectionBase
from spire.xls.TextSaveOptions import TextSaveOptions
from spire.xls.interfaces.IDocumentProperty import IDocumentProperty
from spire.xls.interfaces.IPropertyData import IPropertyData
from spire.xls.ConverterSetting import ConverterSetting
from spire.xls.PageColRow import PageColRow
from spire.xls.ExternalConnection import ExternalConnection
from spire.xls.ExportTableOptions import ExportTableOptions
from spire.xls.DBConnection import DBConnection
from spire.xls.interfaces.IExcelApplication import IExcelApplication
from spire.xls.XlsObject import XlsObject
from spire.xls.interfaces.ImportObjectOptions import ImportObjectOptions
from spire.xls.QueryTableXls import QueryTableXls
from spire.xls.ReferRangeArea import ReferRangeArea
from spire.xls.ReferRangeArea import ListReferRangeAreas
from spire.xls.license.LicenseProvider import LicenseProvider

from spire.xls.interfaces.ICloneParent import ICloneParent
from spire.xls.WebQueryConnection import WebQueryConnection
from spire.xls.interfaces.IShadow import IShadow
from spire.xls.interfaces.IconSet import IconSet
from spire.xls.interfaces.IConditionValue import IConditionValue
from spire.xls.interfaces.IColorConditionValue import IColorConditionValue
from spire.xls.interfaces.IColorScale import IColorScale
from spire.xls.conditional_formatting.XlsConditionValue import XlsConditionValue
from spire.xls.conditional_formatting.ConditionValue import ConditionValue
from spire.xls.conditional_formatting.ColorConditionValue import ColorConditionValue
from spire.xls.ColorScale import ColorScale
from spire.xls.conditional_formatting.NegativeBarFormat import NegativeBarFormat
from spire.xls.conditional_formatting.DataBarBorder import DataBarBorder
from spire.xls.DataBar import DataBar
from spire.xls.interfaces.IConditionalFormat import IConditionalFormat
from spire.xls.interfaces.IConditionalFormats import IConditionalFormats
from spire.xls.DocumentProperty import DocumentProperty
from spire.xls.interfaces.IInterior import IInterior
from spire.xls.interfaces.pivot_table.IPivotCache import IPivotCache
from spire.xls.interfaces.pivot_table.IPivotField import IPivotField
from spire.xls.interfaces.pivot_table.IPivotFields import IPivotFields
from spire.xls.interfaces.pivot_table.IPivotTable import IPivotTable
from spire.xls.sparkline.ISparkline import ISparkline
from spire.xls.sparkline.ISparklines import ISparklines
from spire.xls.sparkline.ISparklineGroup import ISparklineGroup
from spire.xls.sparkline.Sparkline import Sparkline
from spire.xls.template_markers.MarkerDesigner import MarkerDesigner
from spire.xls.conditional_formatting.XlsConditionalFormat import XlsConditionalFormat
from spire.xls.interfaces.IShape import IShape
from spire.xls.interfaces.ITextBox import ITextBox
from spire.xls.interfaces.IPictureShape import IPictureShape
from spire.xls.interfaces.IFormat3D import IFormat3D
from spire.xls.interfaces.IBorder import IBorder
from spire.xls.interfaces.IXLSRange import IXLSRange
from spire.xls.interfaces.ITabSheet import ITabSheet
from spire.xls.CellStyleFlag import CellStyleFlag
from spire.xls.interfaces.IExtendedFormat import IExtendedFormat
from spire.xls.interfaces.IOptimizedUpdate import IOptimizedUpdate
from spire.xls.interfaces.IAddInFunction import IAddInFunction
from spire.xls.interfaces.IFont import IFont
from spire.xls.interfaces.IGradient import IGradient
from spire.xls.interfaces.IHPageBreak import IHPageBreak
from spire.xls.interfaces.IHyperLink import IHyperLink
from spire.xls.interfaces.IPageSetupBase import IPageSetupBase
from spire.xls.interfaces.IRichTextString import IRichTextString
from spire.xls.RichTextObject import RichTextObject
from spire.xls.interfaces.IDataValidation import IDataValidation
from spire.xls.interfaces.IVPageBreak import IVPageBreak
from spire.xls.interfaces.IStyle import IStyle
from spire.xls.interfaces.IWorksheet import IWorksheet
from spire.xls.SaveShapeTypeOption import SaveShapeTypeOption
from spire.xls.OdsPageBackground import OdsPageBackground
from spire.xls.interfaces.IGlow import IGlow
from spire.xls.interfaces.collections.IConditionalFormatsCollection import IConditionalFormatsCollection
from spire.xls.collection.DataConnections import DataConnections
from spire.xls.collection.ExternalLinkCollection import ExternalLinkCollection
from spire.xls.collection.QueryTableCollection import QueryTableCollection
from spire.xls.interfaces.IBuiltInDocumentProperties import IBuiltInDocumentProperties
from spire.xls.interfaces.IXLSRanges import IXLSRanges
from spire.xls.interfaces.pivot_table.IPivotCaches import IPivotCaches
from spire.xls.interfaces.pivot_table.IPivotTables import IPivotTables
from spire.xls.interfaces.collections.IPictures import IPictures
from spire.xls.interfaces.collections.IChartShapes import IChartShapes
from spire.xls.interfaces.collections.IAddInFunctions import IAddInFunctions
from spire.xls.interfaces.collections.IBorders import IBorders
from spire.xls.collection.XlsFontsCollection import XlsFontsCollection
from spire.xls.interfaces.collections.IHPageBreaks import IHPageBreaks
from spire.xls.interfaces.collections.IHyperLinks import IHyperLinks
from spire.xls.interfaces.collections.IVPageBreaks import IVPageBreaks
from spire.xls.interfaces.collections.ITabSheets import ITabSheets
from spire.xls.interfaces.collections.IWorksheets import IWorksheets
from spire.xls.interfaces.collections.IStyles import IStyles
from spire.xls.interfaces.IAutoFilters import IAutoFilters
from spire.xls.interfaces.IChartFillBorder import IChartFillBorder
from spire.xls.interfaces.IChartBorder import IChartBorder
from spire.xls.interfaces.IChartAxis import IChartAxis
from spire.xls.interfaces.IChartTextArea import IChartTextArea
from spire.xls.interfaces.IChartDataPoint import IChartDataPoint
from spire.xls.interfaces.IChartDataTable import IChartDataTable
from spire.xls.interfaces.IChartDropBar import IChartDropBar
from spire.xls.interfaces.IChartFormat import IChartFormat
from spire.xls.interfaces.IChartGridLine import IChartGridLine
from spire.xls.interfaces.IChartInterior import IChartInterior
from spire.xls.interfaces.IChartLegend import IChartLegend
from spire.xls.interfaces.IChartLegendEntry import IChartLegendEntry
from spire.xls.interfaces.IChartPageSetup import IChartPageSetup
from spire.xls.interfaces.IChartFrameFormat import IChartFrameFormat
from spire.xls.interfaces.IChartErrorBars import IChartErrorBars
from spire.xls.interfaces.IChartSerie import IChartSerie
from spire.xls.interfaces.IChartSerieDataFormat import IChartSerieDataFormat
from spire.xls.interfaces.IChartSeriesAxis import IChartSeriesAxis
from spire.xls.interfaces.IChartDataLabels import IChartDataLabels
from spire.xls.charts.XlsChartTitleArea import XlsChartTitleArea
from spire.xls.interfaces.IChartValueAxis import IChartValueAxis
from spire.xls.interfaces.IChartWallOrFloor import IChartWallOrFloor
from spire.xls.interfaces.collections.IChartDataPoints import IChartDataPoints
from spire.xls.interfaces.IChart import IChart
from spire.xls.interfaces.collections.ICharts import ICharts
from spire.xls.interfaces.collections.IChartSeries import IChartSeries
from spire.xls.interfaces.collections.IDataValidationCollection import IDataValidationCollection
from spire.xls.interfaces.IDataValidationTable import IDataValidationTable
from spire.xls.collection.XlsBuiltInDocumentProperties import XlsBuiltInDocumentProperties
from spire.xls.interfaces.ICustomDocumentProperties import ICustomDocumentProperties
from spire.xls.interfaces.IInternalWorksheet import IInternalWorksheet
from spire.xls.interfaces.IMarkersDesigner import IMarkersDesigner
from spire.xls.interfaces.IMigrantRange import IMigrantRange
from spire.xls.interfaces.ICombinedRange import ICombinedRange
from spire.xls.interfaces.pivot_table.IPivotCalculatedFields import IPivotCalculatedFields
from spire.xls.interfaces.pivot_table.IPivotDataField import IPivotDataField
from spire.xls.interfaces.pivot_table.IPivotDataFields import IPivotDataFields
from spire.xls.pivot_tables.XlsPivotField import XlsPivotField
from spire.xls.collection.pivot_table.PivotTableFields import PivotTableFields
from spire.xls.interfaces.pivot_table.IPivotTableOptions import IPivotTableOptions
from spire.xls.pivot_tables.XlsPivotCache import XlsPivotCache
from spire.xls.pivot_tables.XlsPivotCacheField import XlsPivotCacheField
from spire.xls.collection.XlsChartsCollection import XlsChartsCollection
from spire.xls.interfaces.IPrstGeomShape import IPrstGeomShape
from spire.xls.interfaces.IButtonShape import IButtonShape
from spire.xls.interfaces.collections.IButtonShapes import IButtonShapes
from spire.xls.interfaces.INamedObject import INamedObject
from spire.xls.XlsPageSetupBase import XlsPageSetupBase
from spire.xls.CommonWrapper import CommonWrapper
from spire.xls.interfaces.IChartShape import IChartShape
from spire.xls.interfaces.IChartCategoryAxis import IChartCategoryAxis
from spire.xls.interfaces.collections.IChartLegendEntries import IChartLegendEntries
from spire.xls.interfaces.ICheckBox import ICheckBox
from spire.xls.interfaces.collections.ICheckBoxes import ICheckBoxes
from spire.xls.interfaces.IComboBoxShape import IComboBoxShape
from spire.xls.interfaces.ITextBoxShape import ITextBoxShape
from spire.xls.interfaces.IComment import IComment
from spire.xls.interfaces.IGeomPathInfo import IGeomPathInfo
from spire.xls.interfaces.IGeomPathShape import IGeomPathShape
from spire.xls.interfaces.IGroupBox import IGroupBox
from spire.xls.interfaces.ILabelShape import ILabelShape
from spire.xls.interfaces.ILineShape import ILineShape
from spire.xls.interfaces.IListBox import IListBox
from spire.xls.interfaces.IOleObject import IOleObject
from spire.xls.interfaces.IOvalShape import IOvalShape
from spire.xls.interfaces.IArcShape import IArcShape
from spire.xls.interfaces.collections.IArcShapes import IArcShapes
from spire.xls.interfaces.IGeomPath import IGeomPath
from spire.xls.interfaces.IRadioButton import IRadioButton
from spire.xls.interfaces.IRectangleShape import IRectangleShape
from spire.xls.interfaces.IScrollBarShape import IScrollBarShape
from spire.xls.interfaces.ICommentShape import ICommentShape
from spire.xls.interfaces.collections.IComments import IComments
from spire.xls.interfaces.IShapeFill import IShapeFill
from spire.xls.interfaces.IShapeLineFormat import IShapeLineFormat
from spire.xls.interfaces.ISpinnerShape import ISpinnerShape
from spire.xls.interfaces.collections.IComboBoxes import IComboBoxes
from spire.xls.interfaces.collections.IGroupBoxes import IGroupBoxes
from spire.xls.interfaces.collections.ILabelShapes import ILabelShapes
from spire.xls.interfaces.collections.ILines import ILines
from spire.xls.interfaces.collections.IListBoxes import IListBoxes
from spire.xls.interfaces.collections.IOleObjects import IOleObjects
from spire.xls.interfaces.collections.IOvalShapes import IOvalShapes
from spire.xls.interfaces.collections.IPrstGeomShapes import IPrstGeomShapes
from spire.xls.interfaces.collections.IRadioButtons import IRadioButtons
from spire.xls.interfaces.collections.IRectangleShapes import IRectangleShapes
from spire.xls.interfaces.collections.IScrollBarShapes import IScrollBarShapes
from spire.xls.interfaces.collections.ISpinnerShapes import ISpinnerShapes
from spire.xls.interfaces.ITextBoxLinkShape import ITextBoxLinkShape
from spire.xls.interfaces.collections.ITextBoxes import ITextBoxes
from spire.xls.TextBoxShapeBase import TextBoxShapeBase
from spire.xls.interfaces.ITextFrame import ITextFrame
from spire.xls.interfaces.sorting.IDataSort import IDataSort
from spire.xls.interfaces.ISortColumn import ISortColumn
from spire.xls.interfaces.ISortColumns import ISortColumns
from spire.xls.interfaces.ISortedRule import ISortedRule
from spire.xls.interfaces.collections.IWorksheetGroup import IWorksheetGroup
from spire.xls.interfaces.IReflectionEffect import IReflectionEffect
from spire.xls.interfaces.IErrorIndicator import IErrorIndicator
from spire.xls.interfaces.IDataBar import IDataBar
from spire.xls.interfaces.IIconSet import IIconSet
from spire.xls.interfaces.IAutoFilterCondition import IAutoFilterCondition
from spire.xls.interfaces.INamedRange import INamedRange
from spire.xls.interfaces.INumberFormat import INumberFormat
from spire.xls.interfaces.IPageSetup import IPageSetup
from spire.xls.interfaces.IExtendIndex import IExtendIndex
from spire.xls.interfaces.IInternalAddtionalFormat import IInternalAddtionalFormat
from spire.xls.interfaces.IInternalFont import IInternalFont
from spire.xls.interfaces.IDigitalSignature import IDigitalSignature
from spire.xls.interfaces.IDigitalSignatures import IDigitalSignatures
from spire.xls.PicTile import PicTile
from spire.xls.PicStretch import PicStretch
from spire.xls.charts.ChartShadow import ChartShadow
from spire.xls.XlsShapeFill import XlsShapeFill
from spire.xls.charts.XlsChartBorder import XlsChartBorder
from spire.xls.charts.XlsChartAxis import XlsChartAxis
from spire.xls.charts.XlsChartCategoryAxis import XlsChartCategoryAxis
from spire.xls.charts.XlsChartDataTable import XlsChartDataTable
from spire.xls.charts.XlsChartDropBar import XlsChartDropBar
from spire.xls.charts.XlsChartFrameFormat import XlsChartFrameFormat
from spire.xls.charts.XlsChartFormat import XlsChartFormat
from spire.xls.collection.XlsChartFormatCollection import XlsChartFormatCollection
from spire.xls.charts.XlsChartPlotArea import XlsChartPlotArea
from spire.xls.charts.XlsChartInterior import XlsChartInterior
from spire.xls.charts.XlsChartLegend import XlsChartLegend
from spire.xls.charts.XlsChartLegendEntry import XlsChartLegendEntry
from spire.xls.charts.XlsChartPageSetup import XlsChartPageSetup
from spire.xls.charts.XlsChartSerieDataFormat import XlsChartSerieDataFormat
from spire.xls.charts.XlsChartSeriesAxis import XlsChartSeriesAxis
from spire.xls.charts.XlsChartDataLabelArea import XlsChartDataLabelArea
from spire.xls.charts.XlsChartDataLabels import XlsChartDataLabels
from spire.xls.charts.XlsChartDataPoint import XlsChartDataPoint
from spire.xls.collection.XlsChartDataPointsCollection import XlsChartDataPointsCollection
from spire.xls.charts.XlsChartValueAxis import XlsChartValueAxis
from spire.xls.charts.XlsChartWallOrFloor import XlsChartWallOrFloor
from spire.xls.interfaces.IChartTrendLine import IChartTrendLine
from spire.xls.interfaces.collections.IChartTrendLines import IChartTrendLines
from spire.xls.XlsShape import XlsShape
from spire.xls.XlsBitmapShape import XlsBitmapShape
from spire.xls.collection.XlsPicturesCollection import XlsPicturesCollection
from spire.xls.RichText import RichText
from spire.xls.ExcelCommentObject import ExcelCommentObject
from spire.xls.ExcelComment import ExcelComment
from spire.xls.MsoPathInfo import MsoPathInfo
from spire.xls.XlsAddInFunction import XlsAddInFunction
from spire.xls.collection.XlsAddInFunctionsCollection import XlsAddInFunctionsCollection
from spire.xls.ExternalLink import ExternalLink
from spire.xls.collection.XlsWorkbookObjectsCollection import XlsWorkbookObjectsCollection
from spire.xls.ExcelFont import ExcelFont
from spire.xls.XlsBorder import XlsBorder
from spire.xls.XlsBorderArrayWrapper import XlsBorderArrayWrapper
from spire.xls.CellBorder import CellBorder
from spire.xls.collection.BordersCollection import BordersCollection
from spire.xls.CellStyleObject import CellStyleObject
from spire.xls.collection.XlsStylesCollection import XlsStylesCollection
from spire.xls.ExcelGradient import ExcelGradient
from spire.xls.ExcelInterior import ExcelInterior
from spire.xls.CellStyle import CellStyle
from spire.xls.XlsValidationWrapper import XlsValidationWrapper
from spire.xls.Validation import Validation
from spire.xls.GroupShape import GroupShape
from spire.xls.collection.GroupShapeCollection import GroupShapeCollection
from spire.xls.conditional_formatting.ConditionalFormatWrapper import ConditionalFormatWrapper
from spire.xls.conditional_formatting.CondFormatCollectionWrapper import CondFormatCollectionWrapper
from spire.xls.conditional_formatting.ConditionalFormats import ConditionalFormats
from spire.xls.XlsRange import XlsRange
from spire.xls.XlsRange import EnumeratorXlsRange
from spire.xls.XlsRange import ListXlsRanges
from spire.xls.XlsHyperLink import XlsHyperLink
from spire.xls.collection.XlsHyperLinksCollection import XlsHyperLinksCollection
from spire.xls.collection.pivot_table.XlsPivotCachesCollection import XlsPivotCachesCollection

from spire.xls.XlsHPageBreak import XlsHPageBreak
from spire.xls.XlsVPageBreak import XlsVPageBreak
from spire.xls.HPageBreak import HPageBreak
from spire.xls.VPageBreak import VPageBreak
from spire.xls.collection.XlsHPageBreaksCollection import XlsHPageBreaksCollection
from spire.xls.collection.XlsVPageBreaksCollection import XlsVPageBreaksCollection
from spire.xls.interfaces.IListObjectColumn import IListObjectColumn
from spire.xls.interfaces.IListObjectColumn import ListObjectColumns
from spire.xls.interfaces.IListObject import IListObject
from spire.xls.interfaces.collections.IListObjects import IListObjects
from spire.xls.collection.XlsRangesCollection import XlsRangesCollection
from spire.xls.interfaces.IWorkbook import IWorkbook
from spire.xls.OColor import OColor
from spire.xls.interfaces.IAutoFilter import IAutoFilter
from spire.xls.XlsDocumentProperty import XlsDocumentProperty
from spire.xls.ShapeReflection import ShapeReflection
from spire.xls.Format3D import Format3D
from spire.xls.charts.XlsChartSerie import XlsChartSerie
from spire.xls.collection.XlsChartSeries import XlsChartSeries
from spire.xls.ShapeGlow import ShapeGlow
from spire.xls.WriteProtection import WriteProtection
from spire.xls.AddtionalFormatWrapper import AddtionalFormatWrapper
from spire.xls.XlsFill import XlsFill
from spire.xls.RichTextShape import RichTextShape
from spire.xls.RTFCommentArray import RTFCommentArray
from spire.xls.CellBaseStyle import CellBaseStyle
from spire.xls.FontArrayWrapper import FontArrayWrapper
from spire.xls.FontWrapper import FontWrapper
from spire.xls.GradientArrayWrapper import GradientArrayWrapper
from spire.xls.interfaces.InteriorArrayWrapper import InteriorArrayWrapper
from spire.xls.RichTextString import RichTextString
from spire.xls.RangeRichTextString import RangeRichTextString
from spire.xls.RtfTextWriter import RtfTextWriter
from spire.xls.LOGFONT import LOGFONT
from spire.xls.RTFStringArray import RTFStringArray
from spire.xls.StyleArrayWrapper import StyleArrayWrapper
from spire.xls.UtilityMethods import UtilityMethods
from spire.xls.ExcelAddInFunction import ExcelAddInFunction
from spire.xls.XlsGradient import XlsGradient
from spire.xls.XlsValidation import XlsValidation
from spire.xls.XlsDataValidationTable import XlsDataValidationTable
from spire.xls.XlsFont import XlsFont
from spire.xls.XlsFontStyle import XlsFontStyle
from spire.xls.HyperLink import HyperLink
from spire.xls.XlsName import XlsName
from spire.xls.interfaces.collections.INameRanges import INameRanges
from spire.xls.charts.ChartTextArea import ChartTextArea
from spire.xls.XlsEventArgs import XlsEventArgs
from spire.xls.XlsEventHandler import XlsEventHandler
from spire.xls.XlsPageSetup import XlsPageSetup
from spire.xls.PageSetup import PageSetup
from spire.xls.CellRange import ListCellRanges
from spire.xls.CellRange import CellRange
from spire.xls.sparkline.SparklineCollection import SparklineCollection
from spire.xls.sparkline.SparklineGroup import SparklineGroup
from spire.xls.sparkline.SparklineGroupCollection import SparklineGroupCollection
from spire.xls.CellValueChangedEventArgs import CellValueChangedEventArgs
from spire.xls.XlsStyle import XlsStyle
from spire.xls.collection.ListObjectCollection import ListObjectCollection
from spire.xls.collection.LabelShapeCollection import LabelShapeCollection
from spire.xls.conditional_formatting.ConditionalFormat import ConditionalFormat
from spire.xls.Average import Average
from spire.xls.TopBottom import TopBottom
from spire.xls.autofilter.ColorFilter import ColorFilter
from spire.xls.autofilter.CustomFilter import CustomFilter
from spire.xls.autofilter.CustomFilterCollection import CustomFilterCollection
from spire.xls.autofilter.DateTimeGroupItem import DateTimeGroupItem
from spire.xls.autofilter.DynamicFilter import DynamicFilter
from spire.xls.autofilter.FilterColumn import FilterColumn
from spire.xls.autofilter.XlsAutoFiltersCollection import XlsAutoFiltersCollection
from spire.xls.autofilter.MultipleFilterCollection import MultipleFilterCollection
from spire.xls.autofilter.Top10Filter import Top10Filter
from spire.xls.sorting.SortColumn import SortColumn
from spire.xls.sorting.SortColumns import SortColumns
from spire.xls.sorting.DataSorter import DataSorter
from spire.xls.security.EncryptedKeyInfo import EncryptedKeyInfo
from spire.xls.collection.pivot_table.PivotCalculatedFieldsCollection import PivotCalculatedFieldsCollection
from spire.xls.collection.pivot_table.PivotConditionalFormatCollection import PivotConditionalFormatCollection
from spire.xls.pivot_tables.AutoSortScope import AutoSortScope
from spire.xls.pivot_tables.PivotConditionalFormat import PivotConditionalFormat
from spire.xls.pivot_tables.PivotDataField import PivotDataField
from spire.xls.collection.pivot_table.PivotDataFields import PivotDataFields
from spire.xls.pivot_tables.PivotItem import PivotItem
from spire.xls.pivot_tables.PivotReportFilter import PivotReportFilter
from spire.xls.pivot_tables.PivotReportFilters import PivotReportFilters
from spire.xls.pivot_tables.PivotStyle import PivotStyle
from spire.xls.pivot_tables.PivotTableStyle import PivotTableStyle
from spire.xls.pivot_tables.PivotCache import PivotCache
from spire.xls.pivot_tables.PivotField import PivotField
from spire.xls.pivot_tables.XlsPivotTable import XlsPivotTable
from spire.xls.collection.pivot_table.XlsPivotTablesCollection import XlsPivotTablesCollection
from spire.xls.pivot_tables.PivotTable import PivotTable
from spire.xls.charts.ChartLegendEntriesColl import ChartLegendEntriesColl
from spire.xls.charts.ChartBorder import ChartBorder
from spire.xls.charts.XlsChartGridLine import XlsChartGridLine
from spire.xls.charts.ChartCategoryAxis import ChartCategoryAxis
from spire.xls.charts.ChartDataLabels import ChartDataLabels
from spire.xls.charts.ChartSerieDataFormat import ChartSerieDataFormat
from spire.xls.charts.ChartDataPoint import ChartDataPoint
from spire.xls.charts.ChartDataTable import ChartDataTable
from spire.xls.charts.ChartDropBar import ChartDropBar
from spire.xls.charts.ChartFormat import ChartFormat
from spire.xls.charts.ChartArea import ChartArea
from spire.xls.charts.ChartGridLine import ChartGridLine
from spire.xls.charts.ChartInterior import ChartInterior
from spire.xls.charts.ChartLegend import ChartLegend
from spire.xls.charts.XlsChartLegendArea import XlsChartLegendArea
from spire.xls.charts.ChartLegendEntry import ChartLegendEntry
from spire.xls.charts.ChartPageSetup import ChartPageSetup
from spire.xls.charts.ChartPlotArea import ChartPlotArea
from spire.xls.collection.ChartDataPointsCollection import ChartDataPointsCollection
from spire.xls.charts.ChartSerie import ChartSerie
from spire.xls.charts.HistogramAxisFormat import HistogramAxisFormat
from spire.xls.charts.ChartSeriesAxis import ChartSeriesAxis
from spire.xls.charts.ChartTitle import ChartTitle
from spire.xls.charts.ChartValueAxis import ChartValueAxis
from spire.xls.charts.ChartWallOrFloor import ChartWallOrFloor
from spire.xls.collection.ChartFormatCollection import ChartFormatCollection
from spire.xls.collection.ChartSeries import ChartSeries
from spire.xls.GeomertyAdjustValue import GeomertyAdjustValue
from spire.xls.XlsGradientStop import XlsGradientStop
from spire.xls.GradientStops import GradientStops
from spire.xls.CommentsRange import CommentsRange
from spire.xls.collection.GeomertyAdjustValuesCollection import GeomertyAdjustValuesCollection
from spire.xls.XlsPrstGeomShape import XlsPrstGeomShape
from spire.xls.ExcelPicture import ExcelPicture
from spire.xls.XlsButtonShape import XlsButtonShape
from spire.xls.XlsCheckBoxShape import XlsCheckBoxShape
from spire.xls.XlsComboBoxShape import XlsComboBoxShape
from spire.xls.XlsComment import XlsComment
from spire.xls.XlsGroupBoxShape import XlsGroupBoxShape
from spire.xls.XlsLabelShape import XlsLabelShape
from spire.xls.XlsLineShape import XlsLineShape
from spire.xls.XlsListBoxShape import XlsListBoxShape
from spire.xls.XlsOvalShape import XlsOvalShape
from spire.xls.XlsArcShape import XlsArcShape
from spire.xls.ShapeGeomPath import ShapeGeomPath
from spire.xls.ShapeSegmentPath import ShapeSegmentPath
from spire.xls.XlsRadioButtonShape import XlsRadioButtonShape
from spire.xls.XlsRectangleShape import XlsRectangleShape
from spire.xls.XlsScrollBarShape import XlsScrollBarShape
from spire.xls.XlsShapeLineFormat import XlsShapeLineFormat
from spire.xls.XlsSpinnerShape import XlsSpinnerShape
from spire.xls.XlsTextBoxShape import XlsTextBoxShape
from spire.xls.interfaces.collections.IShapes import IShapes
from spire.xls.charts.XlsChartFill import XlsChartFill
from spire.xls.collection.BuiltInDocumentProperties import BuiltInDocumentProperties
from spire.xls.collection.ShapeCollectionBase import ShapeCollectionBase
from spire.xls.collection.XlsCommentsCollection import XlsCommentsCollection
from spire.xls.collection.RangesCollection import RangesCollection
from spire.xls.collection.pivot_table.PivotCachesCollection import PivotCachesCollection
from spire.xls.collection.pivot_table.PivotTablesCollection import PivotTablesCollection
from spire.xls.collection.ArcShapeCollection import ArcShapeCollection
from spire.xls.collection.ButtonShapeCollection import ButtonShapeCollection
from spire.xls.collection.CheckBoxCollection import CheckBoxCollection
from spire.xls.collection.ComboBoxCollection import ComboBoxCollection
from spire.xls.collection.GroupBoxCollection import GroupBoxCollection
from spire.xls.collection.LineCollection import LineCollection
from spire.xls.collection.ListBoxCollection import ListBoxCollection
from spire.xls.collection.OvalShapeCollection import OvalShapeCollection
from spire.xls.collection.PrstGeomShapeCollection import PrstGeomShapeCollection
from spire.xls.collection.RadioButtonCollection import RadioButtonCollection
from spire.xls.collection.RectangleCollection import RectangleCollection
from spire.xls.collection.ScrollBarCollection import ScrollBarCollection
from spire.xls.collection.XlsHeaderFooterShapeCollection import XlsHeaderFooterShapeCollection
from spire.xls.collection.SpinnerShapeCollection import SpinnerShapeCollection
from spire.xls.collection.TextBoxCollection import TextBoxCollection
from spire.xls.collection.CommentsCollection import CommentsCollection
from spire.xls.collection.PicturesCollection import PicturesCollection
from spire.xls.collection.BordersCollectionArrayWrapper import BordersCollectionArrayWrapper
from spire.xls.collection.AddInFunctionsCollection import AddInFunctionsCollection
from spire.xls.collection.XlsBordersCollection import XlsBordersCollection
from spire.xls.collection.XlsDataValidationCollection import XlsDataValidationCollection
from spire.xls.collection.FontsCollection import FontsCollection
from spire.xls.collection.HPageBreaksCollection import HPageBreaksCollection
from spire.xls.collection.HyperLinksCollection import HyperLinksCollection
from spire.xls.collection.StylesCollection import StylesCollection
from spire.xls.collection.VPageBreaksCollection import VPageBreaksCollection
from spire.xls.collection.CollectionExtended import CollectionExtended
from spire.xls.collection.CollectionChangeEventArgs import CollectionChangeEventArgs
from spire.xls.collection.AutoFiltersCollection import AutoFiltersCollection
from spire.xls.conditional_formatting.XlsConditionalFormats import XlsConditionalFormats
from spire.xls.collection.XlsWorksheetConditionalFormats import XlsWorksheetConditionalFormats
from spire.xls.collection.WorksheetConditionalFormats import WorksheetConditionalFormats
from spire.xls.PaperSizeEntry import PaperSizeEntry
from spire.xls.CellValueChangedEventHandler import CellValueChangedEventHandler
from spire.xls.charts.XlsChartShape import XlsChartShape
from spire.xls.charts.Chart import Chart
from spire.xls.collection.XlsWorksheetChartsCollection import XlsWorksheetChartsCollection
from spire.xls.collection.WorksheetChartsCollection import WorksheetChartsCollection
from spire.xls.XlsWorksheetBase import XlsWorksheetBase
from spire.xls.charts.XlsChart import XlsChart
from spire.xls.charts.ChartSheet import ChartSheet
from spire.xls.collection.ChartsCollection import ChartsCollection
from spire.xls.XlsWorksheet import XlsWorksheet
from spire.xls.collection.XlsWorksheetsCollection import XlsWorksheetsCollection

#class Workbook (SpireObject) :
#    pass

from spire.xls.Worksheet import Worksheet
from spire.xls.XlsWorkbook import XlsWorkbook
from spire.xls.collection.WorkbookObjectsCollection import WorkbookObjectsCollection
from spire.xls.collection.WorksheetsCollection import WorksheetsCollection
from spire.xls.Workbook import Workbook
from spire.xls.StringUtil import StringUtil


