# coding: utf-8

"""
    AccessibleTranslator SDK API

    Official SDK API for AccessibleTranslator - automated cognitive accessibility

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from accessibletranslator.models.translation_request import TranslationRequest

class TestTranslationRequest(unittest.TestCase):
    """TranslationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TranslationRequest:
        """Test TranslationRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TranslationRequest`
        """
        model = TranslationRequest()
        if include_optional:
            return TranslationRequest(
                text = '',
                transformations = [
                    ''
                    ],
                input_type = '',
                target_language = ''
            )
        else:
            return TranslationRequest(
                text = '',
                transformations = [
                    ''
                    ],
        )
        """

    def testTranslationRequest(self):
        """Test TranslationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
