{
 "title": "Stackgen Ingress Dashboard",
 "description": "Nginx Ingress Controller via Prometheus Metrics Dashboard created for DevOps Nirvana @ https://github.com/DevOps-Nirvana",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "controller_class",
    "label": "Controller Class",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash, controller_class) "
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(resource_namespace)"
    }
   },
   {
    "name": "ingress",
    "label": "Ingress",
    "query": {
     "query": "label_values(nginx_ingress_controller_requests{resource_namespace=~\"$namespace\",controller_class=~\"$controller_class\"}, ingress) "
    }
   },
   {
    "name": "pod",
    "label": "Ingress Pod",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash{controller_class=~\"$controller_class\"}, controller_pod) "
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests (period)",
   "type": "stat",
   "description": "This is the total number of requests made in this period (top-right period selected)",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_nginx_http_requests_total[${__range_s}s]))"
    }
   ]
  },
  {
   "title": "% Success (period)",
   "type": "stat",
   "description": "This is the percentage of successful requests over the entire period in the top-right hand corner.\n\nNOTE: Ignoring 404s in this metric, since a 404 is a normal response for errant/invalid request.  This helps prevent this percentage from being affected by typical web scanners and security probes.",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5,\n  sum(rate(nginx_ingress_controller_upstream_server_response_latency_ms_bucket{controller_class=~\"$controller_class\", resource_namespace=~\"$namespace\"}[5m])) by (le)\n) < 500\n"
    }
   ]
  },
  {
   "title": "Conns (2m)",
   "type": "stat",
   "description": "This is the number of new connections made to the controller in the last minute.  NOTE: This metric does not support the Ingress, Namespace variables, as this is at a lower-level than the actual application.  It does support the others though (Env, Controller Class, Pod)",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  avg_over_time(\n    nginx_ingress_nginx_connections_active{\n      controller_class=~\"$controller_class\",\n      pod=~\"$pod\"\n    }[$__interval]\n  )\n)\n",
     "legendFormat": "{{`{{ ingress }}`}}"
    }
   ]
  },
  {
   "title": "Reqs (2m)",
   "type": "stat",
   "description": "The number of HTTP requests made in the last 1 minute window",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_nginx_http_requests_total[$__interval]))\n"
    }
   ]
  },
  {
   "title": "HTTP 1/2xx Success Rate (2m)",
   "type": "stat",
   "description": "This is the number of successful requests in the last minute. Successful being 1xx or 2xx by the standard HTTP definition.",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rate(nginx_ingress_controller_upstream_server_response_latency_ms_count{code=~\"(1|2).*\", resource_namespace=~\"$namespace\"}[2m]))\n  /\n  sum(rate(nginx_ingress_controller_upstream_server_response_latency_ms_count{resource_namespace=~\"$namespace\"}[2m]))\n) * 100\n"
    }
   ]
  },
  {
   "title": "HTTP 3xx (2m)",
   "type": "stat",
   "description": "This is the number of 3xx requests in the last minute.",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_upstream_server_response_latency_ms_sum{status=~\"(1|2).*\", controller_class=~\"$pod\"}[5m])) or vector(0)\n"
    }
   ]
  },
  {
   "title": "HTTP 4xx (2m)",
   "type": "stat",
   "description": "This is the number of 4xx requests in the last minute.",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rate(nginx_ingress_controller_upstream_server_response_latency_ms_count{code=~\"4.*\", controller_class=~\"$controller_class\", resource_namespace=~\"$namespace\"}[2m]))\n  /\n  sum(rate(nginx_ingress_controller_upstream_server_response_latency_ms_count{controller_class=~\"$controller_class\", resource_namespace=~\"$namespace\"}[2m]))\n) * 100\n"
    }
   ]
  },
  {
   "title": "HTTP 5xx (2m)",
   "type": "stat",
   "description": "This is the number of 5xx requests in the last minute.",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rate(nginx_ingress_controller_upstream_server_response_latency_ms_count{code=~\"5.*\", controller_class=~\"$controller_class\", resource_namespace=~\"$namespace\"}[2m]))\n  /\n  sum(rate(nginx_ingress_controller_upstream_server_response_latency_ms_count{controller_class=~\"$controller_class\", resource_namespace=~\"$namespace\"}[2m]))\n) * 100\n"
    }
   ]
  },
  {
   "title": "HTTP Status Code Breakdown (2m)",
   "type": "histogram",
   "description": "Breakdown of HTTP status codes (2xx, 3xx, 4xx, 5xx) in the last 2 minutes based on the given controller class and namespace.",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(code) (nginx_ingress_controller_upstream_server_response_latency_ms_count{controller_class=~\"$controller_class\", resource_namespace=~\"$namespace\"})",
     "legendFormat": "{{`{{ code }}`}}"
    }
   ]
  },
  {
   "title": "Total HTTP Requests",
   "type": "timeseries",
   "description": "The total number of HTTP requests made within' each period",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 4 },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_upstream_server_response_latency_ms_count{controller_class=~\"$controller_class\", resource_namespace=~\"$namespace\", ingress=~\"$ingress\"}[2m]))\n",
     "legendFormat": "{{`{{ ingress }}`}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Latency (Average Percentiles)",
   "type": "barchart",
   "description": "This graph can help assess and help us meet SLA requirements as far as the responsive time of our services.\n\nFor a more detailed latency graph broken out by ingress please open the closed tab at the bottom because it is very CPU intensive.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le)(\n    rate(\n      nginx_ingress_controller_upstream_server_response_latency_ms_bucket{\n        controller_class=~\"$controller_class\",\n        ingress=~\"$ingress\",\n        resource_namespace=~\"$namespace\",\n        controller_pod=~\"$pod\"\n      }[$__interval]\n    )\n  )\n)",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le)(\n    rate(\n      nginx_ingress_controller_request_duration_seconds_bucket{\n        status!=\"404|500|304|499\",\n        controller_class=~\"$controller_class\",\n        ingress=~\"$ingress\",\n        resource_namespace=~\"$namespace\",\n        controller_pod=~\"$pod\"\n      }[$__interval]\n    )\n  )\n)",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(\n  0.9,\n  sum by (le)(\n    rate(\n      nginx_ingress_controller_request_duration_seconds_bucket{\n        status!=\"404|500|304|499\",\n        controller_class=~\"$controller_class\",\n        ingress=~\"$ingress\",\n        resource_namespace=~\"$namespace\",\n        controller_pod=~\"$pod\"\n      }[$__interval]\n    )\n  )\n)",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (le)(\n    rate(\n      nginx_ingress_controller_request_duration_seconds_bucket{\n        status!=\"404|500|304|499\",\n        controller_class=~\"$controller_class\",\n        ingress=~\"$ingress\",\n        resource_namespace=~\"$namespace\",\n        controller_pod=~\"$pod\"\n      }[$__interval]\n    )\n  )\n)",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(\n  0.75,\n  sum by (le)(\n    rate(\n      nginx_ingress_controller_request_duration_seconds_bucket{\n        status!=\"404|500|304|499\",\n        controller_class=~\"$controller_class\",\n        ingress=~\"$ingress\",\n        resource_namespace=~\"$namespace\",\n        controller_pod=~\"$pod\"\n      }[$__interval]\n    )\n  )\n)",
     "legendFormat": "0.75"
    },
    {
     "expr": "(\n\n(sum(increase(nginx_ingress_controller_request_duration_seconds_bucket{\n    status!=\"404|500|304\",\n    controller_class=~\"$controller_class\",\n    ingress=~\"$ingress\",\n    resource_namespace=~\"$namespace\",\n    controller_pod=~\"$pod\",\n    le=\"0.01\"\n}[$__interval]))\n* 0.01)\n\n+\n\n((sum(increase(nginx_ingress_controller_request_duration_seconds_bucket{\n    status!=\"404|500|304\",\n    controller_class=~\"$controller_class\",\n    ingress=~\"$ingress\",\n    resource_namespace=~\"$namespace\",\n    controller_pod=~\"$pod\",\n    le=\"0.1\"\n}[$__interval]))\n-\nsum(increase(nginx_ingress_controller_request_duration_seconds_bucket{\n    status!=\"404|500|304\",\n    controller_class=~\"$controller_class\",\n    ingress=~\"$ingress\",\n    resource_namespace=~\"$namespace\",\n    controller_pod=~\"$pod\",\n    le=\"0.01\"\n}[$__interval])))\n* 0.1)\n\n+\n\n((sum(increase(nginx_ingress_controller_request_duration_seconds_bucket{\n    status!=\"404|500|304\",\n    controller_class=~\"$controller_class\",\n    ingress=~\"$ingress\",\n    resource_namespace=~\"$namespace\",\n    controller_pod=~\"$pod\",\n    le=\"1\"\n}[$__interval]))\n-\nsum(increase(nginx_ingress_controller_request_duration_seconds_bucket{\n    status!=\"404|500|304\",\n    controller_class=~\"$controller_class\",\n    ingress=~\"$ingress\",\n    resource_namespace=~\"$namespace\",\n    controller_pod=~\"$pod\",\n    le=\"0.1\"\n}[$__interval])))\n* 1)\n\n+\n\n((sum(increase(nginx_ingress_controller_request_duration_seconds_bucket{\n    status!=\"404|500|304\",\n    controller_class=~\"$controller_class\",\n    ingress=~\"$ingress\",\n    resource_namespace=~\"$namespace\",\n    controller_pod=~\"$pod\",\n    le=\"10\"\n}[$__interval]))\n-\nsum(increase(nginx_ingress_controller_request_duration_seconds_bucket{\n    status!=\"404|500|304\",\n    controller_class=~\"$controller_class\",\n    ingress=~\"$ingress\",\n    resource_namespace=~\"$namespace\",\n    controller_pod=~\"$pod\",\n    le=\"1\"\n}[$__interval])))\n* 10 )\n\n+\n\n((sum(increase(nginx_ingress_controller_request_duration_seconds_bucket{\n    status!=\"404|500|304\",\n    controller_class=~\"$controller_class\",\n    ingress=~\"$ingress\",\n    resource_namespace=~\"$namespace\",\n    controller_pod=~\"$pod\",\n    le=\"30\"\n}[$__interval]))\n-\nsum(increase(nginx_ingress_controller_request_duration_seconds_bucket{\n    status!=\"404|500|304\",\n    controller_class=~\"$controller_class\",\n    ingress=~\"$ingress\",\n    resource_namespace=~\"$namespace\",\n    controller_pod=~\"$pod\",\n    le=\"10\"\n}[$__interval])))\n* 30 )\n\n+\n\n((sum(increase(nginx_ingress_controller_request_duration_seconds_bucket{\n    status!=\"404|500|304\",\n    controller_class=~\"$controller_class\",\n    ingress=~\"$ingress\",\n    resource_namespace=~\"$namespace\",\n    controller_pod=~\"$pod\",\n    le=\"60\"\n}[$__interval]))\n-\nsum(increase(nginx_ingress_controller_request_duration_seconds_bucket{\n    status!=\"404|500|304\",\n    controller_class=~\"$controller_class\",\n    ingress=~\"$ingress\",\n    resource_namespace=~\"$namespace\",\n    controller_pod=~\"$pod\",\n    le=\"30\"\n}[$__interval])))\n* 60 )\n\n+\n\n((sum(increase(nginx_ingress_controller_request_duration_seconds_bucket{\n    status!=\"404|500|304\",\n    controller_class=~\"$controller_class\",\n    ingress=~\"$ingress\",\n    resource_namespace=~\"$namespace\",\n    controller_pod=~\"$pod\",\n    le=\"+Inf\"\n}[$__interval]))\n-\nsum(increase(nginx_ingress_controller_request_duration_seconds_bucket{\n    status!=\"404|500|304\",\n    controller_class=~\"$controller_class\",\n    ingress=~\"$ingress\",\n    resource_namespace=~\"$namespace\",\n    controller_pod=~\"$pod\",\n    le=\"60\"\n}[$__interval])))\n* 120 )\n\n) / \n\nsum(increase(nginx_ingress_controller_request_duration_seconds_bucket{\n    status!=\"404|500|304\",\n    controller_class=~\"$controller_class\",\n    ingress=~\"$ingress\",\n    resource_namespace=~\"$namespace\",\n    controller_pod=~\"$pod\",\n    le=\"+Inf\"\n}[$__interval]))\n",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Latency Heatmap",
   "type": "heatmap",
   "description": "This graph can help assess and help us meet SLA requirements as far as the responsive time of our services.\n\nFor a more detailed latency graph broken out by ingress please open the closed tab at the bottom because it is very CPU intensive.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum by (le)(\n  increase(\n    nginx_ingress_controller_upstream_server_response_latency_ms_bucket{\n      controller_class =~ \"$controller_class\",\n      resource_namespace =~ \"$namespace\",\n      code=\"200\",\n      ingress =~ \"$ingress\"\n    }[$__interval]\n  )\n)",
     "legendFormat": "{{`{{ le }}`}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "New Connections Opened (Controller / Ingress Pod)",
   "type": "barchart",
   "description": "NOTE: This does not work per ingress/namespace\n\nThis is the number of new connections opened by the controller",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_nginx_connections_accepted{\n  controller_class=~\"$controller_class\",\n  controller_pod=~\"$pod\"\n}[$__interval]))",
     "legendFormat": "New Connections"
    }
   ]
  },
  {
   "title": "Total Connections Open (Controller / Ingress Pod)",
   "type": "histogram",
   "description": "NOTE: This does not work per ingress/namespace\n\nThe total number of connections opened to our ingresses.  If you have a CDN in front of our services, it is not unusual for this to be very low.  If/when we use something like websockets with a persistent connection this can/will be very high.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "avg(nginx_ingress_nginx_connections_active)",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "CPU Intensive / Optional Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Percentage of Success (non-2xx) - By Ingress",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rate(nginx_ingress_controller_upstream_server_response_latency_ms_count{controller_class=~\"$controller_class\", resource_namespace=~\"$namespace\", ingress=~\"$ingress\", code=~\"^(3|4|5).*\"}[2m]))\n)\n/\n(\n  sum(rate(nginx_ingress_controller_upstream_server_response_latency_ms_count{controller_class=~\"$controller_class\", resource_namespace=~\"$namespace\", ingress=~\"$ingress\"}[2m]))\n)\n* 100\n",
     "legendFormat": "{{`{{ ingress }}`}}"
    }
   ]
  },
  {
   "title": "Percentage of Success (non-2xx) - By Ingress",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_upstream_server_response_latency_ms_count{controller_class=~\"$controller_class\", resource_namespace=~\"$namespace\", ingress=~\"$ingress\", code=~\"^(3|4|5).*\"}[2m]))\n",
     "legendFormat": "{{`{{ ingress }}`}}"
    }
   ]
  },
  {
   "title": "Latency (per ingress)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_upstream_server_response_latency_ms_bucket{status!=\"404\",status!=\"500\", controller_class=~\"$controller_class\", ingress=~\"$ingress\", resource_namespace=~\"$namespace\", controller_pod=~\"$pod\"}[5m])) by (le, ingress))",
     "legendFormat": "p99 {{`{{ ingress }}`}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_upstream_server_response_latency_ms_bucket{status!=\"404\",status!=\"500\", controller_class=~\"$controller_class\", ingress=~\"$ingress\", resource_namespace=~\"$namespace\", controller_pod=~\"$pod\"}[5m])) by (le, ingress))",
     "legendFormat": "p95 {{`{{ ingress }}`}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{status!=\"404\",status!=\"500\", controller_class=~\"$controller_class\", ingress=~\"$ingress\", resource_namespace=~\"$namespace\", controller_pod=~\"$pod\"}[5m])) by (le, ingress))",
     "legendFormat": "p90 {{`{{ ingress }}`}}"
    }
   ]
  }
 ]
}