# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agi_med_protos/Text.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'agi_med_protos/Text.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from agi_med_protos import commons_pb2 as agi__med__protos_dot_commons__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61gi_med_protos/Text.proto\x12\x11\x61gi.med.protos.v1\x1a\x1c\x61gi_med_protos/commons.proto\"F\n\x0bTextRequest\x12\x0c\n\x04Text\x18\x01 \x01(\t\x12)\n\x04\x43hat\x18\x02 \x01(\x0b\x32\x1b.agi.med.protos.v1.ChatItem\"\x1c\n\x0cTextResponse\x12\x0c\n\x04Text\x18\x01 \x01(\t2Z\n\x04Text\x12R\n\x0fGetTextResponse\x12\x1e.agi.med.protos.v1.TextRequest\x1a\x1f.agi.med.protos.v1.TextResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agi_med_protos.Text_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEXTREQUEST']._serialized_start=78
  _globals['_TEXTREQUEST']._serialized_end=148
  _globals['_TEXTRESPONSE']._serialized_start=150
  _globals['_TEXTRESPONSE']._serialized_end=178
  _globals['_TEXT']._serialized_start=180
  _globals['_TEXT']._serialized_end=270
# @@protoc_insertion_point(module_scope)
