# Generated by Django 3.0.5 on 2022-03-15 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_rds_iam_auth', '0054_auto_20220315_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='parent_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_tenant', to='django_rds_iam_auth.Tenant'),
        ),
    ]
