# coding: utf-8

"""
    Netpicker API (Celery 5.5.3)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.4.23.3109
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from netpicker_client.models.access_token_read import AccessTokenRead

class TestAccessTokenRead(unittest.TestCase):
    """AccessTokenRead unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccessTokenRead:
        """Test AccessTokenRead
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccessTokenRead`
        """
        model = AccessTokenRead()
        if include_optional:
            return AccessTokenRead(
                id = '',
                user_id = '',
                token = '',
                expires = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                revoked = True,
                scopes = [
                    ''
                    ],
                claims = None
            )
        else:
            return AccessTokenRead(
                id = '',
                token = '',
                expires = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                scopes = [
                    ''
                    ],
        )
        """

    def testAccessTokenRead(self):
        """Test AccessTokenRead"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
