# coding: utf-8

"""
    Netpicker API (Celery 5.5.3)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.4.23.3109
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from netpicker_client.models.body_create_api_token_api_v1_auth_api_token_post import BodyCreateApiTokenApiV1AuthApiTokenPost

class TestBodyCreateApiTokenApiV1AuthApiTokenPost(unittest.TestCase):
    """BodyCreateApiTokenApiV1AuthApiTokenPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BodyCreateApiTokenApiV1AuthApiTokenPost:
        """Test BodyCreateApiTokenApiV1AuthApiTokenPost
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BodyCreateApiTokenApiV1AuthApiTokenPost`
        """
        model = BodyCreateApiTokenApiV1AuthApiTokenPost()
        if include_optional:
            return BodyCreateApiTokenApiV1AuthApiTokenPost(
                claims = {
                    'key' : [
                        null
                        ]
                    },
                scopes = [
                    ''
                    ]
            )
        else:
            return BodyCreateApiTokenApiV1AuthApiTokenPost(
        )
        """

    def testBodyCreateApiTokenApiV1AuthApiTokenPost(self):
        """Test BodyCreateApiTokenApiV1AuthApiTokenPost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
