# coding: utf-8

"""
    Netpicker API (Celery 5.5.3)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.4.23.3109
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from netpicker_client.models.code_snippet import CodeSnippet

class TestCodeSnippet(unittest.TestCase):
    """CodeSnippet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CodeSnippet:
        """Test CodeSnippet
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CodeSnippet`
        """
        model = CodeSnippet()
        if include_optional:
            return CodeSnippet(
                range = netpicker_client.models.line_range.LineRange(
                    start = 56, 
                    end = 56, ),
                code = ''
            )
        else:
            return CodeSnippet(
                code = '',
        )
        """

    def testCodeSnippet(self):
        """Test CodeSnippet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
