# coding: utf-8

"""
    Netpicker API (Celery 5.5.3)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.4.23.3109
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from netpicker_client.models.page_t_customized_job_exec_log_report import PageTCustomizedJobExecLogReport

class TestPageTCustomizedJobExecLogReport(unittest.TestCase):
    """PageTCustomizedJobExecLogReport unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PageTCustomizedJobExecLogReport:
        """Test PageTCustomizedJobExecLogReport
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PageTCustomizedJobExecLogReport`
        """
        model = PageTCustomizedJobExecLogReport()
        if include_optional:
            return PageTCustomizedJobExecLogReport(
                items = [
                    netpicker_client.models.job_exec_log_report.JobExecLogReport(
                        id = '', 
                        job_name = '', 
                        job_id = '', 
                        initiator = '', 
                        variables = {
                            'key' : null
                            }, 
                        return_value = null, 
                        exec_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        exec_ns = 56, 
                        log = '', 
                        ipaddress = '', 
                        name = '', 
                        status = 'SUCCESS', 
                        created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                total = 0.0,
                page = 1.0,
                size = 1.0,
                pages = 0.0
            )
        else:
            return PageTCustomizedJobExecLogReport(
                items = [
                    netpicker_client.models.job_exec_log_report.JobExecLogReport(
                        id = '', 
                        job_name = '', 
                        job_id = '', 
                        initiator = '', 
                        variables = {
                            'key' : null
                            }, 
                        return_value = null, 
                        exec_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        exec_ns = 56, 
                        log = '', 
                        ipaddress = '', 
                        name = '', 
                        status = 'SUCCESS', 
                        created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                total = 0.0,
                page = 1.0,
                size = 1.0,
        )
        """

    def testPageTCustomizedJobExecLogReport(self):
        """Test PageTCustomizedJobExecLogReport"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
