# coding: utf-8

"""
    Netpicker API (Celery 5.5.3)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.4.23.3109
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from netpicker_client.models.signal_info import SignalInfo

class TestSignalInfo(unittest.TestCase):
    """SignalInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SignalInfo:
        """Test SignalInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SignalInfo`
        """
        model = SignalInfo()
        if include_optional:
            return SignalInfo(
                name = '',
                providing_args = [
                    ''
                    ],
                receivers = [
                    netpicker_client.models.receiver_info.ReceiverInfo(
                        name = '', 
                        module = '', 
                        is_conditional = True, 
                        conditions = netpicker_client.models.conditions.conditions(), 
                        arguments = netpicker_client.models.arguments.arguments(), )
                    ]
            )
        else:
            return SignalInfo(
                name = '',
                providing_args = [
                    ''
                    ],
                receivers = [
                    netpicker_client.models.receiver_info.ReceiverInfo(
                        name = '', 
                        module = '', 
                        is_conditional = True, 
                        conditions = netpicker_client.models.conditions.conditions(), 
                        arguments = netpicker_client.models.arguments.arguments(), )
                    ],
        )
        """

    def testSignalInfo(self):
        """Test SignalInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
