# coding: utf-8

"""
    Netpicker API (Celery 5.5.3)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.4.23.3109
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from netpicker_client.models.body_store_job_api_v1_automation_tenant_job_post import BodyStoreJobApiV1AutomationTenantJobPost

class TestBodyStoreJobApiV1AutomationTenantJobPost(unittest.TestCase):
    """BodyStoreJobApiV1AutomationTenantJobPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BodyStoreJobApiV1AutomationTenantJobPost:
        """Test BodyStoreJobApiV1AutomationTenantJobPost
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BodyStoreJobApiV1AutomationTenantJobPost`
        """
        model = BodyStoreJobApiV1AutomationTenantJobPost()
        if include_optional:
            return BodyStoreJobApiV1AutomationTenantJobPost(
                name = '',
                sources = {
                    'key' : ''
                    }
            )
        else:
            return BodyStoreJobApiV1AutomationTenantJobPost(
                name = '',
                sources = {
                    'key' : ''
                    },
        )
        """

    def testBodyStoreJobApiV1AutomationTenantJobPost(self):
        """Test BodyStoreJobApiV1AutomationTenantJobPost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
