# Generated by Django 3.2.6 on 2023-01-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rds_iam_auth', '0061_auto_20230103_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_otp_required',
            field=models.BooleanField(default=False, verbose_name='Connect with OTP'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_c2c_required',
            field=models.BooleanField(default=False, verbose_name='c2c device type'),
        ),
    ]
