# coding: utf-8

"""
    Platform API Documentation

    Combined API documentation for all platform services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from do_sdk_platform.models.nucleus_api_create_database_view200_response import NucleusApiCreateDatabaseView200Response

class TestNucleusApiCreateDatabaseView200Response(unittest.TestCase):
    """NucleusApiCreateDatabaseView200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NucleusApiCreateDatabaseView200Response:
        """Test NucleusApiCreateDatabaseView200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NucleusApiCreateDatabaseView200Response`
        """
        model = NucleusApiCreateDatabaseView200Response()
        if include_optional:
            return NucleusApiCreateDatabaseView200Response(
                data = do_sdk_platform.models.database_view.DatabaseView(
                    id = '', 
                    database_id = '', 
                    name = '', 
                    filter = null, 
                    row_sort = [
                        do_sdk_platform.models.row_sort_inner.RowSort_inner(
                            column_id = '', 
                            sort = 'asc', )
                        ], 
                    column_selection = do_sdk_platform.models.column_selection.ColumnSelection(
                        include = [
                            ''
                            ], 
                        exclude = [
                            ''
                            ], ), )
            )
        else:
            return NucleusApiCreateDatabaseView200Response(
                data = do_sdk_platform.models.database_view.DatabaseView(
                    id = '', 
                    database_id = '', 
                    name = '', 
                    filter = null, 
                    row_sort = [
                        do_sdk_platform.models.row_sort_inner.RowSort_inner(
                            column_id = '', 
                            sort = 'asc', )
                        ], 
                    column_selection = do_sdk_platform.models.column_selection.ColumnSelection(
                        include = [
                            ''
                            ], 
                        exclude = [
                            ''
                            ], ), ),
        )
        """

    def testNucleusApiCreateDatabaseView200Response(self):
        """Test NucleusApiCreateDatabaseView200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
