# coding: utf-8

"""
    Platform API Documentation

    Combined API documentation for all platform services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from do_sdk_platform.models.api_list_clusters200_response_data_inner import ApiListClusters200ResponseDataInner

class TestApiListClusters200ResponseDataInner(unittest.TestCase):
    """ApiListClusters200ResponseDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiListClusters200ResponseDataInner:
        """Test ApiListClusters200ResponseDataInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiListClusters200ResponseDataInner`
        """
        model = ApiListClusters200ResponseDataInner()
        if include_optional:
            return ApiListClusters200ResponseDataInner(
                id = '',
                type = '',
                attributes = do_sdk_platform.models.cluster_dto.ClusterDto(
                    drn = '', 
                    name = '', )
            )
        else:
            return ApiListClusters200ResponseDataInner(
                id = '',
                type = '',
                attributes = do_sdk_platform.models.cluster_dto.ClusterDto(
                    drn = '', 
                    name = '', ),
        )
        """

    def testApiListClusters200ResponseDataInner(self):
        """Test ApiListClusters200ResponseDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
