# coding: utf-8

"""
    Platform API Documentation

    Combined API documentation for all platform services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from do_sdk_platform.models.function_manifest_interface_schema_dto_function_versions_inner import FunctionManifestInterfaceSchemaDtoFunctionVersionsInner

class TestFunctionManifestInterfaceSchemaDtoFunctionVersionsInner(unittest.TestCase):
    """FunctionManifestInterfaceSchemaDtoFunctionVersionsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FunctionManifestInterfaceSchemaDtoFunctionVersionsInner:
        """Test FunctionManifestInterfaceSchemaDtoFunctionVersionsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FunctionManifestInterfaceSchemaDtoFunctionVersionsInner`
        """
        model = FunctionManifestInterfaceSchemaDtoFunctionVersionsInner()
        if include_optional:
            return FunctionManifestInterfaceSchemaDtoFunctionVersionsInner(
                id = '',
                version = '',
                enabled = True,
                manifest_body = None,
                billing_code = ''
            )
        else:
            return FunctionManifestInterfaceSchemaDtoFunctionVersionsInner(
                id = '',
                version = '',
                enabled = True,
                manifest_body = None,
        )
        """

    def testFunctionManifestInterfaceSchemaDtoFunctionVersionsInner(self):
        """Test FunctionManifestInterfaceSchemaDtoFunctionVersionsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
