# coding: utf-8

"""
    Platform API Documentation

    Combined API documentation for all platform services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from do_sdk_platform.models.blueprint_object import BlueprintObject

class TestBlueprintObject(unittest.TestCase):
    """BlueprintObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BlueprintObject:
        """Test BlueprintObject
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BlueprintObject`
        """
        model = BlueprintObject()
        if include_optional:
            return BlueprintObject(
                type_id = '',
                use_case_ids = [
                    ''
                    ],
                use_case_names = [
                    ''
                    ],
                icon = [
                    ''
                    ],
                id = '',
                enabled = True,
                version = '',
                name = '',
                summary = '',
                description = None,
                license = do_sdk_platform.models.described_external_entity_object.DescribedExternalEntityObject(
                    name = '', 
                    url = '', 
                    description = '', ),
                resource_links = [
                    do_sdk_platform.models.external_entity_object.ExternalEntityObject(
                        name = '', 
                        url = '', )
                    ],
                publication_references = [
                    do_sdk_platform.models.external_entity_object.ExternalEntityObject(
                        name = '', 
                        url = '', )
                    ],
                authors = [
                    do_sdk_platform.models.external_entity_object.ExternalEntityObject(
                        name = '', 
                        url = '', )
                    ],
                created = '',
                variant_tags = [
                    ''
                    ],
                node_types = [
                    do_sdk_platform.models.node_type_response.NodeTypeResponse(
                        id = '', 
                        name = '', 
                        summary = '', 
                        entry_points = [
                            do_sdk_platform.models.entry_point_reference_object.EntryPointReferenceObject(
                                id = '', 
                                name = '', 
                                port = 1.337, 
                                protocol = '', 
                                is_exposed = True, )
                            ], 
                        image_location = '', 
                        home_data_location = '', 
                        fixed_resources = True, 
                        shared_drive_required = True, 
                        notebooks = [
                            do_sdk_platform.models.catalog_item_reference_object.CatalogItemReferenceObject(
                                id = '', 
                                version = '', 
                                other_item_version = '', 
                                variant_tags = [
                                    ''
                                    ], )
                            ], 
                        operating_system = null, 
                        applications = [
                            do_sdk_platform.models.catalog_item_reference_object.CatalogItemReferenceObject(
                                id = '', 
                                version = '', 
                                other_item_version = '', 
                                variant_tags = [
                                    ''
                                    ], )
                            ], 
                        requirements = null, )
                    ],
                applications = [
                    do_sdk_platform.models.application_response.ApplicationResponse(
                        authors = [
                            do_sdk_platform.models.external_entity_object.ExternalEntityObject(
                                name = '', 
                                url = '', )
                            ], 
                        created = '', 
                        description = '', 
                        icon = '', 
                        id = '', 
                        license = null, 
                        name = '', 
                        summary = '', 
                        publication_references = [
                            do_sdk_platform.models.external_entity_object.ExternalEntityObject(
                                name = '', 
                                url = '', )
                            ], 
                        requirements = null, 
                        resource_links = [
                            
                            ], 
                        version = '', 
                        type_id = '', 
                        use_case_ids = [
                            ''
                            ], 
                        use_case_names = [
                            ''
                            ], 
                        variant_tags = [
                            ''
                            ], )
                    ]
            )
        else:
            return BlueprintObject(
                type_id = '',
                use_case_ids = [
                    ''
                    ],
                use_case_names = [
                    ''
                    ],
                icon = [
                    ''
                    ],
                id = '',
                enabled = True,
                version = '',
                name = '',
                summary = '',
                description = None,
                license = do_sdk_platform.models.described_external_entity_object.DescribedExternalEntityObject(
                    name = '', 
                    url = '', 
                    description = '', ),
                resource_links = [
                    do_sdk_platform.models.external_entity_object.ExternalEntityObject(
                        name = '', 
                        url = '', )
                    ],
                publication_references = [
                    do_sdk_platform.models.external_entity_object.ExternalEntityObject(
                        name = '', 
                        url = '', )
                    ],
                authors = [
                    do_sdk_platform.models.external_entity_object.ExternalEntityObject(
                        name = '', 
                        url = '', )
                    ],
                created = '',
                variant_tags = [
                    ''
                    ],
                node_types = [
                    do_sdk_platform.models.node_type_response.NodeTypeResponse(
                        id = '', 
                        name = '', 
                        summary = '', 
                        entry_points = [
                            do_sdk_platform.models.entry_point_reference_object.EntryPointReferenceObject(
                                id = '', 
                                name = '', 
                                port = 1.337, 
                                protocol = '', 
                                is_exposed = True, )
                            ], 
                        image_location = '', 
                        home_data_location = '', 
                        fixed_resources = True, 
                        shared_drive_required = True, 
                        notebooks = [
                            do_sdk_platform.models.catalog_item_reference_object.CatalogItemReferenceObject(
                                id = '', 
                                version = '', 
                                other_item_version = '', 
                                variant_tags = [
                                    ''
                                    ], )
                            ], 
                        operating_system = null, 
                        applications = [
                            do_sdk_platform.models.catalog_item_reference_object.CatalogItemReferenceObject(
                                id = '', 
                                version = '', 
                                other_item_version = '', 
                                variant_tags = [
                                    ''
                                    ], )
                            ], 
                        requirements = null, )
                    ],
                applications = [
                    do_sdk_platform.models.application_response.ApplicationResponse(
                        authors = [
                            do_sdk_platform.models.external_entity_object.ExternalEntityObject(
                                name = '', 
                                url = '', )
                            ], 
                        created = '', 
                        description = '', 
                        icon = '', 
                        id = '', 
                        license = null, 
                        name = '', 
                        summary = '', 
                        publication_references = [
                            do_sdk_platform.models.external_entity_object.ExternalEntityObject(
                                name = '', 
                                url = '', )
                            ], 
                        requirements = null, 
                        resource_links = [
                            
                            ], 
                        version = '', 
                        type_id = '', 
                        use_case_ids = [
                            ''
                            ], 
                        use_case_names = [
                            ''
                            ], 
                        variant_tags = [
                            ''
                            ], )
                    ],
        )
        """

    def testBlueprintObject(self):
        """Test BlueprintObject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
