# This file will contain all the workbook names and the sheets within that contains
# configuration data. It is very important that the filenames provided for configuration
# match the filenames listed below.

# **IMPORTANT** - Do not change the existing IDs below as it is used in other scripts for
# identifying the correct sheet and script

import os
rootdir = os.environ['CFGAUTOROOT']

# Workbooks Parent Path
SOURCE_DIR_PATH = rootdir + "/workbooks/source/"
PRCS_DIR_PATH = rootdir + "/workbooks/formatted/"
RESULTS_DIR_PATH = rootdir + "/results/"
VIDEO_DIR_PATH = rootdir + "/videos/"


# GL Basic Configurations
GL_WORKBOOK = "ERP/GL/ERP GeneralLedger ConfigurationGuide.xlsx"
LEGAL_ENTITY_SHEET = "LEGAL ENTITY"
LEGAL_ENTITY_REG = "LEGAL ENTITY REGISTRATIONS"
LEGAL_REPORTING_UNIT = "LEGAL REPORTING UNIT"
BU = "GL_BUSINESS UNIT"
LOCATION = "LOCATION"
LEDGER = "LEDGERS"
CURRENCY = "CURRENCY"
CHART_OF_ACCOUNT = "CHART OF ACCOUNT"
FUND = "SEGMENT1"
COST_CENTER = "SEGMENT2"
ACCOUNT = "SEGMENT3"
ACTIVITY = "SEGMENT4"
INTERFUND = "SEGMENT5"
FUTURE1 = "SEGMENT6"
FUTURE2 = "SEGMENT7"
DEPLOYFLEXFIELDS = "CHART OF ACCOUNT"
JRNL_CATEGORIES = "JOURNAL CATEGORIES"
JRNL_SOURCES = "JOURNAL SOURCES"
LEDGERSETS = "LEDGER SET"
MANAGE_CONV_RATES_TYPES = "CONVERSION RATE TYPES"
ACC_CALENDAR = "ACCOUNTING CALENDARS"
DATA_ACCESS_SET = "DATA ACCESS SET"
IC_SUPPLIER_ASSOCIATION = "CUSTOMER SUPPLIER ASSOCATION"
MANAGE_ADD_INTERCOMPANY_CLEARING = "Intercompany Clearing Options"
MANAGE_IC_TRANSACTIONTYPES = "Intercompany Transaction Types"
MANAGE_IC_ORGANIZATIONS = 'Intercompany Organizations'
ASSIGN_LEGAL_ENTITY = 'ASSIGN LEGAL ENTITIES'
ASSIGN_BAL_SGMT_VALUE_LE = 'ASSIGN BALANCING SGMNT VALUE'
REVIEW_SUBMIT_ACCOUNTING = 'REVIEW & SUBMIT ACCOUNTING'
MANAGE_AUTO_POST_SETS = "AUTOPOST CRITERIA SETS"
MANAGE_ACCOUNTING_METHOD = 'ACCOUNTING METHOD'
MANAGE_SECONDARY_LEDGERS = 'SECONDARY LEDGER'
MANAGE_JRNL_REVERSALSETS = 'JOURNAL REVERSAL CRITERIA SETS'
MANAGE_GL_DESCRIPTIVE_FLEXFIELDS = 'GL DESCRIPTIVE FLEXFIELDS'
GL_DFF_VALUES = 'GL DFF VALUES'
# SPECIFYLEDGEROPTION = 'LEDGERS'

# Accounts Payable
AP_WORKBOOK = '/ERP/AP/ERP AccountsPayable ConfigurationGuide.xlsx'
COMMON_OPTIONS = 'COMMON OPTIONS'
INVOICE_OPTIONS = 'INVOICE OPTIONS'
PAYMENT_OPTIONS = 'PAYMENT OPTIONS'
PAY_GROUP = 'PAY GROUP'
PAYMENT_TERMS = 'PAYMENT TERMS'
DISTRIBUTION_SETS = 'DISTRIBUTION SETS'
INVOICE_TOLERANCES = 'INVOICE TOLERANCES'
INVOICE_HOLDS_RELEASES = 'INVOICE HOLDS AND RELEASES'
AGING_PERIODS = 'AGING PERIODS'
PAYABLES_CALENDAR = 'PAYABLES CALENDAR'
PAYABLES_DESCRIPTIVE_FLEXFIELD = 'PAYABLES DESCRIPTIVE FLEXFIELD'
DFF_VALUES = 'PAYABLES DFF VALUES'
PAYABLES_DOC_SEQUENCE = 'PAYABLES DOCUMENT SEQUENCE'
SPECIFY_SUPPLIER_NUMBERING = 'SPECIFY SUPPLIER NUMBERING'
PAYMENT_METHODS = 'PAYMENT METHODS'
PAYMENT_METHOD_DEFAULTING_RULE = 'PAYMENT METHOD DEFAULTING RULE'
FORMATS = 'FORMATS'
PAYMENT_PROCESS_PROFILES = 'PAYMENT PROCESS PROFILES'
DISBURSEMENT_SYSTEM_OPTIONS = 'DISBURSEMENT SYSTEM OPTIONS'
PAYMENT_SYSTEM = 'PAYMENT SYSTEM'
TRANSMISSION_CONFIG = 'TRANSMISSION CONFIGURATION'
PAYABLES_PROFILE_OPTIONS = 'PAYABLES PROFILE OPTIONS'
PAYMENT_PROCESS_REQ_TEMPLATE = 'PAYMENT PROCESS REQUEST TEMPLAT'

# Expenses
EXP_WORKBOOK = 'ERP/Expenses/ERP Expense ConfigurationGuide.xlsx'
EXP_FIELDS_BY_CATEGORY = 'EXPENSE FIELDS BY CATEGORY'
EXP_TEMP = 'ER TEMPLATE RECRUITING'
TAX_FIELDS = 'TAX FIELDS'
EXP_SYS_OPTIONS = 'EXPENSE SYSTEM OPTIONS'
ACCM_EXP_POLICY = 'ACCOMODATION EXPENSE POLICY'
ENTERTAINMENT_POLICY = 'ENTERTAINMENT POLICY'
MEALS_EXP_POLICY = 'MEALS EXPENSE POLICY'
MILEAGE_POLICY = 'MILEAGE POLICY'
MISC_EXP_POLICY = 'MISCELLENOUS EXPENSE POLICY'
CASH_ADVN_POLICY = 'CASH ADVANCE POLICIES'
RECEIPT_NOTIFI_RULE = 'RECEIPT AND NOTIFICATION RULE'
CONV_RATES_POLICY = 'CONVERSION RATES AND POLICIES'
EXP_PROFILE_VALUES = 'EXPENSE PROFILE VALUES'
EXP_PAYMENT_METHOD_DEFAULTING_RULE = 'PAYMENT METHOD DEFAULTING RULES'
AUDIT_SELC_RULE = 'AUDIT SELECTION RULES'
AUDIT_RULES_BY_EXP_TYPE = 'AUDIT RULES BY EXP TYPE'
AUDIT_RECEIPT_RULE = 'AUDIT AND RECEIPT RULE'
EXP_DFF = 'EXPENSE DESCRIPTIVE FLEXFIELD'
EXP_DFF_VALUES = 'EXPENSE DFF VALUES'
DFF_EXPENSE_REPORT = 'DFF EXPENSE REPORT'

# CM
CM_WORKBOOK = 'ERP/CM/ERP CashManagement ConfigurationGuide.xlsx'
BANKS = 'BANKS'
BANK_BRANCHES = 'BANK BRANCHES'
BANK_ACCOUNT = 'BANK ACCOUNT'
BANK_STMT_TRNSCTN_CODE='TRANSACTION CODES'
PARSE_RULE_SETS = 'PARSE RULE SETS'
CASH_TRANS_TYPE_MAPPING = 'CASH TRANSACTION TYPE MAPPING'
BANK_STATEMENT_REC_TOLERANCE_RULE = 'RECONCILIATION TOLERANCE RULES'
BANK_STATEMENT_REC_MATCHING_RULE = 'RECONCILIATION MATCHING RULE'
REC_RULE_SETS = 'RECONCILIATION RULE SETS'

# FA
FA_WORKBOOK = 'ERP/FA/ERP FixedAssets ConfigurationGuide.xlsx'
MANAGE_FA_KEYFF = 'KEY FLEXFIELDS'
MANAGE_FA_KEYFF_VALUESETS = 'KEY FLEXFIELD VALUE SETS'
MANAGE_ASSET_KEYS = 'ASSET KEYS'
MANAGE_ASSET_LOCATION = 'ASSET LOCATIONS'
MANGE_SYSTEM_CONTROL = 'SYSTEM CONTROL'
MANGE_FISCAL_YEAR = 'FISCAL YEAR'
MANAGE_ASSET_CALENDARS = 'ASSET CALENDARS'
MANGE_PRORATE_CONV = 'PRORATE CONVENTION'
MANAGE_ASSET_BOOK = 'ASSET BOOK'
MANAGE_ASSET_CATEGORIES = 'ASSET CATEGORIES'
MANAGE_DFF = 'DESCRIPTIVE FLEXFIELD'
MANAGE_DFF_VALUES = 'DFF VALUES'
MANAGE_MAPPING_SETS = 'MAPPING SETS'
MANAGE_ACCOUNTING_RULE = 'ACCOUNT RULE'
MANAGE_JRNL_ENTRY_RULE = 'JOURNAL ENTRY RULE'
MANAGE_ACCOUNT_METHOD = 'ACCOUNTING METHOD'
MANAGE_CATEGORY_ALIASES = 'CATEGORY ALIASES'
MANAGE_ASSETKEY_ALIASES = 'ASSET KEY ALIASES'
MANAGE_LOCATION_ALIASES = 'LOCATION ALIASES'
MANAGE_BONUS_RULE = 'BONUS RULE'
MANAGE_DEPRECIATION_CEILING = 'DEPRECIATION CEILING'

# AR
AR_WORKBOOK = 'ERP/AR/ERP AccountsReceivable ConfigurationGuide.xlsx'
RECEIVABLES_SYS_OPT = 'RECEIVABLES SYSTEM OPTION'
RECEIVABLES_ACTIVITY = 'CREATE RECEIVABLES ACTIVITY'
TRANS_TYPES = 'TRANSACTION TYPES'
TRANS_SOURCE = 'MANAGE TRANSACTION SOURCE'
STAN_MEMO_LINES = 'MANAGE STANDARD MEMO LINES'
AUTO_ACC_RULE = 'CREATE AUTO ACCOUNTING RULE'
PYMNT_TERMS = 'MANAGE RECEIVABLES PAYMENT TERM'
REMIT_TO_ADDRESSES = 'MANAGE REMIT TO ADDRESSES'
APPROVAL_LIMITS = 'MANAGE APPROVAL LIMITS'
STATEMENT_CYCLE = 'MANAGE STATEMENT CYCLE'
RECEIVABLES_DSTRBTN = 'CREATE RECEIVABLES DISTRIBUTION'
AR_DFF_VALUES = 'RECEIVABLES DFF VALUES'
RECEIVABLE_DFF = 'RECEIVABLE DESCRIPTIVE FLEXFILD'
RECEIPT_CLASSES_AND_METHODS = 'MANAGE RECEIPT CLASSES & METHOD'
RECEIPT_SOURCE = 'RECEIPT SOURCE'
AUTOCASH_RULE_SET = 'AUTOCASH RULE SET'
AUTOMATCH_RULE_SET = 'CREATE AUTOMATCH RULE SET'
APP_EXCEPTION_RULES= 'APPLICATION EXCEPTION RULES'
REVENUE_SCHDLNG_RULES = 'REVENUE SCHEDULING RULES'
REVENUE_CONTINGENCIES = 'MANAGE REVENUE CONTINGENCIES'
RECEIVABLE_CUSTOMER_PROF = 'MNG RECEIVABLE CUSTOMER PROFILE'
TRADING_COMMUNITY_SOURCE = 'MANAGE TRADING COMMUNITY SOURCE'
# AR_ACCOUNTING_METHOD = 'ACCOUNTING METHOD'
# AR_ACCOUNT_RULE = 'ACCOUNT RULE'
RECEIVABLES_DOC_SEQ = 'MANAGE RECEIVABLES DOC SEQ'
AR_AGING_METHODS = 'MANAGE AGING METHODS'

# Talent Rating Model
HCM_TALENT_RATING_MODEL_WRKBK = "HCM/Talent/HCM_TALENT_RATING MODEL.xlsx"
PROFILE_COMPETENCIES_WRKBK = "HCM/Talent/Talent_Profile _ConfigurationGuide_DS Auto_profile Confi_V1.0..xlsx"
ITEM_CATALOG = "Item Catalog"

# Global HR Configuration
GHR_CONFIG_WRKBK = "HCM/GHR/HCM HR ConfigurationGuide.xlsx"
MANAGE_ADDRESS_FORMATS = 'MANAGE ADDRESS FORMAT'
ASSGN_LOOKUPS_SHEET = "WORK TERM AND ASG LOOKUPS"
MANAGE_ASSGN_STATUS = "MANAGE ASSIGNMENT STATUS"
MANAGE_PRSN_FORMATS = "MANAGE PERSON NAME FORMATS"
MANAGE_PRSN_NM_STYL = "MANAGE PERSON NAME STYLE"
BARGAINING_UNIT = "BARGAINING UNIT"
SALARY_BASIS = "SALARY BASIS"
MANAGE_DOCUMENT_TYPE = "DOCUMENT TYPES"
SENIORITY_DATE_RULES = "SENIORITY DATE RULES"
MANAGE_COMMON_LOOKUP = "MANAGE COMMON LOOKUP"
MANAGE_VALUE_SETS = "MANAGE VALUESETS"
MANAGE_EFF = "MANAGE EFF"
MANAGE_HR_DFF = "MANAGE DFF"
MANAGE_KFF = "MANAGE KFF"
HR_LEGAL_REPORTING_UNIT = "LEGAL REPORTING UNIT"
MANAGE_JOURNY_CONFIG = "MANAGE JOURNEY CONFIGURATION"
LEGAL_ADDRESS = "MANAGE LEGAL ADDRESSES"


# Enterprise Structures
GHR_ENTSTRUCT_CONFIG_WRKBK = "HCM/GHR/HCM EnterpriseStructure ConfigurationGuide.xlsx"
ENTERPRISE = "ENTERPRISE"
LDG = "LDG"
BUSINESS_UNIT = "BUSINESS UNIT"
REFERENCE_DATA_SET = "REFERENCE DATA SET"
LEGAL_ENTITY_HCM_INFORMATION = "LEGAL ENTITY HCM INFORMATION"


# PAYROLL
PAYROLL_ELEMENTS_CONFIG_WRKBK = "HCM/Payroll/HCM Payroll Elements Earnings ConfigurationGuide.xlsx"
PAYROLL_CONFIG_WRKBK = "HCM/Payroll/HCM Payroll TRU ConfigurationGuide.xlsx"
LEGAL_REPORTING_REGISTRATION = "LEGAL REPORTING REGISTRATION"
MANAGE_BANK = "MANAGE BANK"
MANAGE_BANK_BRANCHES = "MANAGE BANK BRANCHES"
MANAGE_BANK_ACCOUNTS = "MANAGE BANK ACCOUNTS"
STANDARD_EARNINGS="STANDARDEARN"
TIME_LABOUR="TIME&LABOR"
ABSENCE_ELEMENTS='ABSENCE'
ORGANIZATION_PAYMENT_METHODS = "ORGANIZATION PAYMENT METHODS"
CREATE_PAYMENT_SOURCE = "CREATE PAYMENT SOURCE"
PAYROLL_DEFINITIONS = "PAYROLL DEFINITIONS"
LEGAL_RPT_CALCULATION_FEDERAL = "LEGAL RPT CALCULATION FEDERAL"
LEGAL_RPT_CALCULATION_REGION = "LEGAL RPT CALCULATION REGION"
MANAGE_LEGAL_ENTITY_REGISTRATION = "MANAGE LEGAL ENTITY REGISTRATIO"
LEGAL_ENTITY_CALCULATION_FEDERA = "LEGAL ENTITY CALCULATION FEDERA"
LEGAL_ENTITY_CALCULATION_REGION = "LEGAL ENTITY CALCULATION REGION"
IMPUTED_EARNINGS = "IMPUTEDEARN"
SUPPLEMENTAL_EARNINGS = "SUPPLEMENTALEARN"
THIRD_PARTY_ORG = "THIRD PARTY ORG"
PAYROLL_DEDUCTIONS_WRKBK = "HCM/Payroll/HCM Payroll Elements Deductions ConfigurationGuide.xlsx"
VOLUNTRY_DEDUCTIONS = "VOLUNTARY DEDUCTIONS"
PRETAX_DEDUCTIONS = "PRETAX DEDUCTIONS"
PRETAX_401K_DEDUCTIONS = "PRETAX DEFERRED 401K"
PRETAX_403B_457_DEDUCTIONS = "PRETAX DEFERRED 403B 457"
OTHER_DEDUCTIONS = "HCM/Payroll/HCM Payroll Elements Others ConfigurationGuide.xlsx"
EMPLOYER_LIABILITY = "EMPLOYER LIABILIT"
NONPAYROLL_ELEMENTS = "NONPAYROLL PAYMENT"
COST_ALLOCATION_FLEX_FIELDS = "HCM/Payroll/HCM Payroll CostAllocations Flexfield ConfigurationGuide.xlsx"
MANAGE_STRUCTURE = "COST ALLOCATION CODE"
MANAGE_STRUCTURE_INST = "COST ALLOCATIONS INSTANCE"
PAYROLL_DFRD_BLNCE_FEEDS = "HCM/Payroll/HCM Payroll DeferredorCustomBalanceFeeds ConfigurationGuide.xlsx"
DFRD_BLNCE = "DEFERRED BALANCE"
DFRD_CSTM_BLNCE = "CUSTOM BALANCE"
CSTM_DMSN = "CUSTOM DIMENSION"
CSTM_BLNC_FDS = "CUSTOM BALANC FEEDS"

#Payroll - SLA Setup

PAYROLL_SLA_CONFIG_WB = "HCM/Payroll/HCM Payroll SLA ConfigurationGuide.xlsx"
MAN_ACC_RULES = "MANAGE ACCOUNT RULES"
MAN_SBLDGR_JRNL_ENT = "MANAGE SUBLEDGER JOURNAL ENTRY"
MAN_ACC_MTHDS = "MANAGE ACCOUNTING METHODS"

# BENEFITS
BENEFITS_CONFIG_WRKBK = "HCM/Benefits/HCM Ben Configuration Workbook.xlsx"
BENEFIT_RELATIONSHIP = "BENEFIT RELATIONSHIP"
LIFEEVENTS_DATACHANGES = "BENEFIT LIFE EVENT DATA CHNGS"
LIFEEVENTS = "LIFE EVENTS"
DERIVEDFACTORS_AGE = "DERIVED FACTORS AGE"
PROGRAM_PLANYEARS = "PROGRAM OR PLAN YEARS"
PLAN_TYPES = "PLAN TYPES"
CONFIG_PLANTYPE_GROUPING_DISPLAY = "CONFIG PLANTYPE GROUPING DSPLY"
BENEFIT_OPTIONS = "BENEFIT OPTIONS"
BASIC_PLAN_DETAILS = "PLAN BASIC DETAILS"
DERIVEDFACTORS_COMPENSATION = "DERIVED FACTORS CMPSNTN"
DERIVEDFACTORS_LOS = "DERIVED FACTORS LOS"
DERIVEDFACTORS_AGEANDSERVICE = "DERIVED FACTORS AGE&SERVICE"
ENROLL_AUTH = "ENROLMENT AUTHORIZATION"
DERIVEDFACTORS_HOURSWORKED = "DERIVED FACTORS HOURSWORKED"
DERIVEDFACTORS_FTE = "DERIVED FACTORS FTE"
BENEFIT_BALANCES = "BENEFITS BALANCE"
USR_DEF_CRITERIA = "USER DEFINED CRITERIA"
BENEFIT_GROUP = "BENEFIT GROUPS"
SELF_SER_CONFIG = "SELF SERVICE CONFIGURATION"
BASIC_PROGRAM_DETAILS = "PROGRAM BASIC DETAILS"
BENEFIT_PROGRAM_ENROLLMENT = "PROGRAM ENROLLMENT GENERAL"
BENEFIT_PROGRAM_DESIGNATION = "BENEFIT PROGRAM DESIGNATIONS"
BENEFIT_PRGM_DOC_UPLOAD = "BENEFIT PROGRAM DOCUMENT UPLDS"
BENEFIT_PRGM_CERT_UPLOAD = "BENEFIT PLAN CERTIFICATIONS"
BENEFIT_RATES = "STANDARD RATES"
BENEFIT_COVERAGE = "COVERAGES"
VARIABLE_COVERAGE = "VARIABLE COVERAGES"
VARIABLE_RATE = "VARIABLE RATES"

# PPM & PFC
PPM_PFC_CONFIG_WRKBK = "ERP/PPM/ERP PPM ProjectFoundationandCosting ConfigurationGuide.xlsx"
REV_CAT = "REVENUE CATEGORY"
EXP_CAT = "EXPENDITURE CATEGORY"
EXP_TYP = "EXPENDITURE TYPES"
SER_TYP = "SERVICE TYPES"
PRJ_STS = "PROJECT STATUSES"
PLN_BLN_BRK_STR = "PLANNING & BILLING BREAKDOWN ST"
PRJ_TYPS = "PROJECT TYPES"
BRDN_CST_BS_TYP = "BURDEN COST BASE TYPES"
BRDN_CST_BSS = "BURDEN COST BASES"
BRDN_CST_CDS = "BURDEN COST CODES"
PRJCT_TRANS_SOURCES = 'PROJECT TRANSACTION SOURCES'
BRDN_SCHDL = 'BURDEN SCHEDULE'
FIN_PLAN_TYPES = 'FINANCIAL PLAN TYPES'
MGE_BRDN_STR = 'BURDEN STRUCTURE'
MGE_CLASS_CTG = 'PROJECT CLASS CATEGORIES'
PRJ_TMPLT ='PROJECT TEMPLATES'
PRJ_PLAN_TYPES = 'PROJECT PLAN TYPES'

# PPM - Grants
PPM_GRNTS_CONFIG_WRKBK = "ERP/PPM/ERP PPM ProjectGrants ConfigurationGuide.xlsx"
RESOURCES = 'MANAGE RESOURCES'
VALUE_SETS = 'GRANT VALUE SETS'
GRANTS_DFF = 'GRANT DESCRIPTIVE FLEXFIELDS'
AUDIT_TYPES = 'MANAGE AUDIT TYPES'
AWARD_PURPOSE_CODES = 'MANAGE AWARD PURPOSE CODES'
AWARD_TYPES = 'MANAGE AWARD TYPES'
INS_CONTACT_OFFICIAL = 'MANAGE INSTIN CNTCT OFICIAL TYP'
KEYWORDS = 'MANAGE KEYWORDS'
GRANTS_REF_TYPES = 'MANAGE GRANTS REFERENCE TYPES'
ASSIST_LISTING_NUMBER = 'MANAGE ASSISTANCE LISTING NUMBR'
GRANTS_PERSONNEL = 'MANAGE GRANTS PERSONNEL'
SPONSORS = 'MANAGE SPONSORS'
FUND_SOURCES = 'MANAGE FUNDING SOURCES'
INSTITUTIONS = 'MANAGE INSTITUTIONS'
GRANTS_MANAGEMENT_BU_IMPL_OPTIONS = 'MANAGE GRANTS MANAGEMENT BUSINE'
AWARD_TEMPLATES = 'MANAGE AWARD TEMPLATES'

# PPM - Organization
PPM_ORG_CONFIG_WRKBK = 'ERP/PPM/ERP PPM ProjectOrganization ConfigurationGuide.xlsx'
PRJ_UNIT_ORG= "PROJECT UNIT ORGANIZATIONS"
PRJ_UNIT_OPTS= "PROJECT UNIT OPTIONS"
PRJ_UNIT_SETS_ASSIGNMTS= "PROJECT UNIT SET ASSIGNMENTS"
ORG_CLS_HIERARCHY= "ORG. CLASSIFICATION & HIERARCHY"
PRJ_ORG_CLASSIFICATIONS= "PROJECT ORG CLASSIFICATIONS"
PRJ_ACC_BU_FN= "PROJECT ACCOUNTING BU FUNCTION"

# PPM - Billing
PPM_BILLING_CONFIG_WRKBK = "ERP/PPM/ERP PPM ProjectBilling ConfigurationGuide.xlsx"
CONTRACT_TYPES = "MANAGE CONTRACT TYPES"
SPCFY_CSTMR_CNTRCT_MNGMNT_BSNSS_FNCTN_PRPRTS = "SPECIFY CUSTOMER CONTRACT MNGMT"
EVENT_TYPES = "MANAGE EVENT TYPES"
INV_FORMATS = "MANAGE INVOICE FORMATS"

# Time & Labor
HCM_TIME_AND_LABOR_WRKBK = "HCM/TimeandLabor/HCM T&L ConfigurationGuide.xlsx"
REPEATING_TIME_PERIOD = "REPEATING TIME PERIOD"
TIME_CONSUMER_SETS = "TIME CONSUMER SETS"
TIME_CATEGORIES = "TIME CATEGORIES"
SINGLE_ATTRIBUTE_COMPONENTS = "SINGLE ATTRIBUTE COMPONENTS"
MULTIPLE_ATTRIBUTE_COMPONENT = "MULTIPLE ATTRIBUTE COMPONENT"
TIME_LAYOUT_SETS = "TIME LAYOUT SETS"
TIME_REPOSITORY_TEMP_TIME_ENT = "TIME REPOSITORY TEMP - TIME ENT"
TIME_REPOSITORY_TEMP_CALCULAT = "TIME REPOSITORY TEMP - CALCULAT"
TIME_REPOSITORY_RULES_TIME_EN = "TIME REPOSITORY RULES - TIME EN"
TIME_REPOSITORY_RULES_CALCULA = "TIME REPOSITORY RULES - CALCULA"
TIME_RULE_SETS = "TIME RULE SETS"
HCM_GROUPS = "HCM GROUPS"
WORKER_TIME_ENTRY_PROFILES = "WORKER TIME ENTRY PROFILES"
WORKER_TIME_PROCESSING_PROFILES = "WORKER TIME PROCESSING PROFILES"
MESSAGES = "MESSAGES"

# Absence
ABSENCE_CONFIG_WRKBK = "HCM/Absence/HCM Absence ConfigurationGuide.xlsx"
ABSENCE_REASONS = "ABSENCE REASONS"
ABSENCE_CATEGORIES = "ABSENCE CATEGORIES"
ABSENCE_TYPES = "ABSENCE TYPES"
ABSENCE_PLANS_ACCRUAL = "ABSENCE PLANS ACCRUAL"
RATE_DEFINITION = "RATE DEFINITION"
ABSENCE_CERTIFICATIONS = "ABSENCE CERTIFICATIONS"
ABSENCE_PLAN_QUALIFICATION = "ABSENCE PLAN QUALIFICATION"
ABSENCE_PLANS_NO_ENTITLEMENT = "ABSENCE PLANS NO ENTITLEMENT"

#Absence WorkSchedule
WORK_SCH_CONFIG = "HCM/Absence/HCM Absence WorkSchedules ConfigurationGuide.xlsx"
WORK_SHIFTS = "ABSENCE WORK SHIFTS"
WORK_WRKDAY_PATTERN ="ABSENCE WORK WORKDAY PATTERN"
WRK_SCHEDULES = "ABSENCE WORK SCHEDULES"

# Talent - Onboarding
ONBOARDING_CONFIG_WRKBK = "HCM/Talent-Onboarding/Talent Onboard ConfigurationGuide.xlsx"
CHECKLIST_STEP = "CHECKLIST STEP"
CHECKLIST_PROCESS= "CHECKLIST PROCESS"
CHECKLIST_TASK = "CHECKLIST TASK"

# Talent - Recruiting
Recruiting_CONFIG_WRKBK = "HCM/Talent-Recruiting/Talent Recruiting ConfigurationGuide.xlsx"
RECRUITING_MANAGEMENT = "RECRUITING MANAGEMENT"
SOURCES = "SOURCES"
QUESTION_LIBRARY = "QUESTIONS"
QUESTIONNAIRE_TEMPLATE = "QUESTIONNAIRE TEMPLATE"
QUESTIONNAIRE_REC = "QUESTIONNAIRE"

# Talent - Goal
GOAL_CONFIG_WRKBK = "HCM/Talent-Goals/Talent Goal ConfigurationGuide.xlsx"
GOAL_LIBRARY = "GOAL LIBRARY"
GOAL_PLAN = "GOAL PLAN"

# Talent - Management
MGMT_CONFIG_WRKBK = "HCM/Talent-Management/Talent CD&TR ConfigurationGuide.xlsx"
CAREER_DEV = "CAREER DEV"


# Talent-Performance
PERF_CONFIG_WRKBK = "HCM/Talent-Performance/Talent Performance ConfigurationGuide.xlsx"
RATING_MODEL_SHEET_NAME = "RATING MODEL"
QUESTIONS = "QUESTIONS"
REVIEW_PERIOD = "REVIEW PERIOD"
PERFORMANCE_DOCUMENT_TYPE = "PERFORMANCE DOCUMENT TYPE"
CHECK_IN_TEMPLATE = "CHECK-IN TEMPLATE"
FEEDBACK_TEMPLATE = "FEEDBACK TEMPLATE"
PERFORMANCE_ROLE = "PERFORMANCE ROLE"
QUES_TEMPLATES = "QUESTIONNAIRE TEMPLATE"
QUESTIONNARIE = "QUESTIONNAIRE"
PERFORMANCE_PROCESS_FLOW = "PERF PROCESS FLOW"
PERFORMANCE_TEMPLATE_SECTION = "PERF TEMPLATE SECTION"
PERFORMANCE_TEMPLATE = "Perf Template"

# Talent-Learning
LEARNINGS_CONFIG_WRKBK = "HCM/Talent-Learnings/Talent Learning ConfigurationGuide.xlsx"

CLASSROOM = "CLASSROOM"
LA_QUESTIONS = "QUESTIONS-LEARNINGEVAL(ILC)"
LA_QUESTIONNARIE_TEMP = "QT - LEARNING EVALUATIONS(ILC)"
LA_QUESTIONNARIE = "QUESTIONNAIRE - LE (ILC)"
LE_QUESTIONS = "QUESTIONS-LEARNING EVALUATIONS"
LE_QUES_TEMPLATE = "QT - LEARNING EVALUATIONS"
LE_QUESTIONNARIE = "QUESTIONNAIRE-LEARNINGEVAL"
OLC_QUESTIONS = "QUESTIONS - ONLINECOURSE"
OLC_QUES_TEMPLATE = "QT - ONLINECOURSE"
OLC_QUESTIONNARIE = "QUESTIONNAIRE - ONLINECOURSE"
LA_COURSE = "COURSES"
LEARNING_CONTENT = "LEARNING CONTENT"
LEARNING_OFFERINGS = "OFFERINGS"
INST_LED_ACTIVITY = "INSTRUCTOR LED ACTIVITY"
SELF_PACED_ACT = "SELF PACED ACTIVITY"

# Health & Safety
HEAL_SAF_CONFIG_WRKBK= "HCM/Health and Safety/HCM HNS ConfigurationGuide.xlsx"
HandS_DFF = "MANAGE DESCRIPTIVE FLEX FIELDS"
QUESTIONS_HNS = "QUESTIONS"
QUESTIONNAIRES_TEMPLATES = "QUESTIONNAIRES TEMPLATES"
QUESTIONNAIRES_HNS = "QUESTIONNAIRES"
TARGET_DATE = "TARGET DATE"
ENABLE_DELIVERED_ALERTS = "ALERT COMPOSER"
INCIDENT_EVENTS_LOOKUPS = "INCIDENT EVENTS LOOKUPS"

#PAYROLL - OBJECT GROUPS
PAYROLL_OBJ_GRP_CONFIG_WRKBK = "HCM/Payroll/HCM Payroll ObjectGroups ConfigurationGuide.xlsx"
DST_OBJ_GRP_DED = "DEDUCTION CARD GROUP"
DST_OBJ_GRP_ELE = "ELEMENT GROUP"
DST_OBJ_GRP_PAY_R = "PAYROLL RELATIONSHIP GROUP"
DST_OBJ_GRP_PRO_I = "PROCESS INFORMATION GROUP"
DST_OBJ_GRP_WRK_REL = "WORK RELATIONSHIP GROUP"

#SEGMENT - Security Roles
SECURITY_OBJ_GRP_CONFIG_WRKBK = "SECURITY/SEC SEGMNET SECURITY ROLES.xlsx"
SEG_ROLE_OBJ_GRP = "SEGMENT SECURITY ROLES"

