ADMIN_COMMANDS_SETTINGS_NAME = "ADMIN_COMMANDS"
"""Expected setting name for enabling/disabling commands in the admin panel"""
ADMIN_COMMANDS_SETTINGS_HINT = "The setting should be a dict with keys as strings with the app names and the mapped values should be either the string literal '__all__' to show all commands for the app or an iterable of strings with the command names to show."
"""Hint for expected setting values"""
ALLOW_USER_INPUT_SETTINGS_NAME = "ADMIN_COMMANDS_ALLOW_USER_INPUT"
"""Expected setting name for enabling/disabling the user input field in the run command form"""
ALLOW_USER_INPUT_SETTINGS_HINT = "Set to True to allow user input to be passed to the command stdin when/if prompted, False to disable the field"
"""Hint for expected setting values"""
APP_NAME = "django_admin_commander"
"""Default app name"""
PERMISSION_NAME = "run_management_command"
"""Default permission name for running commands"""
FULL_PERMISSION_NAME = f"{APP_NAME}.{PERMISSION_NAME}"
"""The full permission name to be used in run command checks"""
