from numbers import Real
from typing import Mapping, Protocol, Union

class _Fileobj(Protocol):
    def fileno(self) -> int: ...

POLL_FLAGS_FOR_REPR: Mapping[str, int]

def getfd(fd: Union[_Fileobj, int]) -> int: ...
def repr_flags(mask: int, flags: Mapping[str, int]) -> str: ...
def smallest_multiple_atleast(base: int, minimum_value: int) -> int: ...
def uptruncate(x: Real) -> int: ...
