
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-07-24T15:18:27+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "939371b4d2b83d38e4388bdad91f34667fc7251c",
 "version": "1.4.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
