# LLM Model options for GUI

LLMS = [
    "AImlapi",
    "anthropic",
    "awsbedrock",
    "awsclaude",
    "azureopenAI",
    "azureAIfoundary",
    "cerebras",
    "cerebrasopenAI",
    "cohere",
    "deepinfra",
    "deepseek",
    "fireworks",
    "gemini",
    "groq",
    "huggingface",
    "ibm",
    "internlm",
    "litellmopenAI",
    "litellm",
    "lmstudio",
    "meta",
    "mistral",
    "nvidia",
    "ollama",
    "openAI",
    "openAIResponse",
    "openrouter",
    "perplexity",
    "sambanova",
    "together",
    "vercelv0",
    "xAI"
    ]