# Generated by Django 5.2.4 on 2025-07-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_convert_foreign_keys_to_integers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='county',
            name='id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='observation',
            name='id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='observer',
            name='id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='species',
            name='id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='state',
            name='id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='identifier',
            field=models.CharField(help_text='The unique identifier for the checklist.', max_length=15, primary_key=True, serialize=False, verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(help_text='The code used to identify the country.', max_length=2, primary_key=True, serialize=False, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='county',
            name='code',
            field=models.CharField(help_text='The code used to identify the county.', max_length=10, primary_key=True, serialize=False, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='location',
            name='identifier',
            field=models.CharField(help_text='The unique identifier for the location.', max_length=15, primary_key=True, serialize=False, verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='identifier',
            field=models.CharField(help_text='A global unique identifier for the observation.', max_length=15, primary_key=True, serialize=False, verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='observer',
            name='identifier',
            field=models.CharField(help_text='The code for the person submitted the checklist.', max_length=15, primary_key=True, serialize=False, verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='species',
            name='species_code',
            field=models.CharField(help_text='The species code, e.g. ostric2, used in the eBird API.', max_length=10, primary_key=True, serialize=False, verbose_name='species code'),
        ),
        migrations.AlterField(
            model_name='state',
            name='code',
            field=models.CharField(help_text='The code used to identify the state.', max_length=6, primary_key=True, serialize=False, verbose_name='code'),
        ),
    ]
