class Robot:
    def __init__(self, agent: str, txt: bytes) -> None: ...
    @property
    def delay(self) -> float | None: ...
    @property
    def sitemaps(self) -> list[str]: ...
    def allowed(self, url: str) -> bool: ...
