{
 "title": "Analyzer Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "language",
    "label": "Language",
    "query": "label_values(analyzer_duration_bucket, language)"
   }
  ]
 },
 "panels": [
  {
   "title": "Analyzer Scan Duration",
   "type": "histogram",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(language) (analyzer_duration_bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Analyzer Duration Count (Per Analyser Version)",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(analyzerVersion) (analyzer_duration_count{language=\"$language\"})",
     "legendFormat": "{{`{{ analysisPathLength }}`}}"
    }
   ]
  },
  {
   "title": "Analyzer Duration count (Per AnalysisPathLength)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(analysisPathLength, ) (analyzer_duration_count{language=\"$language\"})",
     "legendFormat": "{{`{{ analysisPathLength }}`}}"
    }
   ]
  },
  {
   "title": "Analyzer Duration Count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(language) (analyzer_duration_count)",
     "legendFormat": "{{`{{ le }}`}}"
    }
   ]
  },
  {
   "title": "Total Analyzer Duration Count for  \"$language\"",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "valueName": "total",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(language) (analyzer_duration_bucket{language=\"$language\"})",
     "legendFormat": "{{`{{ language }}`}} Total"
    }
   ]
  }
 ]
}