// This file is autogenerated. DO NOT EDIT

#pragma once
#include <semiwrap.h>

// wrapped header

#include <hal/PowerDistribution.h>
#error "::HAL_PowerDistributionFaults does not have a trampoline"
