#  Developed by CQ Inversiones SAS.
#  Copyright ©. 2019 - 2025. All rights reserved.
#  Desarrollado por CQ Inversiones SAS.
#  Copyright ©. 2019 - 2025. Todos los derechos reservados.

# Generated by Django 3.2.11 on 2025-02-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_zb_repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zibanurepositorypluginmodel',
            name='order',
            field=models.CharField(choices=[('id', '[Date Published] From the oldest to the most recent'), ('-id', '[Date Published] From the most recent to the oldest'), ('file_extended__title', '[Title] A-Z'), ('-file_extended__title', '[Title] Z-A')], default='-id', max_length=50, verbose_name='Order By'),
        ),
    ]
