# -*- coding: utf-8 -*-
EXCLUDED_LOADER_MODULE_OBJECTS = [
    "Blob",
    "BlobLoader",
    "OneDriveFileLoader",
    "WeatherDataLoader",
    "PebbloSafeLoader",
    "PolarDataFrameLoader",
    "CassandraLoader",
    "PsychicLoader",
    "PySparkDataFrameLoader",
    "RocksetLoader",
    "YuqueLoader",
    "YoutubeLoader",
    "AZLyricsLoader",
    # no force init
    "DocugamiLoader",
    "DropboxLoader",
    "GitHubIssuesLoader",
    "GithubFileLoader",
    "PagedPDFSplitter",
    "SharePointLoader",
    "GoogleDriveLoader",
    "OneDriveLoader",
    # no kwargs
    "AirtableLoader",
    "TelegramChatLoader",
    "UnstructuredAPIFileIOLoader",
    "UnstructuredAPIFileLoader",
    "UnstructuredFileIOLoader",
    "UnstructuredFileLoader",
    "UnstructuredODTLoader",
    "OracleTextSplitter",
    "OracleDocLoader",
    "TwitterTweetLoader",
    "TrelloLoader",
    "GoogleApiYoutubeLoader",
    "GoogleApiClient",
    "DiscordChatLoader",
    "AssemblyAIAudioTranscriptLoader",
    "ArcGISLoader",
]
