# -*- coding: utf-8 -*-
from langchain_community.document_loaders import (
    AirtableLoader,
    ArcGISLoader,
    AssemblyAIAudioTranscriptLoader,
    DiscordChatLoader,
    GoogleApiClient,
    GoogleApiYoutubeLoader,
    OracleDocLoader,
    OracleTextSplitter,
    TelegramChatLoader,
    TrelloLoader,
    TwitterTweetLoader,
    # UnstructuredAPIFileIOLoader,
    # UnstructuredAPIFileLoader,
    # UnstructuredFileIOLoader,
    # UnstructuredFileLoader,
)

__all__ = [
    "AirtableLoader",
    "ArcGISLoader",
    "AssemblyAIAudioTranscriptLoader",
    "DiscordChatLoader",
    "GoogleApiClient",
    "GoogleApiYoutubeLoader",
    "OracleDocLoader",
    "OracleTextSplitter",
    "TelegramChatLoader",
    "TrelloLoader",
    "TwitterTweetLoader",
    # "UnstructuredAPIFileIOLoader",
    # "UnstructuredAPIFileLoader",
    # "UnstructuredFileIOLoader",
    # "UnstructuredFileLoader",
]
