# coding: utf-8

"""
    Platform API Documentation

    Combined API documentation for all platform services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from do_sdk_platform.models.function_definition_schema_dto_input_schema_const_one_of import FunctionDefinitionSchemaDtoInputSchemaConstOneOf

class TestFunctionDefinitionSchemaDtoInputSchemaConstOneOf(unittest.TestCase):
    """FunctionDefinitionSchemaDtoInputSchemaConstOneOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FunctionDefinitionSchemaDtoInputSchemaConstOneOf:
        """Test FunctionDefinitionSchemaDtoInputSchemaConstOneOf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FunctionDefinitionSchemaDtoInputSchemaConstOneOf`
        """
        model = FunctionDefinitionSchemaDtoInputSchemaConstOneOf()
        if include_optional:
            return FunctionDefinitionSchemaDtoInputSchemaConstOneOf(
            )
        else:
            return FunctionDefinitionSchemaDtoInputSchemaConstOneOf(
        )
        """

    def testFunctionDefinitionSchemaDtoInputSchemaConstOneOf(self):
        """Test FunctionDefinitionSchemaDtoInputSchemaConstOneOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
