# coding: utf-8

"""
    Platform API Documentation

    Combined API documentation for all platform services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from do_sdk_platform.models.function_definition_schema_dto_executor_port_inner import FunctionDefinitionSchemaDtoExecutorPortInner

class TestFunctionDefinitionSchemaDtoExecutorPortInner(unittest.TestCase):
    """FunctionDefinitionSchemaDtoExecutorPortInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FunctionDefinitionSchemaDtoExecutorPortInner:
        """Test FunctionDefinitionSchemaDtoExecutorPortInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FunctionDefinitionSchemaDtoExecutorPortInner`
        """
        model = FunctionDefinitionSchemaDtoExecutorPortInner()
        if include_optional:
            return FunctionDefinitionSchemaDtoExecutorPortInner(
                description = '',
                externally_exposed = '',
                name = '',
                port = 1.337,
                protocol = 'TCP'
            )
        else:
            return FunctionDefinitionSchemaDtoExecutorPortInner(
                name = '',
                port = 1.337,
                protocol = 'TCP',
        )
        """

    def testFunctionDefinitionSchemaDtoExecutorPortInner(self):
        """Test FunctionDefinitionSchemaDtoExecutorPortInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
