# coding: utf-8

"""
    Platform API Documentation

    Combined API documentation for all platform services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from do_sdk_platform.models.nucleus_api_list_chat_thread_messages200_response_data_messages_inner_content_inner_any_of1_image_file import NucleusApiListChatThreadMessages200ResponseDataMessagesInnerContentInnerAnyOf1ImageFile

class TestNucleusApiListChatThreadMessages200ResponseDataMessagesInnerContentInnerAnyOf1ImageFile(unittest.TestCase):
    """NucleusApiListChatThreadMessages200ResponseDataMessagesInnerContentInnerAnyOf1ImageFile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NucleusApiListChatThreadMessages200ResponseDataMessagesInnerContentInnerAnyOf1ImageFile:
        """Test NucleusApiListChatThreadMessages200ResponseDataMessagesInnerContentInnerAnyOf1ImageFile
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NucleusApiListChatThreadMessages200ResponseDataMessagesInnerContentInnerAnyOf1ImageFile`
        """
        model = NucleusApiListChatThreadMessages200ResponseDataMessagesInnerContentInnerAnyOf1ImageFile()
        if include_optional:
            return NucleusApiListChatThreadMessages200ResponseDataMessagesInnerContentInnerAnyOf1ImageFile(
                file_id = ''
            )
        else:
            return NucleusApiListChatThreadMessages200ResponseDataMessagesInnerContentInnerAnyOf1ImageFile(
                file_id = '',
        )
        """

    def testNucleusApiListChatThreadMessages200ResponseDataMessagesInnerContentInnerAnyOf1ImageFile(self):
        """Test NucleusApiListChatThreadMessages200ResponseDataMessagesInnerContentInnerAnyOf1ImageFile"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
