# coding: utf-8

"""
    Platform API Documentation

    Combined API documentation for all platform services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from do_sdk_platform.models.api_get_admin_tool_executions200_response import ApiGetAdminToolExecutions200Response

class TestApiGetAdminToolExecutions200Response(unittest.TestCase):
    """ApiGetAdminToolExecutions200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiGetAdminToolExecutions200Response:
        """Test ApiGetAdminToolExecutions200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiGetAdminToolExecutions200Response`
        """
        model = ApiGetAdminToolExecutions200Response()
        if include_optional:
            return ApiGetAdminToolExecutions200Response(
                count = 10,
                data = [
                    do_sdk_platform.models.api_get_admin_tool_executions_200_response_data_inner.apiGetAdminToolExecutions_200_response_data_inner(
                        attributes = do_sdk_platform.models.tool_execution_dto.ToolExecutionDto(
                            completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            execution_id = '', 
                            job_outputs = do_sdk_platform.models.job_outputs.jobOutputs(), 
                            metadata = do_sdk_platform.models.metadata.metadata(), 
                            name = '', 
                            progress_report = '', 
                            resources_requested = do_sdk_platform.models.resources_requested.resourcesRequested(), 
                            resources_used = do_sdk_platform.models.resources_used.resourcesUsed(), 
                            started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            status = 'Quoted', 
                            tool = {key=alignment-tool, version=v1.0.2}, 
                            user_inputs = do_sdk_platform.models.user_inputs.userInputs(), 
                            user_outputs = do_sdk_platform.models.user_outputs.userOutputs(), ), 
                        id = 'abc123', 
                        type = 'toolExecution', )
                    ]
            )
        else:
            return ApiGetAdminToolExecutions200Response(
        )
        """

    def testApiGetAdminToolExecutions200Response(self):
        """Test ApiGetAdminToolExecutions200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
