# coding: utf-8

"""
    Platform API Documentation

    Combined API documentation for all platform services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from do_sdk_platform.models.update_subscription_schema_dto import UpdateSubscriptionSchemaDto

class TestUpdateSubscriptionSchemaDto(unittest.TestCase):
    """UpdateSubscriptionSchemaDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateSubscriptionSchemaDto:
        """Test UpdateSubscriptionSchemaDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateSubscriptionSchemaDto`
        """
        model = UpdateSubscriptionSchemaDto()
        if include_optional:
            return UpdateSubscriptionSchemaDto(
                existing_id = '',
                group_id = '',
                org_friendly_id = '',
                payment_id = '',
                period = 'Monthly',
                plan_id = '',
                qty = 1.337,
                subscription_id = ''
            )
        else:
            return UpdateSubscriptionSchemaDto(
                group_id = '',
                org_friendly_id = '',
                period = 'Monthly',
                plan_id = '',
                qty = 1.337,
        )
        """

    def testUpdateSubscriptionSchemaDto(self):
        """Test UpdateSubscriptionSchemaDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
