# coding: utf-8

"""
    Platform API Documentation

    Combined API documentation for all platform services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from do_sdk_platform.models.field_text import FieldText

class TestFieldText(unittest.TestCase):
    """FieldText unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FieldText:
        """Test FieldText
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FieldText`
        """
        model = FieldText()
        if include_optional:
            return FieldText(
                column_id = '',
                invalid_data = do_sdk_platform.models.invalid_data.InvalidData(
                    message = '', ),
                system_type = 'name',
                type = 'text',
                validation_status = 'valid',
                value = '',
                version = 1.337
            )
        else:
            return FieldText(
                column_id = '',
                type = 'text',
                validation_status = 'valid',
        )
        """

    def testFieldText(self):
        """Test FieldText"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
