# coding: utf-8

"""
    Platform API Documentation

    Combined API documentation for all platform services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from do_sdk_platform.models.add_column_file import AddColumnFile

class TestAddColumnFile(unittest.TestCase):
    """AddColumnFile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddColumnFile:
        """Test AddColumnFile
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddColumnFile`
        """
        model = AddColumnFile()
        if include_optional:
            return AddColumnFile(
                cardinality = 'one',
                cell_json_schema = None,
                config_file = do_sdk_platform.models.add_column_file_config_file.AddColumnFile_configFile(
                    allowed_extensions = [
                        ''
                        ], ),
                enabled_viewers = [
                    'code'
                    ],
                inline_viewer = 'molecule2d',
                is_required = True,
                json_field = '',
                name = '/UR,rZ',
                system_type = 'name',
                type = 'file'
            )
        else:
            return AddColumnFile(
                cardinality = 'one',
                name = '/UR,rZ',
                type = 'file',
        )
        """

    def testAddColumnFile(self):
        """Test AddColumnFile"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
