# coding: utf-8

"""
    Platform API Documentation

    Combined API documentation for all platform services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from do_sdk_platform.models.function_definition_schema_dto_executor import FunctionDefinitionSchemaDtoExecutor

class TestFunctionDefinitionSchemaDtoExecutor(unittest.TestCase):
    """FunctionDefinitionSchemaDtoExecutor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FunctionDefinitionSchemaDtoExecutor:
        """Test FunctionDefinitionSchemaDtoExecutor
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FunctionDefinitionSchemaDtoExecutor`
        """
        model = FunctionDefinitionSchemaDtoExecutor()
        if include_optional:
            return FunctionDefinitionSchemaDtoExecutor(
                container_concurrency = 1.337,
                environment = [
                    do_sdk_platform.models.function_definition_schema_dto_executor_environment_inner.FunctionDefinitionSchemaDto_executor_environment_inner(
                        name = '', 
                        value = '', )
                    ],
                image = '',
                method = 'POST',
                min_scale = 1.337,
                name = '',
                path = '',
                port = [
                    do_sdk_platform.models.function_definition_schema_dto_executor_port_inner.FunctionDefinitionSchemaDto_executor_port_inner(
                        description = '', 
                        externally_exposed = '', 
                        name = '', 
                        port = 1.337, 
                        protocol = 'TCP', )
                    ],
                resource_requirements = do_sdk_platform.models.function_definition_schema_dto_executor_resource_requirements.FunctionDefinitionSchemaDto_executor_resourceRequirements(
                    cpu = 1.337, 
                    memory = 1.337, ),
                response_start_timeout_seconds = 1.337,
                scale_down_delay_seconds = 1.337,
                timeout_seconds = 1.337,
                url = ''
            )
        else:
            return FunctionDefinitionSchemaDtoExecutor(
                container_concurrency = 1.337,
                image = '',
                method = 'POST',
                min_scale = 1.337,
                name = '',
                path = '',
                resource_requirements = do_sdk_platform.models.function_definition_schema_dto_executor_resource_requirements.FunctionDefinitionSchemaDto_executor_resourceRequirements(
                    cpu = 1.337, 
                    memory = 1.337, ),
                response_start_timeout_seconds = 1.337,
                timeout_seconds = 1.337,
        )
        """

    def testFunctionDefinitionSchemaDtoExecutor(self):
        """Test FunctionDefinitionSchemaDtoExecutor"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
