# coding: utf-8

"""
    Platform API Documentation

    Combined API documentation for all platform services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from do_sdk_platform.models.create_workflow_input_dto import CreateWorkflowInputDto

class TestCreateWorkflowInputDto(unittest.TestCase):
    """CreateWorkflowInputDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateWorkflowInputDto:
        """Test CreateWorkflowInputDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateWorkflowInputDto`
        """
        model = CreateWorkflowInputDto()
        if include_optional:
            return CreateWorkflowInputDto(
                cluster_drn = '',
                config = '',
                created_by = '',
                engine = 'nextflow',
                engine_parameters = None,
                engine_version = '',
                output_directory = '',
                parameters = None,
                pipeline_id = '',
                profile = '',
                sample_sheet = '',
                unit_sheet = '',
                volume_mounts = [
                    ''
                    ],
                working_dir = ''
            )
        else:
            return CreateWorkflowInputDto(
                cluster_drn = '',
                engine = 'nextflow',
                engine_parameters = None,
                engine_version = '',
                output_directory = '',
                parameters = None,
                pipeline_id = '',
                volume_mounts = [
                    ''
                    ],
                working_dir = '',
        )
        """

    def testCreateWorkflowInputDto(self):
        """Test CreateWorkflowInputDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
