# coding: utf-8

"""
    Platform API Documentation

    Combined API documentation for all platform services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from do_sdk_platform.models.credit_history_schema_dto import CreditHistorySchemaDto

class TestCreditHistorySchemaDto(unittest.TestCase):
    """CreditHistorySchemaDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreditHistorySchemaDto:
        """Test CreditHistorySchemaDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreditHistorySchemaDto`
        """
        model = CreditHistorySchemaDto()
        if include_optional:
            return CreditHistorySchemaDto(
                credits = 1.337,
                var_date = None,
                discount_credits = 1.337,
                id = '',
                item = '',
                total_credits = 1.337
            )
        else:
            return CreditHistorySchemaDto(
                credits = 1.337,
                var_date = None,
                discount_credits = 1.337,
                id = '',
                item = '',
                total_credits = 1.337,
        )
        """

    def testCreditHistorySchemaDto(self):
        """Test CreditHistorySchemaDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
