# Generated by Django 5.2.4 on 2025-07-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_squashed_0010_alter_species_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='When was the record updated.', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='When was the record updated.', null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='When was the record updated.', null=True),
        ),
        migrations.AddField(
            model_name='filter',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='When was the record updated.', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='When was the record updated.', null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='When was the record updated.', null=True),
        ),
        migrations.AddField(
            model_name='observer',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='When was the record updated.', null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='When was the record updated.', null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='When was the record updated.', null=True),
        ),
    ]
