
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-07-22T14:39:31-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "32734cca4a0241242f49aa52436361d77f7d63ea",
 "version": "2.66.1b0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
