
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-06-18T22:13:49+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "56994236bd76d029096eb5ad6ca3767a893bb4fa",
 "version": "0.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
