print("╔────────────────────────────────── WELCOME ──────────────────────────────────╗")
print("|                   ▁ ▂ ▄ ▅ ▆ ▇ █  AutoCADlib  █ ▇ ▆ ▅ ▄ ▂ ▁                  |")
print("|        AutoCADlib is a Python library designed for automating AutoCAD       |")
print("|         workflows,enabling efficient drawing manipulations, custom          |")
print("|             scripting, and automation of repetitive CAD tasks               |")
print("|                               using Python.                                 |")
print("|  version   : 0.1.9                                         By - JonesPeter  |")
print("|  github    : https://github.com/Jones-peter                                 |")
print("|                                                                             |")
print("╚──────────────────────────Unlimited CAD Automation───────────────────────────╝")
print("")